Added multiline output to search command
Yamato-Security/hayabusa pull request #1017
Opened 2023-04-27 15:13 UTC by hitenkoku

## What Changed

- added multiline output to search command

## Evidence

- main branch output( `-M` option  does not exist in search command on main branch)
```
PS > ./main.exe search -d ..\hayabusa-sample-evtx\ --keywords "null" -o main.csv
...
Total event log files: 584
Total file size: 137.1 MB

584 / 584 [==========================================================================] 100.00 %

Total findings: 44144

Elapsed time: 00:00:09.375
```

- This PR
```
> ./1004.exe search -d ..\hayabusa-sample-evtx\ --keywords "null" -o 1004.csv -M
...
Total event log files: 584
Total file size: 137.1 MB

584 / 584 [==========================================================================] 100.00 %

Total findings: 44144

Elapsed time: 00:00:09.570
```

### Result check

- main branch output
```
PS >cat main.csv | select-object -First 2
Timestamp,Hostname,Channel,Event ID,Record ID,EventTitle,AllFieldInfo,EvtxFile
2016-09-19T16:52:21.001572Z,DESKTOP-M5SN04R,Sec,4625,5392,Logon failure,AuthenticationPackageName: NTLM ﾂｦ FailureReason: %%2313 ﾂｦ IpAddress: 192.168.198.149 ﾂｦ IpPort: 51422 ﾂｦ KeyLength: 0 ﾂｦ LmPackageName: - ﾂｦ LogonProcessName: NtLmSsp ﾂｦ LogonType: 3 ﾂｦ ProcessId: 0x0 ﾂｦ ProcessName: - ﾂｦ Status: 0xc000006d ﾂｦ SubStatus: 0xc000006a ﾂｦ SubjectDomainName: - ﾂｦ SubjectLogonId: 0x0 ﾂｦ SubjectUserName: - ﾂｦ SubjectUserSid: S-1-0-0 ﾂｦ TargetDomainName: . ﾂｦ TargetUserName: Administrator ﾂｦ TargetUserSid: S-1-0-0 ﾂｦ TransmittedServices: - ﾂｦ WorkstationName: QQ2MHr71xALFHJqN,..\hayabusa-sample-evtx\DeepBlueCLI\smb-password-guessing-security.evtx
PS >
```

- This PR
```
PS >cat 1004.csv | select-object -First 30
Timestamp,Hostname,Channel,Event ID,Record ID,EventTitle,AllFieldInfo,EvtxFile
2016-09-19T16:52:21.001572Z,DESKTOP-M5SN04R,Sec,4625,5392,Logon failure,"AuthenticationPackageName: NTLM
FailureReason: %%2313
IpAddress: 192.168.198.149
IpPort: 51422
KeyLength: 0
LmPackageName: -
LogonProcessName: NtLmSsp
LogonType: 3
ProcessId: 0x0
ProcessName: -
Status: 0xc000006d
SubStatus: 0xc000006a
SubjectDomainName: -
SubjectLogonId: 0x0
SubjectUserName: -
SubjectUserSid: S-1-0-0
TargetDomainName: .
TargetUserName: Administrator
TargetUserSid: S-1-0-0
TransmittedServices: -
WorkstationName: QQ2MHr71xALFHJqN",..\hayabusa-sample-evtx\DeepBlueCLI\smb-password-guessing-security.evtx
2016-09-03T16:05:04.589585Z,IE10Win7,Sec,4688,11598,Process created,"CommandLine: C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsvw.exe -StartupEvent 4a4 -InterruptEvent 29c -NGENProcess 4a0 -Pipe 498 -Comment ""NGen Worker Process""
NewProcessId: 0xe74
NewProcessName: C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsvw.exe
ProcessId: 0x16d4
SubjectDomainName: WORKGROUP
SubjectLogonId: 0x3e7
SubjectUserName: IE10WIN7$
SubjectUserSid: S-1-5-18
```

2023-04-27 16:26 UTC, itiB commented
- #1004

2023-04-29 00:38 UTC, YamatoSecurity commented
@hitenkoku ありがとうございます！
確認したところ、文字列が無事にダブルクォートで囲まれて、フィールドデータにダブルクォートが入った場合は無事に２個のダブルクォートにエスケープしているのに、Excelにインポートしたら改行コードでCSVが壊れてしまいます。後でその原因を調べてみます。
やり方は`csv-timeline`と何も変わらないですよね？

2023-04-29 02:57 UTC, hitenkoku commented
コメントありがとうございます。確認してみます！

2023-04-29 11:04 UTC, hitenkoku commented
やり方は変わらないと思いますが、Excelへのインポートを行うという点でも確認してみます

2023-04-30 08:06 UTC, hitenkoku commented
@YamatoSecurity Excelのインポート方法ですが、以下の方法で対応できませんでしょうか？

https://tsukaeru-excel.com/line-feed-code-csv-powerquery

2023-04-30 19:04 UTC, YamatoSecurity approved these changes
LGTM! すみません、そもそもExcelはマルチラインに対応していないので、LibreOfficeで一回インポートして、XLSX等の形式に保存したらいけます。
参考: https://superuser.com/questions/319549/importing-multiline-cells-from-csv-file-into-excel
なので、これで大丈夫です！ありがとうございました！

2023-04-30 19:18 UTC, YamatoSecurity commented
> @YamatoSecurity Excelのインポート方法ですが、以下の方法で対応できませんでしょうか？
> 
> https://tsukaeru-excel.com/line-feed-code-csv-powerquery

リンク、ありがとうございます！手元にあるExcelと若干違って、ソースをダブルクリックしても改行をそのままにするというようなダイアログボックスが出て来ないので、ドキュメンテーションではLibreOfficeを使って〜と書いておきます。
時間があるときにもう一回ExcelのPowerQueryで方法ないか見てみます。

2023-04-30 20:18 UTC, YamatoSecurity requested changes
@hitenkoku すみません、
```
Output:
  -o, --output <FILE>  Save the search results in CSV format (ex: search.csv)
  -M, --multiline      Output event field information in multiple rows
```
の順番を
```
Output:
  -M, --multiline      Output event field information in multiple rows
  -o, --output <FILE>  Save the search results in CSV format (ex: search.csv)
```
にできますか？

2023-04-30 22:34 UTC, hitenkoku commented
@YamatoSecurity  ご指摘ありがとうございます。https://github.com/Yamato-Security/hayabusa/pull/1017/commits/a81281c66b888c1919185ef8377232b1b4e9062b で対応完了しましたのでご確認のほどよろしくお願いいたします。

> ```
> Output:
>   -o, --output <FILE>  Save the search results in CSV format (ex: search.csv)
>   -M, --multiline      Output event field information in multiple rows
> ```
> 
> の順番を
> 
> ```
> Output:
>   -M, --multiline      Output event field information in multiple rows
>   -o, --output <FILE>  Save the search results in CSV format (ex: search.csv)
> ```
> 
> にできますか？

2023-04-30 22:40 UTC, YamatoSecurity approved these changes
LGTM! Thank you!

2023-04-30 23:09 UTC, hitenkoku commented
ありがとうございます！それではそのままマージさせていただきます

2023-04-30 23:09 UTC, merged