finalize 2.5.1
Yamato-Security/hayabusa pull request #1050
Opened 2023-05-14 23:17 UTC by YamatoSecurity

I would like to release the new rules with the new convertor so want to release this minor release with the memory improvement. It's already past Mothers Day in Japan but still Mothers Day in other parts of the world so I decided to make it a Mothers Day release. =)

2023-05-14 23:32 UTC, hitenkoku approved these changes
@YamatoSecurity Thanks for your pull request.
LGTM.

2023-05-14 23:39 UTC, fukusuket requested changes

2023-05-14 23:39 UTC, fukusuket commented on CHANGELOG-Japanese.md
> +## 2.5.1 [2023/05/04] "Mothers Day Release"
There was a typo, could you please check it? :)
```suggestion
## 2.5.1 [2023/05/14] "Mothers Day Release"
```

2023-05-14 23:43 UTC, YamatoSecurity commented
@fukusuket Thanks for the typo fix!

2023-05-15 00:00 UTC, fukusuket approved these changes
LGTM!🚀

2023-05-15 00:14 UTC, merged