[WIP] add support for `|all`
Yamato-Security/hayabusa pull request #1060
Opened 2023-05-28 13:52 UTC by kazuminn

## What Changed

fix #1038 
 
Working on Progress

## Evidence

Please describe the functionality gained by merging this pull-request and the evidence that the bug has been fixed.

2023-05-29 14:07 UTC, kazuminn commented
レビューお願いします。

2023-05-30 00:07 UTC, fukusuket approved these changes
以下3点を確認しました！LGTMです！！🚀

1. 修正前後で`csv-timeline -d sample-hayabusa-evt --debug`の結果ファイル差分なし。メモリ使用量同等

2. 以下ルールの検知数と`search --keywords mimikatz`の件数が一致
```
detection:
    selection:
        '|all':
            - mimikatz
    condition: selection
```

3. 以下ルールの検知数と`search --keywords mimikatz` + `cat result.csv | grep -i invoke | wc -l` の件数が一致
```
detection:
    selection:
        '|all':
            - invoke
            - mimikatz
    condition: selection
```

2023-05-30 03:23 UTC, hitenkoku reviewed
一部不明点についてコメントしました

2023-05-30 03:23 UTC, hitenkoku commented on src/detections/rule/matchers.rs
> +            for key in keys_all.iter_mut().skip(1) {
keyで参照している要素は1つのみですが、iter_mutを回して処理をしている理由はありますでしょうか。keys_allの配列要素を参照するほうがわかりやすいかと思われます

2023-05-30 03:23 UTC, hitenkoku commented on src/detections/rule/matchers.rs
> +                    Self::convert_to_fast_match(format!("allOnly*{pattern}*").as_str(), true)
この場合|endswithで指定されてallOnlyという文字列が入ってしまっていた場合はこのAllOnlyと合致してしまいませんか

2023-05-30 03:23 UTC, hitenkoku commented on src/detections/rule/mod.rs
> +            // 配列はALL条件と解釈する。
L332の内容と矛盾するため、|allの場合はなどの追記をしたほうが良いかと思われます。

2023-05-30 03:25 UTC, hitenkoku requested changes
endswithとallOnlyの区別ができなくなる個所が見つかったため解決するまでマージブロックします

2023-05-30 03:26 UTC, hitenkoku requested changes
endswithとallOnlyの区別ができなくなる個所が見つかったため解決するまでマージブロックします

2023-05-30 03:26 UTC, hitenkoku commented on src/detections/rule/matchers.rs
> +        } else if s.starts_with("allOnly") {
...|endswithでallOnlyという値が指定されてもこちらの判定に入ると思われますので修正が必要と思われます

2023-05-31 08:54 UTC, kazuminn commented on src/detections/rule/matchers.rs
> +        } else if s.starts_with("allOnly") {
直しました。

2023-05-31 08:54 UTC, kazuminn commented on src/detections/rule/mod.rs
> +            // 配列はALL条件と解釈する。
コメントを追記しました。

2023-05-31 08:55 UTC, kazuminn commented on src/detections/rule/matchers.rs
> +            for key in keys_all.iter_mut().skip(1) {
今後他にも機能を追加する際に楽になるんじゃないかと思いましたが、ちょっと冗長的すぎるので、配列にしました。

2023-05-31 13:19 UTC, YamatoSecurity commented
@kazuminn 対応ありがとうございます！念のために確認ですが、`UserData`にも対応していますか？

2023-05-31 13:52 UTC, kazuminn commented
@YamatoSecurity はい。対応してます。

2023-05-31 23:42 UTC, hitenkoku approved these changes
LGTM

2023-06-01 05:54 UTC, merged