Added timeline offset offset option
Yamato-Security/hayabusa pull request #1167
Opened 2023-08-28 01:34 UTC by hitenkoku

## What Changed

- Added timeline offset offset option in `csv-timeline`, `json-timeline`, `search`, `eid-metrics`, `logon-summary`, `pivot-keywords-list`

I would appreciate it if you could review when you have time.

2023-08-29 10:32 UTC, fukusuket requested changes

2023-08-29 10:32 UTC, fukusuket commented on src/detections/configs.rs
> +    /// Scan just the most recent number of days(example: 1y, 30d, 24h, etc...)
Would `ex:` be better when aligned with other Usage?

2023-08-29 11:30 UTC, fukusuket commented on src/detections/configs.rs
> +    /// Scan just the most recent number of days(example: 1y, 30d, 24h, etc...)
Thank you so much for quick fix!

2023-08-29 14:17 UTC, hitenkoku commented
@fukusuket  Thanks for your review!
I forgot 'M'(month) timeformat.....
I implemented 'M' timeformat in .e46046a88f31d69d7326147f929fc11a19901666

2023-08-29 14:27 UTC, fukusuket commented
@hitenkoku 
I've confirmed that `M` works as well!(and https://github.com/Yamato-Security/hayabusa/pull/1167#pullrequestreview-1600288030 works) LGTM!!🚀 
```
% ./hayabusa logon-summary -d ../hayabusa-sample-evtx -o out.csv -C --timeline-offset 12M -q
...
First Timestamp: 2022-09-25 04:53:36.327 +09:00
Last Timestamp: 2023-01-24 20:54:42.899 +09:00
```

2023-08-29 23:57 UTC, hitenkoku commented
@fukusuket  How quick confirm! Thanks you.

2023-08-30 22:06 UTC, YamatoSecurity commented
@hitenkoku Thanks so much!
Can you add error handling when the format is not correct?
For example, when I do:
`./target/release/hayabusa  csv-timeline -d ../hayabusa-sample-evtx -o delete.csv -C --timeline-offset hogehoge -q`
it still scans like it works but I would like to output something like `Invalid timeline offset. Please use one of the following formats: 1y, 3M, 30d, 24h, 30m`

2023-08-31 08:39 UTC, hitenkoku commented
Thank you very much for confirming.

@YamatoSecurity I forgot to add about error handling. Thanks for pointing that out.
I fixed in 4fe71f10fad3bf1adbae023a53652a522ec6303a. Could you please check it?

> @hitenkoku Thanks so much! Can you add error handling when the format is not correct? For example, when I do: `./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -o delete.csv -C --timeline-offset hogehoge -q` it still scans like it works but I would like to output something like `Invalid timeline offset. Please use one of the following formats: 1y, 3M, 30d, 24h, 30m`

2023-08-31 11:49 UTC, YamatoSecurity approved these changes
@hitenkoku LGTM! Thanks so much!

2023-08-31 13:06 UTC, merged