feat: add GitHub Actions for auto build packages
Yamato-Security/hayabusa pull request #1424
Opened 2024-10-05 08:15 UTC by fukusuket

## What Changed
- Closed #1239 

## How to use

## Action's Artifacts

2024-10-05 08:24 UTC, fukusuket commented
### Windows packages
<img width="868" alt="スクリーンショット 2024-10-05 17 23 23" src="https://github.com/user-attachments/assets/5098478b-f3ef-4a32-a26c-7f30e0a25934">

2024-10-05 08:25 UTC, fukusuket commented
### Linux packaegs
<img width="866" alt="スクリーンショット 2024-10-05 17 24 48" src="https://github.com/user-attachments/assets/4a8be072-dd9c-4fcf-8769-583d5a164086">

2024-10-05 08:26 UTC, fukusuket commented
### macOS packages
<img width="857" alt="スクリーンショット 2024-10-05 17 26 01" src="https://github.com/user-attachments/assets/1d88d26b-eae9-49eb-8da3-48c80400648a">

2024-10-05 08:45 UTC, fukusuket commented
Sorry, we need a `.git` folder under `rules` to run `update-rules`, so I am checking....

2024-10-05 08:47 UTC, YamatoSecurity requested changes
@fukusuket Looks great! That helps out a lot! Just one thing, can you also create a `all-packages.zip` file that contains all the binary releases and documentation so I can download everything in one go instead of having to download each package individually?
(I still want to keep the individual packages though)

2024-10-05 08:52 UTC, fukusuket commented
@YamatoSecurity 
Thank you for checking! I forgot about all-packages.zip😅 I'll implement it!💪

2024-10-05 14:29 UTC, fukusuket commented
@YamatoSecurity 
I added all-packages.zip! Could you please confirm?
<img width="843" alt="スクリーンショット 2024-10-05 23 25 33" src="https://github.com/user-attachments/assets/be2dc4e0-b4ae-496e-a500-6546fc0590c6">

<img width="946" alt="スクリーンショット 2024-10-05 23 28 13" src="https://github.com/user-attachments/assets/a138428c-6bb8-4cec-859a-b6d8f5039914">

2024-10-05 14:31 UTC, fukusuket commented
### macOS
I have confirmed that the binaries work properly on macOS.
```
% ./hayabusa-2.18.0-mac-aarch64 csv-timeline -d ~/Hayabusa/hayabusa-sample-evtx -w -D -n -u -o timeline.csv -q -C
Start time: 2024/10/05 23:30

Total event log files: 585
Total file size: 137.2 MB

Loading detection rules. Please wait.

Excluded rules: 20
Noisy rules: 12

Deprecated rules: 216 (4.72%)
Experimental rules: 431 (9.42%)
Stable rules: 255 (5.57%)
Test rules: 3,627 (79.30%)
Unsupported rules: 45 (0.98%)

Hayabusa rules: 181
Sigma rules: 4,393
Total detection rules: 4,574

Creating the channel filter. Please wait.

Evtx files loaded after channel filter: 575
Detection rules enabled after channel filter: 4,496

Output profile: standard

Scanning in progress. Please wait.

[00:00:06] 575 / 575   [========================================] 100%

Scanning finished. Please wait while the results are being saved.

Rule Authors:

╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Florian Roth (197)                Nasreddine Bencherchali (122)    Zach Mathis (121)                  oscd.community (120)            │
│ frack113 (108)                    Tim Shelton (34)                 Daniil Yugoslavskiy (26)           Teymur Kheirkhabarov (25)       │
│ Jonhnathan Ribeiro (23)           Thomas Patzke (21)               Tim Rauch (18)                     Timur Zinniatullin (17)         │
│ Christian Burkard (17)            Markus Neis (16)                 Roberto Rodriguez @Cyb3r... (15)   E.M. Anhaus (14)                │
│ Roberto Rodriguez (14)            Elastic (13)                     Michael Haag (12)                  Samir Bousseaden (11)           │
│ OTR (9)                           Endgame) (9)                     Victor Sergeev (9)                 Swachchhanda Shrawan Poudel (9) │
│ juju4 (8)                         Natalia Shornikova (8)           David ANDRE (7)                    Endgame (7)                     │
│ JHasenbusch (7)                   Ecco (6)                         X__Junior (6)                      omkar72 (5)                     │
│ Sander Wiebing (5)                Gleb Sukhodolskiy (5)            Christopher Peacock @sec... (4)    Janantha Marasinghe (4)         │
│ Andreas Hunkeler (4)              keepwatch (4)                    Tobias Michalski (4)               Arnim Rupp (4)                  │
│ @neu5ron (4)                      Max Altgelt (4)                  Mauricio Velazco (4)               Vadim Khrykov (3)               │
│ pH-T (3)                          Dimitrios Slamaris (3)           FPT.EagleEye (3)                   Nikita Nazarov (3)              │
│ wagga (3)                         Mark Russinovich (3)             FPT.EagleEye Team (3)              @twjackomo (3)                  │
│ Sherif Eldeeb (3)                 James Pemberton@4A616D6573 (3)   Vasiliy Burov (3)                  Harish Segar (3)                │
│ Austin Songer @austinsonger (3)   Eric Conrad (3)                  Ilyas Ochkov (3)                   SOC Prime (3)                   │
│ Aleksey Potapov (3)               Wojciech Lesicki (3)             Jakob Weinzettl (3)                Yusuke Matsui (3)               │
│ Perez Diego (3)                   Daniel Bohannon (3)              Cyb3rEng (3)                       Hieu Tran (3)                   │
│ Fukusuke Takahashi (3)            Alexandr Yampolskyi (3)          SCYTHE @scythe_io (3)              @dreadphones (2)                │
│ Justin C. (2)                     D3F7A5105 (2)                    @SBousseaden (2)                   Zach Stanford @svch0st (2)      │
│ Relativity (2)                    Sreeman (2)                      Nik Seetharaman (2)                Trent Liffick (2)               │
│ Karneades (2)                     Yassine Oukessou (2)             Tom Ueltschi (2)                   @2xxeformyshirt (2)             │
│ elhoim (2)                        Tony Lambert) (2)                Hosni Mribah (2)                   Sean Metcalf (2)                │
│ Zaw Min Htun (2)                  Tony Lambert (2)                 Anton Kutepov (2)                  Oleg Kolesnikov @securon... (2) │
│ James Pemberton@4A616D65... (2)   Mark Woan (2)                    Chakib Gzenayi (2)                 Maxime Thiebaut (2)             │
│ Bartlomiej Czyz (2)               James Dickenson (2)              Modexp (2)                         Romaissa Adjailia (2)           │
│ EagleEye Team (1)                 Georg Lauenstein (1)             Teymur Kheirkhabarov @He... (1)    Matthew Green @mgreen27 (1)     │
│ Omer Faruk Celik (1)              Andreas Braathen (1)             SBousseaden (1)                    John Lambert (1)                │
│ David Burkett (1)                 Jack Croock (1)                  Stephen Lincoln `@slinco... (1)    @Joseliyo_Jstnk (1)             │
│ Dave Kennedy (1)                  CD_ROM_ (1)                      vburov (1)                         NVISO (1)                       │
│ Alec Costello (1)                 Jason Lynch (1)                  @oscd_initiative (1)               Pushkarev Dmitry (1)            │
│ Center for Threat Inform... (1)   Markus Neis @Karneades (1)       Anish Bogati (1)                   Aaron Herman (1)                │
│ James Pemberton @4A616D6573 (1)   Austin Songer (1)                Joshua Wright (1)                  @caliskanfurkan_ (1)            │
│ fuzzyf10w (1)                     Ali Alwashali (1)                Stamatis Chatzimangou (1)          Joseliyo Sanchez (1)            │
│ Dominik Schaudel (1)              rukawa (1)                       Mangatas Tondang (1)               Ivan Dyachkov (1)               │
│ Bhabesh Raj (1)                   David Strassegger (1)            Kutepov Anton (1)                  Dmitriy Lifanov (1)             │
│ KevTheHermit (1)                  Julia Fomina (1)                 @kostastsale (1)                   Dan Beavin) (1)                 │
│ Maxence Fossat (1)                blueteam0ps (1)                  Tom U. @c_APT_ure (1)              Nextron Systems (1)             │
│ Tuan Le (1)                       Benjamin Delpy (1)               Furkan CALISKAN (1)                Timon Hackenjos (1)             │
│ Open Threat Research (1)          Tom Kern (1)                     @atc_project (1)                   Mustafa Kaan Demir (1)          │
│ Oddvar Moe (1)                    Bartlomiej Czyz @bczyz1 (1)      j4son (1)                          Christopher Peacock @Sec... (1) │
│ Josh Nickels (1)                  Scott Dermott (1)                Cédric Hien (1)                    Jai Minton (1)                  │
│ Swisscom CSIRT (1)                Jeff Warren (1)                  Sorina Ionescu (1)                 @gott_cyber (1)                 │
│ @scythe_io (1)                    SCYTHE (1)                       Jose Rodriguez (1)                 Semanur Guneysu @semanurtg (1)  │
│ Sami Ruohonen (1)                 Cedric MAURUGEON (1)             @signalblur (1)                    Margaritis Dimitrios (1)        │
│ Maxim Pavlunin (1)                @svch0st (1)                     Fatih Sirin (1)                    Subhash Popuri (1)              │
│ mdecrevoisier (1)                 @juju4 (1)                                                                                          │
╰─────────────────────────────────╌────────────────────────────────╌──────────────────────────────────╌─────────────────────────────────╯

Results Summary:

Events with hits / Total events: 21,119 / 46,413 (Data reduction: 25,294 events (54.50%))

Total | Unique detections: 34,593 | 740
Total | Unique critical detections: 53 (0.15%) | 21 (0.00%)
Total | Unique high detections: 5,731 (16.57%) | 282 (9.32%)
Total | Unique medium detections: 2,444 (7.07%) | 264 (14.05%)
Total | Unique low detections: 6,667 (19.27%) | 104 (35.68%)
Total | Unique informational detections: 19,698 (56.94%) | 69 (3 [...]

2024-10-05 21:28 UTC, YamatoSecurity approved these changes
@fukusuket LGTM! I tested the mac intel binary works without any problems. Thanks so much!

2024-10-05 21:28 UTC, merged

2024-10-06 00:24 UTC, fukusuket commented
### hayabusa-2.18.0-win-x64-live-response.zip
```
C:\tmp\hayabusa-2.18.0-win-x64-live-response>hayabusa-2.18.0-win-x64.exe

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Hayabusa v2.18.0 - Dev Build
Yamato Security (https://github.com/Yamato-Security/hayabusa - @SecurityYamato)

Usage:
  hayabusa.exe <COMMAND> [OPTIONS]
  hayabusa.exe help <COMMAND> or hayabusa.exe <COMMAND> -h

Commands:
  computer-metrics     Print computer name metrics
  csv-timeline         Save the timeline in CSV format
  eid-metrics          Print event ID metrics
  json-timeline        Save the timeline in JSON/JSONL format
  level-tuning         Tune alert levels (default: ./rules/config/level_tuning.txt)
  list-contributors    Print the list of contributors
  list-profiles        List the output profiles
  logon-summary        Print a summary of successful and failed logons
  pivot-keywords-list  Create a list of pivot keywords
  search               Search all events by keyword(s) or regular expression
  set-default-profile  Set default output profile
  update-rules         Update to the latest rules in the hayabusa-rules github repository
  help                 Print this message or the help of the given subcommand(s)


C:\tmp\hayabusa-2.18.0-win-x64-live-response>hayabusa-2.18.0-win-x64.exe update-rules -q
Start time: 2024/10/06 09:22

Rules file encoded_rules.yml updated successfully.
Config file rules_config_files.txt updated successfully.

C:\tmp\hayabusa-2.18.0-win-x64-live-response>hayabusa-2.18.0-win-x64.exe csv-timeline -l -q -w -D -n -u -o timeline.csv
Start time: 2024/10/06 09:23

Total event log files: 356
Total file size: 250.2 MB

Loading detection rules. Please wait.

Excluded rules: 20
Noisy rules: 12

Deprecated rules: 216 (4.72%)
Experimental rules: 433 (9.45%)
Stable rules: 255 (5.57%)
Test rules: 3,631 (79.28%)
Unsupported rules: 45 (0.98%)

Hayabusa rules: 181
Sigma rules: 4,399
Total detection rules: 4,580

Creating the channel filter. Please wait.

Evtx files loaded after channel filter: 26
Detection rules enabled after channel filter: 3,880

Output profile: standard

Scanning in progress. Please wait.

[00:00:08] 26 / 26   [========================================] 100%

Scanning finished. Please wait while the results are being saved.

Rule Authors:

╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Zach Mathis (39)                  frack113 (18)                    Florian Roth (11)            Nasreddine Bencherchali (5)   Fukusuke Takahashi (4)   Roberto Rodriguez @Cyb3r... (4) │
│ Arnim Rupp (3)                    oscd.community (3)               Bhabesh Raj (2)              Ján Trenčanský (2)            Tim Shelton (2)          Open Threat Research (2)        │
│ Harish Segar (2)                  Cian Heasley (1)                 Nikita Nazarov (1)           Gleb Sukhodolskiy (1)         Timur Zinniatullin (1)   @redcanary (1)                  │
│ Timur Zinniatullin oscd.... (1)   James Pemberton@4A616D6573 (1)   Zach Stanford @svch0st (1)   Roberto Rodriguez (1)         OTR (1)                  Teymur Kheirkhabarov (1)        │
╰─────────────────────────────────╌────────────────────────────────╌────────────────────────────╌─────────────────────────────╌────────────────────────╌─────────────────────────────────╯

Results Summary:

Events with hits / Total events: 29,943 / 123,842 (Data reduction: 93,899 events (75.82%))

Total | Unique detections: 30,691 | 81
Total | Unique critical detections: 381 (1.24%) | 3 (0.00%)
Total | Unique high detections: 223 (0.73%) | 10 (40.74%)
Total | Unique medium detections: 712 (2.32%) | 19 (19.75%)
Total | Unique low detections: 25,226 (82.19%) | 16 (23.46%)
Total | Unique informational detections: 4,149 (13.52%) | 33 (12.35%)

Dates with most total detections:
critical: 2024-06-01 (46), high: 2024-06-04 (24), medium: 2024-07-27 (173), low: 2024-09-28 (3,886), informational: 2024-09-28 (479)

Top 5 computers with most unique detections:
critical: mouse (3)
high: mouse (10)
medium: mouse (18), MyComputer (2)
low: mouse (16)
informational: mouse (33), MyComputer (1), DESKTOP-CNG7416 (1), DESKTOP-9HFNL0J (1)

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Top critical alerts:                                            Top high alerts:                                                                │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Defender Alert (Severe) (372)                                   Antivirus Relevant File Paths Alerts (158)                                      │
│ Antivirus Password Dumper Detection (8)                         Microsoft Defender Blocked from Loading Unsigned DLL (24)                       │
│ Antivirus Exploitation Framework Detection (1)                  Antivirus Hacktool Detection (9)                                                │
│ n/a                                                             Powershell Token Obfuscation - Powershell (8)                                   │
│ n/a                                                             Defender Alert (High) (7)                                                       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:                                              Top low alerts:                                                                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Potentially Malicious PwSh (541)                                Credential Manager Enumerated (23,995)                                          │
│ Uncommon PowerShell Hosts (83)                                  Credential Manager Accessed (351)                                               │
│ Suspicious Non PowerShell WSMAN COM Provider (24)               Rare Service Installations (310)                                                │
│ BITS Transfer Job With Uncommon Or Suspicious Remote TLD (22)   CodeIntegrity - Unmet Signing Level Requirements By File Under Validation (299) │
│ Usage Of Web Request Commands And Cmdlets - ScriptBlock (11)    Volume Shadow Copy Mount (83)                                                   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top informational alerts:                                                                                                                       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Logon (Service) (Noisy) (1,305)                                 RDS Sess Start (Noisy) (194)                                                    │
│ PwSh Engine Started (318)                                       RDS Sess Logon (194)                                                            │
│ Svc Installed (313)                                             RDS Sess Logoff (189)                                                           │
│ WMI Provider Started (262)                                      Office App PopUp (180)                                                          │
│ Bits Job Created (214)                                          RDS Sess Disconnect (133)                                                       │
 [...]

2024-10-06 00:27 UTC, fukusuket commented
### hayabusa-2.18.0-win-x64.zip
```
C:\tmp\hayabusa-2.18.0-win-x64>hayabusa-2.18.0-win-x64.exe

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Hayabusa v2.18.0 - Dev Build
Yamato Security (https://github.com/Yamato-Security/hayabusa - @SecurityYamato)

Usage:
  hayabusa.exe <COMMAND> [OPTIONS]
  hayabusa.exe help <COMMAND> or hayabusa.exe <COMMAND> -h

Commands:
  computer-metrics     Print computer name metrics
  csv-timeline         Save the timeline in CSV format
  eid-metrics          Print event ID metrics
  json-timeline        Save the timeline in JSON/JSONL format
  level-tuning         Tune alert levels (default: ./rules/config/level_tuning.txt)
  list-contributors    Print the list of contributors
  list-profiles        List the output profiles
  logon-summary        Print a summary of successful and failed logons
  pivot-keywords-list  Create a list of pivot keywords
  search               Search all events by keyword(s) or regular expression
  set-default-profile  Set default output profile
  update-rules         Update to the latest rules in the hayabusa-rules github repository
  help                 Print this message or the help of the given subcommand(s)


C:\tmp\hayabusa-2.18.0-win-x64>hayabusa-2.18.0-win-x64.exe update-rules -q
Start time: 2024/10/06 09:25


You currently have the latest rules.

C:\tmp\hayabusa-2.18.0-win-x64>hayabusa-2.18.0-win-x64.exe csv-timeline -l -w -q -D -n -u -o timeline.csv
Start time: 2024/10/06 09:26

Total event log files: 356
Total file size: 250.2 MB

Loading detection rules. Please wait.

Excluded rules: 20
Noisy rules: 12

Deprecated rules: 216 (4.72%)
Experimental rules: 431 (9.42%)
Stable rules: 255 (5.57%)
Test rules: 3,627 (79.30%)
Unsupported rules: 45 (0.98%)

Hayabusa rules: 181
Sigma rules: 4,393
Total detection rules: 4,574

Creating the channel filter. Please wait.

Evtx files loaded after channel filter: 26
Detection rules enabled after channel filter: 2,282

Output profile: standard

Scanning in progress. Please wait.

[00:00:09] 26 / 26   [========================================] 100%

Scanning finished. Please wait while the results are being saved.

Rule Authors:

╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Zach Mathis (39)                  frack113 (18)                    Florian Roth (11)            Nasreddine Bencherchali (5)   Fukusuke Takahashi (4)   Roberto Rodriguez @Cyb3r... (4) │
│ Arnim Rupp (3)                    oscd.community (3)               Bhabesh Raj (2)              Ján Trenčanský (2)            Tim Shelton (2)          Open Threat Research (2)        │
│ Harish Segar (2)                  Cian Heasley (1)                 Nikita Nazarov (1)           Gleb Sukhodolskiy (1)         Timur Zinniatullin (1)   @redcanary (1)                  │
│ Timur Zinniatullin oscd.... (1)   James Pemberton@4A616D6573 (1)   Zach Stanford @svch0st (1)   Roberto Rodriguez (1)         OTR (1)                  Teymur Kheirkhabarov (1)        │
╰─────────────────────────────────╌────────────────────────────────╌────────────────────────────╌─────────────────────────────╌────────────────────────╌─────────────────────────────────╯

Results Summary:

Events with hits / Total events: 29,965 / 123,905 (Data reduction: 93,940 events (75.82%))

Total | Unique detections: 30,713 | 81
Total | Unique critical detections: 381 (1.24%) | 3 (0.00%)
Total | Unique high detections: 223 (0.73%) | 10 (40.74%)
Total | Unique medium detections: 712 (2.32%) | 19 (19.75%)
Total | Unique low detections: 25,246 (82.20%) | 16 (23.46%)
Total | Unique informational detections: 4,151 (13.52%) | 33 (12.35%)

Dates with most total detections:
critical: 2024-06-01 (46), high: 2024-06-04 (24), medium: 2024-07-27 (173), low: 2024-09-28 (3,886), informational: 2024-09-28 (479)

Top 5 computers with most unique detections:
critical: mouse (3)
high: mouse (10)
medium: mouse (18), MyComputer (2)
low: mouse (16)
informational: mouse (33), MyComputer (1), DESKTOP-CNG7416 (1), DESKTOP-9HFNL0J (1)

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Top critical alerts:                                            Top high alerts:                                                                │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Defender Alert (Severe) (372)                                   Antivirus Relevant File Paths Alerts (158)                                      │
│ Antivirus Password Dumper Detection (8)                         Microsoft Defender Blocked from Loading Unsigned DLL (24)                       │
│ Antivirus Exploitation Framework Detection (1)                  Antivirus Hacktool Detection (9)                                                │
│ n/a                                                             Powershell Token Obfuscation - Powershell (8)                                   │
│ n/a                                                             Defender Alert (High) (7)                                                       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:                                              Top low alerts:                                                                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Potentially Malicious PwSh (541)                                Credential Manager Enumerated (24,015)                                          │
│ Uncommon PowerShell Hosts (83)                                  Credential Manager Accessed (351)                                               │
│ Suspicious Non PowerShell WSMAN COM Provider (24)               Rare Service Installations (310)                                                │
│ BITS Transfer Job With Uncommon Or Suspicious Remote TLD (22)   CodeIntegrity - Unmet Signing Level Requirements By File Under Validation (299) │
│ Usage Of Web Request Commands And Cmdlets - ScriptBlock (11)    Volume Shadow Copy Mount (83)                                                   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top informational alerts:                                                                                                                       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Logon (Service) (Noisy) (1,306)                                 RDS Sess Start (Noisy) (194)                                                    │
│ PwSh Engine Started (318)                                       RDS Sess Logon (194)                                                            │
│ Svc Installed (313)                                             RDS Sess Logoff (189)                                                           │
│ WMI Provider Started (262)                                      Office App PopUp (180)                                                          │
│ Bits Job Created (215)                                          RDS Sess Disconnect (133)                                                       │
╰───────────────────────────────────────────────────────────────╌───────────────────────────────────────────────────────────── [...]