Pivot Keyword List機能の追加
Yamato-Security/hayabusa pull request #412
Opened 2022-02-24 05:36 UTC by kazuminn

fix #393.

# なにこれ
(levelがlow以上の)アラートがある場合は、以下のフィールドから"Pivot Keyword"(攻撃者の足跡になる送信元のIPアドレス、ログオンID等々)をリストアップして、テキストファイルに保存する機能です。キーワードリストで、大量のinformationalログをgrepして、攻撃者の痕跡だけを抽出するための機能です。(informationalログが多すぎて解析が難しいという意見(クレーム？）が来ていたので、これで不要なinformationalログが減るはずです。）
また、キーワードの一覧を見るだけで、どのユーザや端末が攻撃を受けている可能性があるかパッと見て分かるので、fast forenscisに役立ちます。

# 以下のように実装しました。

オプション: -p / --pivot-keywords-list -o <ファイル名> or -p 
(ただの、-oだけだと、csv出力になる。)
例: ./hayabusa.exe --min-level high --pivot-keywords-list -o keywords.txt -d ./sample-evtx

-oがあると、スキャン後にファイルに出力する。
-oがないと、タイムラインではなく、標準出力する。

hashSetをつかっているので、キーワードが重複することはない。
空("-")、("127.0.0.1")、("::1")になっている可能性があって、誤検知になりそうなので、すべてで無視している。

キーワードをハードコーディングではなく、設定ファイルで自由に修正できるようにしました。config/pivot_keywords.txtで設定できます。

取り敢えず、アラートに以下のフィールドが存在する場合は、Pivot Keywords Listに追加します。（デフォルトでのconfig設定）
```
%SubjectUserName%
%TargetUserName%
%User%
%SubjectLogonId%
%TargetLogonId%
%WorkstationName%
%IpAddress%
%Image%
```

# evidence 
```
> .\target\release\hayabusa.exe  -D -n -r C:\Users\warug\hayabusa-rules\ -f 'C:\Users\warug\hayabusa-sample-evtx\YamatoSecurity\T1218.004_Signed Binary Proxy Execution InstallUtil\sysmon.evtx'  -p

██╗  ██╗ █████╗ ██╗   ██╗ █████╗ ██████╗ ██╗   ██╗███████╗ █████╗
██║  ██║██╔══██╗╚██╗ ██╔╝██╔══██╗██╔══██╗██║   ██║██╔════╝██╔══██╗
███████║███████║ ╚████╔╝ ███████║██████╔╝██║   ██║███████╗███████║
██╔══██║██╔══██║  ╚██╔╝  ██╔══██║██╔══██╗██║   ██║╚════██║██╔══██║
██║  ██║██║  ██║   ██║   ██║  ██║██████╔╝╚██████╔╝███████║██║  ██║
╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝
   by Yamato Security

Analyzing event files: 1
Hayabusa rules: 46
Sigma rules: 1139
Ignored rules: 7
Rule parsing errors: 0
Total enabled detection rules: 1185

1 / 1 [====================================================================================================] 100.00 % 
Elapsed Time: 00:00:02.262

The following pivot keywords were found:
Processes: C:\Windows\Microsoft.NET\Framework\v4.0.30319\InstallUtil.exe,
field's list: (%Image%, )

Ip Addresses:
field's list: (%IpAddress%, )

Users: CYBERCAT\pc1-user,
field's list: (%User%, %SubjectUserName%, %TargetUserName%, )

Logon IDs:
field's list: (%TargetLogonId%, %SubjectLogonId%, )

Workstation Names:
field's list: (%WorkstationName%, )
```

# 手動test項目
* -pなしで、-oを実行　→csvがファイルに出力されるか
* -pだけで、pivot keywords listが標準出力されるか
* -p -oを付けて、pivot keywords listがファイルに出力されるか

(ちなみに、コードにおいて、-oオプションの依存度が複雑になってくるので、今後手を入れる場合は、何か対策が必要になってくる。）

2022-02-24 05:50 UTC, kazuminn commented
おっと、rebaseが必要になるので、少しお待ちください。

2022-02-24 06:52 UTC, kazuminn commented
CI通りました。 @hitenkoku さん　@YamatoSecurity さん。
レビューお願いします。

2022-02-24 07:39 UTC, kazuminn commented
2GBのBig-Securityでスキャンかけましたが、あまり出てこない結果になりました。こんなもんなんですね。

```
The following pivot keywords were found:
Workstation Names: SEC504STUDENT,
field's list: (%WorkstationName%, )

Ip Addresses:
field's list: (%IpAddress%, )

Logon IDs: 0x0, 0x36eea,
field's list: (%TargetLogonId%, %SubjectLogonId%, )

Users: DefaultAccount, WDAGUtilityAccount, Administrator, Guest, Sec504,
field's list: (%TargetUserName%, %User%, %SubjectUserName%, )

Processes:
field's list: (%Image%, )
```

2022-02-24 09:57 UTC, hitenkoku requested changes
一応ソースコードレベルで気になるところを指摘しました。まだ動作確認はしていません。

2022-02-24 09:57 UTC, hitenkoku commented on src/detections/configs.rs
> +    -p --pivot-keywords-list 'Create a list of pivot keywords.'
@YamatoSecurity こちらですが、pivot-keywords-listとoutpurの出力を両方指定できたほうよいが思いますがどうでしょうか

今回の話だとinforationalで大量にデータが出てきてしまってよくないという話だったと思いますが、min-levelと併用すれば一回の動作で出してくれた方がよいように思えます

2022-02-24 09:57 UTC, hitenkoku commented on src/detections/configs.rs
> +pub fn load_pivot_keywords(path: &str) {
できればpub関数は外部から読み込む可能性があるので /// でdocコメントをつけてください。

2022-02-24 09:57 UTC, hitenkoku commented on src/detections/pivot.rs
> +        pivot_keyword
L26と同じ内容のinsertがここに入っている理由は何でしょうか。
もし理由があるならコメントで記載してください。不要なら削除してください

2022-02-24 09:57 UTC, hitenkoku commented on src/detections/pivot.rs
> +    pub fn insert_pivot_keyword(&mut self, event_record: &Value) {
できればpub関数は外部から読み込む可能性があるので /// でdocコメントをつけてください。

2022-02-24 09:57 UTC, hitenkoku commented on src/detections/pivot.rs
> +    //PIVOT_KEYWORDはグローバルなので注意が必要。
「注意が必要」だと何を意味しているか分からないので、何が懸念事項化を記載して下さい

2022-02-24 09:57 UTC, hitenkoku commented on src/main.rs
> +            && !configs::CONFIG
複数の個所でこのコンフィグの値を確認するようであればstaticで見るようにしてもよいと思います

2022-02-24 11:29 UTC, hitenkoku commented on src/detections/configs.rs
> +    -p --pivot-keywords-list 'Create a list of pivot keywords.'
打合せで解決したためこちらは対応完了で問題ないでです

2022-02-24 11:35 UTC, hitenkoku requested changes
記載が漏れておりましたが、documentも日本語だけでもよいので作成してください。
英語版は @YamatoSecurity に添削してもらうなりしましょう。

2022-03-07 01:56 UTC, kazuminn commented on src/detections/pivot.rs
> +        pivot_keyword
@hitenkoku 
同じinsertではなく、keywordsメンバとfielsメンバをそれぞれinsertしています。
もう少し良い書き方がありそうですが、もしあったら教えてほしいです。

2022-03-07 02:33 UTC, kazuminn commented on src/detections/configs.rs
> +pub fn load_pivot_keywords(path: &str) {
done

2022-03-07 02:33 UTC, kazuminn commented on src/detections/pivot.rs
> +    pub fn insert_pivot_keyword(&mut self, event_record: &Value) {
done

2022-03-07 02:33 UTC, kazuminn commented on src/detections/pivot.rs
> +    //PIVOT_KEYWORDはグローバルなので注意が必要。
done

2022-03-07 02:33 UTC, kazuminn commented on src/main.rs
> +            && !configs::CONFIG
done

2022-03-07 02:35 UTC, kazuminn commented
clippyの対応とドキュメントの作成に着手します。

2022-03-07 05:56 UTC, kazuminn commented
一応、自分の範囲のclippyのwarnは直した。

2022-03-07 06:27 UTC, kazuminn commented
@hitenkoku @YamatoSecurity 
ドキュメント書くのに時間かかりそうなので、
先にこのプルリクをマージしていただいた方が気持ち的にすごく楽なので、
先にマージする感じのほうが個人的にいいです。それで、お願いしたいです。

レビューの修正とclippyのwarn処理は終わりました。

2022-03-07 08:59 UTC, hitenkoku requested changes
修正分も含めて、確認しました。いくつか指摘をしましたのでご確認ください。

ドキュメント作成と機能の作成を分けてしまうと、ドキュメントの更新が遅れて、develop側の実態が合わなくなってしまう可能性が出てくるので、ドキュメントを追加した上でマージ対応をさせてもらったほうが後々良いと思いますので、このプルリクエストはドキュメントを書いてからマージをするようにしましょう。

2022-03-07 08:59 UTC, hitenkoku commented on .gitignore
> +/rules
rulesはgitignoreにつけないでください。 rulesはsubmoduleであるため、gitignoreをつけなくても変更されたファイルは確認をしない(しても特定のコミットを参照するlinkの修正対応を行うのみ)

2022-03-07 08:59 UTC, hitenkoku commented on src/detections/configs.rs
> +pub fn load_pivot_keywords(path: &str) {
確認しました。問題ありません。

2022-03-07 08:59 UTC, hitenkoku commented on src/detections/pivot.rs
> +    pub fn insert_pivot_keyword(&mut self, event_record: &Value) {
確認しました。問題ありません。

2022-03-07 08:59 UTC, hitenkoku commented on src/detections/pivot.rs
> +        pivot_keyword
失礼いたしました。ただこの処理を見ているとconfigのkeyを増やせるようには見えないです。

一括の投入方法とかは、HashMap::fromとかを使うとかを使ってinsertを行わないで設定する方法はあります。あと、configの方ですでにkeyを取得しているのであればここのnewのところはいらないのではないのでしょうか(単純にentry("key名").or_insertで投入できます)

2022-03-07 12:02 UTC, kazuminn commented on .gitignore
> +/rules
対応します。

2022-03-07 12:12 UTC, kazuminn commented
@hitenkoku @YamatoSecurity え、keyは固定でfields(%hoge%のやつ)が自由に設定できる仕様の話だったと思います。

> ただこの処理を見ているとconfigのkeyを増やせるようには見えないです。

(keyをconfigでカスタマイズする実装することもできる気はしますが)

2022-03-07 12:31 UTC, kazuminn commented
あ、key決め打ちなんて話はなかったですね笑笑

Keyも自由に設定できるように実装してみます。

2022-03-07 13:49 UTC, hitenkoku commented
issueでは固定である旨を書いていません。あと @YamatoSecurity  はissueで以下のように書いています。単純に読めば、項目のつ追加対応が容易にできるようにするほうが良いと思います。

@YamatoSecurity  本件、念の為ご確認をお願いいたします。

> (後でプロセスID等も追加したいかも）
refs #393

2022-03-07 14:43 UTC, hitenkoku commented
@kazuminn  が以下のように発言をまとめています。 @YamatoSecurity はキーワードは任意で読み込めるようにという依頼をしているようです。

https://github.com/Yamato-Security/hayabusa/issues/393#issuecomment-1048746533


> ちょっと、Slackの方でお話をして方針変わってきたので、メモっておきます。最終的にどのように実装したかは、プルリクエストのほうに書いておきます。
> 
> ザックさんの発言
> キーワードをできればハードコーディングではなく、設定ファイルで自由に修正できたら理想ですが、できそうですか？
> -> できそう。
> 
> ザックさんの発言
> 以下のよう使い方の方が良い気がしてきました：
> -p / --pivot-keywords-listを指定する際に通常のフォレンジックタイムラインではなく、ピボット一覧を表示します。-p -o file.txtを指定する場合は結果をfile.txtに保存します。ファイルが存在する場合は上書きせず、エラーを出します。
> (Fast forensicsはスピードを重視するが、エビデンスや解析データ等を上書きすると、大変なことになる可能があるので）
> そうすると、--pivot-keywordsの後にfile.txtの必要性が無くなります。
> もし、既存の-oオプションを利用するのが難しいのであれば、仕様に書いてあるように、アウトプットファイル名を-p <file.txt>にして、更に-oオプションが付けられた場合は「You cannot specify -o / --output when using -p / --pivot-keywords-list」というエラーを出しましょう。
> ->　前者でやる。

2022-03-08 01:58 UTC, hitenkoku commented on src/detections/pivot.rs
> +    //PIVOT_KEYWORDはグローバルなので注意が必要。
確認しました。

2022-03-08 01:58 UTC, hitenkoku commented on src/main.rs
> +            && !configs::CONFIG
確認しました

2022-03-08 11:51 UTC, YamatoSecurity commented
返事が遅くなってすみません！ はい、キーも自由に指定したいです。
pivot_keywords.txtの
```
key,field1,field2,field3
Users,SubjectUserName,TargetUserName,User
Logon IDs,SubjectLogonId,TargetLogonId
Workstation Names,WorkstationName
Ip Addresses,IpAddress
Processes,Image
```
はキーも含めて全部カスタマイズできると思っていました。

また、色々追加の注文がありまして、すみません。。

今の画面出力：
```
Ip Addresses: 10.23.123.11, 172.16.66.1,
field's list: (%IpAddress%, )
```
を
```
Ip Addresses (%IpAddress%): 
10.23.123.11
172.16.66.1
```
という風に出力できますか？
変更点：
1. (%Field%, )の最後の不要のコンマの削除 -> (%Field)
2. (%Field%)をキーの右側に出力する
3. コンマを改行にする

また、`grep -f keywords.txt timeline.csv`のようにキーワードがあるイベント・アラートだけ抽出したいのですが、そのために、コンマの代わりに改行にして、キーワードリストを別々のファイルに分けた方が良さそうです。

例えば`-o keywords`を指定したら、
keywords-Users.txt
keywords-LogonIDs.txt
keywords-Processes.txt
keywords-IpAddresses.txt
keywords-WorkstationNames.txt
という様々なファイルが出力されます。誤検知のキーワードも毎回出て来そうなので、アナリストが手動でテキストファイルを確認して、使えなさそうなキーワードを削除した上で、`grep -f keywords.txt timeline.csv`等で絞ったタイムラインを作成するイメージです。

2022-03-09 02:52 UTC, kazuminn commented
@YamatoSecurity 
（また仕様の変更ですかい笑）
keyのカスタマイズと、出力の変更、かしこまりました。

たしかに、その方がtimelineを絞れて、良さそうです。

2022-03-09 03:43 UTC, YamatoSecurity commented
すまない！ m(__)m
宜しくお願いします！

2022-03-09 21:21 UTC, YamatoSecurity commented
@kazuminn 
後で私がドキュメンテーションを書きましょうか？
(すぐできると思うので）

2022-03-10 02:18 UTC, hitenkoku commented
ドキュメントの作成者は誰でも良いのですが、ドキュメントでpull requestをマージする状態にはすでにかけてるといいなぁと思っています。(というか書けていないと、結局ドキュメント作成が後手に回ってしまうと大変なので……)

2022-03-10 03:29 UTC, kazuminn commented
@YamatoSecurity 
お願いしますー。

2022-03-10 03:30 UTC, kazuminn commented
Dさんが言っていたように、configファイルを以下のように変更します。

```
 Users,SubjectUserName
 Users,TargetUserName
 Users,User

2022-03-10 04:17 UTC, hitenkoku commented
split_at関数を使えば以前の形式でも問題なく実装できそうですが、(1個目のみ読み込んで、それ以降は対応する値として一括投入)実装は任せます

> Dさんが言っていたように、configファイルを以下のように変更します。
> 
> ```
>  Users,SubjectUserName
>  Users,TargetUserName
>  Users,User
>  
> ```

2022-03-14 07:21 UTC, kazuminn commented
私の実装したデータ構造がよくなくて、（ザックさんの言っているファイル出力ができなかったので、）、すこし抜本的？に書き直します。
（なんでこんなデータ構造にしたんだ。。。）

2022-03-28 06:14 UTC, kazuminn commented
出力をmain()でなくて、emit_csv()でしたほうがいいんじゃないか。との話がありましたが、#216でemit_csv()を並列毎に移動するかもしれない話があったので、main()に残しています。

2022-03-28 06:26 UTC, kazuminn commented on .gitignore
> +/rules
対応しておきました。

2022-03-28 07:41 UTC, kazuminn commented
# 2GBのbig-security.evtxのエビデンス(-pのみで標準出力)
```
The following pivot keywords were found:
Ip Addresses: ( %IpAddress% ):

Processes: ( %Image% ):

Workstation Names: ( %WorkstationName% ):
SEC504STUDENT

Users: ( %TargetUserName% %User% %SubjectUserName% ):
DefaultAccount
WDAGUtilityAccount
Administrator
Guest
Sec504

Logon IDs: ( %SubjectLogonId% %TargetLogonId% ):
0x0
0x36eea
```

2022-03-28 07:44 UTC, kazuminn commented
# -pと-oのファイル出力のエビデンス(-o keywordとすると、keyword-Users.txtに以下が記載される）

```
Users: ( %SubjectUserName% %TargetUserName% %User% ):
DefaultAccount
WDAGUtilityAccount
Administrator
Guest
Sec504
```

2022-03-28 07:47 UTC, kazuminn commented
@hitenkoku さん　@YamatoSecurity さん。
実装完了し、CIも通りました。
動作確認やレビューをお願いします。

YamatoSecurityさんには、ドキュメントの作成をお願いします。　🙏

2022-03-28 22:10 UTC, YamatoSecurity commented
ありがとうございます！今出張中で少々お待ち下さいね。

2022-03-30 02:36 UTC, YamatoSecurity commented
<img width="1133" alt="Screen Shot 2022-03-30 at 11 03 28" src="https://user-images.githubusercontent.com/71482215/160739539-54394247-5db3-427b-af58-6eafbdf9dd91.png">

config/pivot_keywords.txtが入っていないので、panicで死にます。
test_files配下のpivot_keywords.txtをコピーしたら、無事に実行できました。
config配下にもpivot_keywords.txtを用意してくれますか？

2022-03-30 02:38 UTC, YamatoSecurity commented
<img width="1514" alt="Screen Shot 2022-03-30 at 11 05 49" src="https://user-images.githubusercontent.com/71482215/160739667-6568990c-0eaf-4174-a41b-50fb527011f0.png">

`-o` を指定した際に(例：`-o keywords`)、最後に
```
Outputted results to the following files:
keywords-Ip Address.txt
keywords-Logon IDs.txt
等々
```
を出力できますか？
今は最後に何も結果が出ないので、ユーザにとって分かりにくいと思います。

2022-03-30 02:40 UTC, YamatoSecurity commented
<img width="446" alt="Screen Shot 2022-03-30 at 11 34 35" src="https://user-images.githubusercontent.com/71482215/160739944-0d9ab8cc-cf07-4fb6-aa5f-6f3b51af0eaa.png">

SysmonのProcessGuidフィールドもキーワードリストに追加したいと思って追加してみましたが、何も結果ありません。
理由分かりますか？
`./target/release/hayabusa -u` した後に
`./target/release/hayabusa -p -d ../../hayabusa-sample-evtx  -r ./rules/hayabusa/sysmon`
で検証しています。

あとは完璧でした！

2022-03-30 05:29 UTC, hitenkoku commented
@YamatoSecurity 確認してみましたが ProcessGuidがeventkey_alias.txtに存在していないことが原因かと思われます。

> 
> SysmonのProcessGuidフィールドもキーワードリストに追加したいと思って追加してみましたが、何も結果ありません。 理由分かりますか？ `./target/release/hayabusa -u` した後に `./target/release/hayabusa -p -d ../../hayabusa-sample-evtx -r ./rules/hayabusa/sysmon` で検証しています。
>

2022-03-30 07:09 UTC, YamatoSecurity commented
なるほど！ありがとうございます！

2022-03-31 04:52 UTC, kazuminn commented
@YamatoSecurity 
> config/pivot_keywords.txtが入っていないので、panicで死にます。
> test_files配下のpivot_keywords.txtをコピーしたら、無事に実行できました。
> config配下にもpivot_keywords.txtを用意してくれますか？
コピーして使うことを伝えるのを忘れてました。申し訳ないです。
hayabusa-rulesのconfigにプルリクを出しておきます。

2022-03-31 05:28 UTC, kazuminn commented
@YamatoSecurity 
こんな感じに、標準出力するように実装しました。

```
Outputted results to the following files:
sysmon4-Logon IDs.txt
sysmon4-Users.txt
sysmon4-Workstation Names.txt
sysmon4-Processes.txt
sysmon4-Ip Addresses.txt
```

2022-03-31 05:43 UTC, kazuminn commented
@YamatoSecurity デフォルトの設定ファイルはこれでよいですか？
変更したいのであれば、おっしゃってください。

```
Users.SubjectUserName
Users.TargetUserName
Users.User
Logon IDs.SubjectLogonId
Logon IDs.TargetLogonId
Workstation Names.WorkstationName
Ip Addresses.IpAddress
Processes.Image
```

2022-04-02 22:38 UTC, YamatoSecurity approved these changes
OKです！ありがとうございます！

2022-04-02 22:39 UTC, YamatoSecurity commented
ドキュメンテーションお待たせしました。書いてみました。

@hitenkoku お手数をかけますが、確認＆和訳をお願いできますか？

2022-04-02 22:41 UTC, YamatoSecurity commented
おっと、こちらの環境では出力メッセージを編集しても問題なかったけど、githubではbuild failedになっています。誰か確認して頂けますか？

2022-04-03 06:53 UTC, kazuminn commented
@YamatoSecurity 
CIをパスするようにしておきました。
（ほぼ、$ cargo fmt　しただけ）

英語ドキュメントありがとうございます。

2022-04-03 09:31 UTC, kazuminn commented
@YamatoSecurity 
やっぱり、一回目の実行でcsvを作って、二回目の実行でキーワードファイルを作って、grepしてtimelineをファストフォレンジックするのって、大きいevtxだと時間がかかって、手間です。（2GBの手動テストは、大変でした。まぁ、マシンスペックが低いからかもしれませんが）

時間短縮ために、
同時にcsvも吐いた方がよいと思っていて、

今の使い方の、 `-p -o tagets`　でtargets.csvも吐けるように、できますが、どうでしょうか?
(targets-timeline.csvなんかでいける）

前に、そんな感じのことを会議でyamatosecurityさんが言ったときは、Dさんが複雑になると言っていましたが、今やろうと思うと、そんなに複雑ではないのでは、と思いました。

-oはcsvを吐いてくれて、-pを付けると、キーワードファイルも吐ける。みたいに、ユーザーも理解しやすいと思います。

リリースも近いので、次のバージョンに回しても大丈夫です。

2022-04-03 10:35 UTC, hitenkoku approved these changes

2022-04-03 10:39 UTC, hitenkoku commented
前回話した際は-pをつけた場合と-pをつけなかった場合で出力されるものが異なる(その時は-pをつけていたらここで話をしているpivot keywordlistの出力。-pをつけていなかったら今までの結果のcsvの出力)となっている場合にusageのときに説明がつけづらいと考えていました。

-p をつけていてもつけていなくても今までのcsvが出力されるのであれば -p側のusageに 「-oを追加すれば別途pivot keyword listのcsvを出力する」旨を書けば特に混乱はないと思っています。

2022-04-03 10:41 UTC, hitenkoku commented
私は特に決定権ないので @YamatoSecurity  に一任します

2022-04-03 20:25 UTC, YamatoSecurity commented
@kazuminn 提案ありがとうございます！`grep -f`は確かに手間なので、書いてくれたように`-o`指定の時だけ、targets-timeline.csvも作成されるようにお願いできたら嬉しいです。
ただ、速度がかなり遅くなるのであれば、別のオプションに分けたいかもしれません。
例えば、`-m critical`等を指定した場合は、一旦`-m critical`スキャンで見つけたキーワードリストを作った後に、info以上の全イベント・アラートのタイムラインを作ってgrepするので、速度が倍になると思っていたのですが、そこまで遅くならないですか？ (再スキャンの必要はないとか？）
(気持ち的に1.5倍ぐらいまで遅くなっても同時にpivot keywordのタイムラインを作りたいけど、2倍近く遅くなるのであれば、別のオプションにしたいかもです。

@hitenkoku ご意見ありがとうございます！確かに勘違いする人も居るかもしれないので、最後のメッセージの出力時に「Saved a timeline filtered by the pivot keywords found.」等を追加しておけば、伝わると思います。

2022-04-04 06:02 UTC, kazuminn commented
@YamatoSecurity 
なるほど。
timeline csv作る場合とキーワード作る場合のフィルタリングlevelが違う使い方の想定なんですね。
たしかに、高々2回スキャンする(selectを二回する）感じで、2倍近くになります。

遅くなるので、たしかに、オプションのほうが良いと思いました。

もしやるなら、別のプルリクでやりましょうか。

2022-04-04 10:47 UTC, YamatoSecurity commented
そうですね。`-m`オプションも組み合わせないと、infoのキーワードも全部入るので、結局タイムラインはあまり変わらないと思います。`-m`指定無しのキーワードリストも有用な情報ですが、(特にログが多い場合は）基本的に`-m medium`以上のレベル指定を想定しています。また、127.0.0.1のローカルホストとか、SYSTEMプロセス等々除外したいキーワードもあるので、取り敢えず今の機能で色々検証した上で、キーワードタイムライン機能をお願いできたらと思います。

2022-04-04 14:19 UTC, hitenkoku commented
@YamatoSecurity ドキュメントを確認しました。特に問題はないと思います。また、 https://github.com/Yamato-Security/hayabusa/pull/412/commits/6009779210f0744ec6929694e6bd134135f52795 で日本語訳を追加しましたのでご確認のほど、よろしくお願いいたします。

2022-04-04 14:25 UTC, kazuminn commented
日本語訳ありがとうございます。LGTM

2022-04-05 12:13 UTC, YamatoSecurity commented
@hitenkoku ありがとうございます！一箇所だけ分かりにくいところがあったので、修正してみました。ご確認ください。
問題が無ければマージしましょう。

2022-04-05 12:14 UTC, hitenkoku commented
@YamatoSecurity 　確認いたしました。修正ありがとうございます。問題ないと思いますのでマージ対応をしておきます

2022-04-05 12:17 UTC, merged