Hotfix/moved rule configs to hayabusa rules repo#409
Yamato-Security/hayabusa pull request #414
Opened 2022-02-25 09:07 UTC by hitenkoku

fixed #409 

## What Changed
- #409 でルール関連のconfigをhayabusa-rules側に移動させたため以下のファイルの参照を./rules/...という形に変更しました
- #409 でhayabusa-rules側に移動させたconfigを読み込むためrulesフォルダのsubmoduleの参照を更新しました

2022-02-25 10:28 UTC, hitenkoku commented
確認してみたところ、configファイルがないことによって一部テストが通らなくなっているようです。ワークフローを少し変えるかテストを無効化する必要がありそうです

2022-02-25 10:33 UTC, kazuminn commented
test_files/にconfigファイルを複製して、そこを参照するようにテストのコードを書き換えるのはどうですか？

2022-02-25 10:47 UTC, YamatoSecurity requested changes
<img width="1145" alt="Screen Shot 2022-02-25 at 19 41 36" src="https://user-images.githubusercontent.com/71482215/155701630-5da1f349-674a-412f-8ea1-a7aca30a012d.png">

rulesディレクトリが空の場合は、こういう分かりにくいpanicエラーが出てしまうので、ユーザがhayabusa-rulesからrulesディレクトリをダウンロードしていない場合に「The rules configuration files were not found. Please run -u / --update to download the latest rules and config files from the hayabusa-rules git repository.」を出力するのはどうですか？

2022-02-25 10:59 UTC, YamatoSecurity commented
readmeのパスを更新して、不要の設定ファイルを削除しました。

2022-02-25 11:15 UTC, hitenkoku commented
@YamatoSecurity  https://github.com/Yamato-Security/hayabusa/pull/414#pullrequestreview-893530902 は #392 の話なのでここでは取り扱わないということで良いですか？

2022-02-25 11:17 UTC, hitenkoku commented
testfiles/configを設定してテストコード側も修正して実施したのですがエラーが発生しています。

2022-02-25 11:18 UTC, hitenkoku commented
@YamatoSecurity  失礼いたしました。ファイル削除とかの対応が漏れていました。ご対応いただき誠にありがとうございます。

2022-02-25 14:04 UTC, hitenkoku commented
確認してみましたが、rulesの参照ができていないことと、github actionの中でsubmoduleを取得しない設定になっていたことが原因のようです。

2022-02-25 14:27 UTC, hitenkoku commented
@YamatoSecurity  @itiB 

修正が完了しました。大変お手数をおかけしてしまい申し訳ございませんがご確認のほどよろしくお願い致します。

@YamatoSecurity  

https://github.com/Yamato-Security/hayabusa/pull/414#pullrequestreview-893530902 の件ですが、確認したところ、 rulesフォルダが存在しないor ymlファイルがないときにファイルのメタデータの読み込みが失敗しているのにも関わらず以降の処理を行ったことが原因でした。

一旦、エラーは出ないように修正を完了しました。
また、ルールの読み込みが0件だったときのエラー表示は https://github.com/Yamato-Security/hayabusa/pull/392#issuecomment-1050276570 で対応をしておりますので文面変更が必要であれば #392 に記載のほどよろしくお願いいたします。

2022-02-25 20:32 UTC, YamatoSecurity approved these changes
OKです。ありがとうございました！

2022-02-26 09:19 UTC, merged

2022-02-26 09:19 UTC, hitenkoku commented
確認ありがとうございます。投入をさせていただきます