added clippy workflow #428
Yamato-Security/hayabusa pull request #429
Opened 2022-02-28 02:00 UTC by hitenkoku

Fixed #428 

## What Changed
- Added rust-clippy workflow

2022-02-28 02:51 UTC, hitenkoku commented
GitHub Actionの動作が確認できるまではこのpull requestは無視してください。動作確認が完了次第、レビューリクエストをだします

2022-03-19 06:20 UTC, hitenkoku commented
developをマージしましたが、一部warningsが出ていました
cargo clippy -- -D warningsを実行しても出てきませんでしたが、https://github.com/Yamato-Security/hayabusa/pull/429/commits/639059b86af6cd6d335bd29ac0ef75105e842f48 で修正をしておきました

2022-03-19 08:36 UTC, YamatoSecurity commented
これ、どうやって検証できますか？developにマージしてみて、その後警告が出るコードが通るかどうかチェックするとか？

2022-03-19 12:09 UTC, hitenkoku commented
そうですね。これをマージしたらdevelopから他のブランチにプルリクエストしたときに確認できます。このプルリクエストでも確認ができます

2022-03-19 12:13 UTC, hitenkoku commented
@YamatoSecurity 

clippyのエラーがない場合
- https://github.com/Yamato-Security/hayabusa/pull/429/checks

clippyのエラーが出た場合
- https://github.com/Yamato-Security/hayabusa/pull/429/checks?check_run_id=5609897252

2022-03-19 18:03 UTC, itiB requested changes
上にある [fixed clippy::needless_match](https://github.com/Yamato-Security/hayabusa/pull/429/commits/639059b86af6cd6d335bd29ac0ef75105e842f48) のコミット横に×がついていてClippyが検知したらわかる感じですね、
うまく動作しているように見えます！

不要そうなWFの削除をお願いします:pray:

2022-03-19 18:03 UTC, itiB commented on .github/workflows/rust.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
パーミッションを調べるWFは消してしまっても大丈夫かと思います！

2022-03-20 13:18 UTC, hitenkoku commented on .github/workflows/rust.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
コメントありがとうございます。また、アノテーションをつけないclippyについてもパーミッションで分岐をつけて対応していたのでそちらも消しておきますね

2022-03-20 13:29 UTC, hitenkoku commented on .github/workflows/rust.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@itiB https://github.com/Yamato-Security/hayabusa/pull/429/commits/ac9b6102e320aa3e44441fba6410071d254176fe で対応完了しました。ご確認のほどよろしくお願いいたします

2022-03-20 17:45 UTC, itiB approved these changes
確認しました！いい感じだと思います！

2022-03-21 03:45 UTC, merged

2022-03-21 03:45 UTC, hitenkoku commented
確認ありがとうございます。マージしておきました。