removed tools/sigmac
Yamato-Security/hayabusa pull request #441
Opened 2022-03-04 11:31 UTC by hitenkoku

## What Changed

- [x] moved tools/sigmac to hayabusa-rules repo
- [ ] changed submodule commit

2022-03-04 11:47 UTC, hitenkoku commented
https://github.com/Yamato-Security/hayabusa-rules/pull/16 のpull requestがマージされたらこちらをready状態にしてレビュー依頼をします

2022-03-05 06:42 UTC, hitenkoku commented
hayabusa-rulesのv1.1.0にsubmoduleの指定を変更しておきました。これで修正が完了しましたのでご確認のほどよろしくお願いいたします。

2022-03-05 08:24 UTC, YamatoSecurity requested changes
１つだけリンクを直す必要があると思います。

2022-03-05 08:24 UTC, YamatoSecurity commented on README.md
> +Sigma rules need to first be converted to hayabusa rule format explained [here](https://github.com/Yamato-Security/hayabusa/blob/main/tools/sigmac/README.md). Hayabusa rules are designed solely for W
https://github.com/Yamato-Security/hayabusa-rules/blob/main/tools/sigmac/README.md が正しいリンクのでは？

2022-03-05 08:30 UTC, YamatoSecurity commented
rules submoduleについてよく分かってなくて申し訳ありません。hayabusa-rulesレポジトリを更新したら、毎回hayabusaレポジトリのrules submoduleリンクも更新する必要がありますか？
常にhayabusa-rulesレポジトリのmainブランチにリンクするようにできますか？

2022-03-05 08:41 UTC, hitenkoku commented on README.md
> +Sigma rules need to first be converted to hayabusa rule format explained [here](https://github.com/Yamato-Security/hayabusa/blob/main/tools/sigmac/README.md). Hayabusa rules are designed solely for W
コメントありがとうございます。 ご指摘のとおりです。
https://github.com/Yamato-Security/hayabusa/pull/441/commits/7d5c2c32f018d7fb6638feffb78f3fd904b9adba で修正をさせていただきましたのでご確認の程よろしくお願い致します。

2022-03-05 08:46 UTC, hitenkoku commented
はい、hayabusa-rulesレポジトリを更新した場合、hayabusaのリモートレポジトリに反映をさせるためにはrules submoduleリンクも更新する必要があります。常にhayabusa-rulesレポジトリのmainブランチにリンクするようにはできません(submoduleは特定のコミットに対しての紐付けを行うため)。他方法についても同様であるため、最新版の取得には-uオプションを利用して取得して貰う必要があります。

> rules submoduleについてよく分かってなくて申し訳ありません。hayabusa-rulesレポジトリを更新したら、毎回hayabusaレポジトリのrules submoduleリンクも更新する必要がありますか？ 常にhayabusa-rulesレポジトリのmainブランチにリンクするようにできますか？

2022-03-05 11:09 UTC, YamatoSecurity commented on README.md
> +Sigma rules need to first be converted to hayabusa rule format explained [here](https://github.com/Yamato-Security/hayabusa/blob/main/tools/sigmac/README.md). Hayabusa rules are designed solely for W
ありがとうございます！

2022-03-05 11:12 UTC, YamatoSecurity commented
なるほど、毎回の更新は手間ですね。。
何か自動化する方法あったら良いですね。Github action等でhayabusa-rulesが更新されたら、rules submoduleも更新するとか。
取り敢えず手動で更新しますか？

2022-03-05 11:12 UTC, YamatoSecurity approved these changes
okです。ありがとうございます！

2022-03-05 13:26 UTC, merged