[WIP] aliasキーがない場合も自動で走査する
Yamato-Security/hayabusa pull request #442
Opened 2022-03-07 07:26 UTC by kazuminn

fix #290.

2022-03-08 06:53 UTC, kazuminn commented
@hitenkoku テストが通ったのでWIPを外しました。レビューお願いします。

2022-03-08 09:40 UTC, hitenkoku commented
aliasキーから以下情報を削除した際に、検出件数が大きく下がっているため再度確認してください。

config 削除前

Total detections: 12263
Total critical detections: 109
Total high detections: 1574
Total medium detections: 532
Total low detections: 5239
Total informational detections: 4809
Total undefined detections: 0
Unique detections: 349
Unique critical detections: 29
Unique high detections: 155
Unique medium detections: 95
Unique low detections: 44
Unique informational detections: 26
Unique undefined detections: 0

Elapsed Time: 00:00:40.204


configからEventDataを削除した場合

Total detections: 3893
Total critical detections: 30
Total high detections: 110
Total medium detections: 3749
Total low detections: 4
Total informational detections: 0
Total undefined detections: 0
Unique detections: 15
Unique critical detections: 2
Unique high detections: 5
Unique medium detections: 7
Unique low detections: 1
Unique informational detections: 0
Unique undefined detections: 0

Elapsed Time: 00:00:26.791


config/eventkey_alias.txtから削除した項目

```text
AccessList,Event.EventData.AccessList
AccessMask,Event.EventData.AccessMask
Accesses,Event.EventData.Accesses
AccountName,Event.EventData.AccountName
Account_Name,Event.EventData.Account_Name
Action,Event.EventData.Action
AllowedToDelegateTo,Event.EventData.AllowedToDelegateTo
ApplicationPath,Event.EventData.ApplicationPath
AttributeLDAPDisplayName,Event.EventData.AttributeLDAPDisplayName
AttributeValue,Event.EventData.AttributeValue
AuditPolicyChanges,Event.EventData.AuditPolicyChanges
AuditSourceName,Event.EventData.AuditSourceName
AuthenticationPackageName,Event.EventData.AuthenticationPackageName
CallTrace,Event.EventData.CallTrace
CallerProcessName,Event.EventData.CallerProcessName
Caller_Process_Name,Event.EventData.Caller_Process_Name
CallingProcessName,Event.EventData.CallingProcessName
CategoryName,Event.EventData.Category Name
CertThumbprint,Event.EventData.CertThumbprint
ClassName,Event.EventData.ClassName
Client_Address,Event.EventData.Client_Address
CommandLine,Event.EventData.CommandLine
Company,Event.EventData.Company
ContextInfo,Event.EventData.ContextInfo
CurrentDirectory,Event.EventData.CurrentDirectory
Description,Event.EventData.Description
DestAddress,Event.EventData.DestAddress
DestPort,Event.EventData.DestPort
Destination,Event.EventData.Destination
DestinationAddress,Event.EventData.DestinationAddress
DestinationHostname,Event.EventData.DestinationHostname
DestinationIp,Event.EventData.DestinationIp
DestinationIsIpv6,Event.EventData.DestinationIsIpv6
DestinationPort,Event.EventData.DestinationPort
Details,Event.EventData.Details
DetectionSource,Event.EventData.DetectionSource
DetectionUser,Event.EventData.Detection User
Device,Event.EventData.Device
DeviceClassName,Event.EventData.DeviceClassName
DeviceDescription,Event.EventData.DeviceDescription
DeviceName,Event.EventData.DeviceName
DomainName,Event.EventData.SubjectDomainName
EngineVersion,Event.EventData.EngineVersion
ErrorCode,Event.EventData.ErrorCode
EventType,Event.EventData.EventType
FailureCode,Event.EventData.FailureCode
FilePath,Event.EventData.FilePath
FileVersion,Event.EventData.FileVersion
Filename,Event.EventData.Filename
GrantedAccess,Event.EventData.GrantedAccess
GroupName,Event.EventData.GroupName
GroupSid,Event.EventData.GroupSid
Hashes,Event.EventData.Hashes
HiveName,Event.EventData.HiveName
HostApplication,Event.EventData.HostApplication
HostName,Event.EventData.HostName
HostVersion,Event.EventData.HostVersion
Image,Event.EventData.Image
image,Event.EventData.Image
ImageLoaded,Event.EventData.ImageLoaded
ImagePath,Event.EventData.ImagePath
Imphash,Event.EventData.Hashes
Initiated,Event.EventData.Initiated
IntegrityLevel,Event.EventData.IntegrityLevel
IpAddress,Event.EventData.IpAddress
IpPort,Event.EventData.IpPort
JobTitle,Event.EventData.name
KeyLength,Event.EventData.KeyLength
LDAPDisplayName,Event.EventData.LDAPDisplayName
LayerRTID,Event.EventData.LayerRTID
LogonId,Event.EventData.LogonId
LogonProcessName,Event.EventData.LogonProcessName
LogonType,Event.EventData.LogonType
Logon_Account,Event.EventData.Logon_Account
MachineName,Event.EventData.MachineName
MemberName,Event.EventData.MemberName
MemberSid,Event.EventData.MemberSid
Message,Event.EventData
ModifyingApplication,Event.EventData.ModifyingApplication
NewName,Event.EventData.NewName
NewTemplateContent, Event.EventData.NewTemplateContent
NewUacValue,Event.EventData.NewUacValue
NewValue,Event.EventData.NewValue
New_Value,Event.EventData.New Value
NewProcessName,Event.EventData.NewProcessName
NewProcessId,Event.EventData.NewProcessId
ObjectClass,Event.EventData.ObjectClass
ObjectName,Event.EventData.ObjectName
ObjectServer,Event.EventData.ObjectServer
ObjectType,Event.EventData.ObjectType
ObjectValueName,Event.EventData.ObjectValueName
OldUacValue,Event.EventData.OldUacValue
Origin,Event.EventData.Origin
OriginalFileName,Event.EventData.OriginalFileName
OriginalFilename,Event.EventData.OriginalFileName
param1,Event.EventData.param1
param2,Event.EventData.param2
param3,Event.EventData.param3
param4,Event.EventData.param4
param5,Event.EventData.param5
ParentCommandLine,Event.EventData.ParentCommandLine
ParentImage,Event.EventData.ParentImage
ParentIntegrityLevel,Event.EventData.ParentIntegrityLevel
ParentProcessName,Event.EventData.ParentProcessName
ParentUser,Event.EventData.ParentUser
PasswordLastSet,Event.EventData.PasswordLastSet
Path,Event.EventData.Path
Payload,Event.EventData.Payload
PipeName,Event.EventData.PipeName
PreAuthType,Event.EventData.PreAuthType
PrivilegeList,Event.EventData.PrivilegeList
ProcessCommandLine,Event.EventData.ProcessCommandLine
ProcessId,Event.EventData.ProcessId
ProcessName,Event.EventData.ProcessName
Product,Event.EventData.Product
Properties,Event.EventData.Properties
QNAME,Event.EventData.QNAME
QueryName,Event.EventData.QueryName
QueryResults,Event.EventData.QueryResults
QueryStatus,Event.EventData.QueryStatus
RelativeTargetName,Event.EventData.RelativeTargetName
RuleName,Event.EventData.RuleName
SAMAccountName,Event.EventData.SamAccountName
ScriptBlockText,Event.EventData.ScriptBlockText
Service,Event.EventData.Service
ServiceFileName,Event.EventData.ServiceFileName
ServiceName,Event.EventData.ServiceName
ServicePrincipalNames,Event.EventData.ServicePrincipalNames
ServiceStartType,Event.EventData.ServiceStartType
ServiceType,Event.EventData.ServiceType
SeverityName,Event.EventData.Severity Name
ShareLocalPath,Event.EventData.ShareLocalPath
ShareName,Event.EventData.ShareName
SidHistory,Event.EventData.SidHistory
Signature,Event.EventData.Signature
SignatureStatus,Event.EventData.SignatureStatus
Signed,Event.EventData.Signed
SourceAddress,Event.EventData.SourceAddress
SourceImage,Event.EventData.SourceImage
SourceNetworkAddress,Event.EventData.SourceNetworkAddress
SourcePort,Event.EventData.SourcePort
Source_Name,Event.EventData.Source Name
Source_Network_Address,Event.EventData.Source_Network_Address
Source_WorkStation,Event.EventData.Source_WorkStation
StartAddress,Event.EventData.StartAddress
StartFunction,Event.EventData.StartFunction
StartModule,Event.EventData.StartModule
StartType,Event.EventData.StartType
State,Event.EventData.State
Status,Event.EventData.Status
SubStatus,Event.EventData.SubStatus
SubjectDomainName,Event.EventData.SubjectDomainName
SubjectLogonId,Event.EventData.SubjectLogonId
SubjectUserName,Event.EventData.SubjectUserName
SubjectUserSid,Event.EventData.SubjectUserSid
TargetDomainName,Event.EventData.TargetDomainName
TargetFilename,Event.EventData.TargetFilename
TargetInfo,Event.EventData.TargetInfo
TargetImage,Event.EventData.TargetImage
TargetLogonId,Event.EventData.TargetLogonId
TargetName,Event.EventData.TargetServerName
TargetObject,Event.EventData.TargetObject
TargetProcessAddress,Event.EventData.TargetProcessAddress
TargetServerName,Event.EventData.TargetServerName
TargetSid,Event.EventData.TargetSid
TargetUserName,Event.EventData.TargetUserName
TaskName,Event.EventData.TaskName
TemplateContent,Event.EventData.TemplateContent
ThreatName,Event.EventData [...]

2022-03-08 09:42 UTC, hitenkoku requested changes
https://github.com/Yamato-Security/hayabusa/pull/442#issuecomment-1061585948 で記載したとおり、EventData関連のaliasを削除した結果と、検出件数が一致しないのでご確認ください

2022-03-08 09:59 UTC, hitenkoku commented on src/detections/print.rs
> +            let array_str;
修正しているところはdetails内のeventkey_alias.txtでの記載場所(%xxx%)を実際のデータに置き換えるために用いられる処理です。出力のためにはこの修正は必要になりますが　、今回の仕様であるEvent.EventDataを自動で走査するところは別かと思います。

2022-03-08 12:35 UTC, hitenkoku commented
@YamatoSecurity  自動で走査させるようにして以下のように結果が改善しました。念の為、どのルールが新たに検知されたのかは確認しようと思います。念の為想定した動作かどうかご確認のほどよろしくお願い致します。

今回の修正ではeventkey_alias.txt内で対象のキーがない場合Event.EventDataの配下を確認するようになっています。
sha1のようにEventDataの中にあるけど属性値として取得するケースは対応していません。(一応ルール側でキー名でアンダースコアで指定をした場合は属性値を見に行くとは思いますが、いくつか確認したところそういうルールはないようです)

developブランチ側でImageを削除したときに検知数が上がっているのはおそらくImageの値が空白でないことなどの条件が入ったルールがあるためかと思われます。

## 結果

- developブランチ( https://github.com/Yamato-Security/hayabusa/commit/7d909a74383938e918c4ed283eb73e52282fc965 )

> Total detections: 12263
> Total critical detections: 109
> Total high detections: 1574
> Total medium detections: 532
> Total low detections: 5239
> Total informational detections: 4809
> Total undefined detections: 0
> Unique detections: 349
> Unique critical detections: 29
> Unique high detections: 155
> Unique medium detections: 95
> Unique low detections: 44
> Unique informational detections: 26
> Unique undefined detections: 0
> 
> Elapsed Time: 00:00:39.825

- developブランチでeventkey_alias.txtからImageのキーを削除

> Total detections: 13484
> Total critical detections: 127
> Total high detections: 2917
> Total medium detections: 547
> Total low detections: 5078
> Total informational detections: 4815
> Total undefined detections: 0
> Unique detections: 247
> Unique critical detections: 24
> Unique high detections: 105
> Unique medium detections: 68
> Unique low detections: 25
> Unique informational detections: 25
> Unique undefined detections: 0
> 
> Elapsed Time: 00:00:34.236
> 

- 修正版( https://github.com/Yamato-Security/hayabusa/pull/442/commits/34e7bfcb5fc639ed2a4ded1a2ca138bc15bd69fb )Configのキーを何も削除していない版

> Total detections: 12270
> Total critical detections: 109
> Total high detections: 1581
> Total medium detections: 532
> Total low detections: 5239
> Total informational detections: 4809
> Total undefined detections: 0
> Unique detections: 350
> Unique critical detections: 29
> Unique high detections: 156
> Unique medium detections: 95
> Unique low detections: 44
> Unique informational detections: 26
> Unique undefined detections: 0
> 
> Elapsed Time: 00:00:35.537

- 修正版( https://github.com/Yamato-Security/hayabusa/pull/442/commits/34e7bfcb5fc639ed2a4ded1a2ca138bc15bd69fb )eventkey_alias.txt からImageのキーを削除

> Total detections: 12270
> Total critical detections: 109
> Total high detections: 1581
> Total medium detections: 532
> Total low detections: 5239
> Total informational detections: 4809
> Total undefined detections: 0
> Unique detections: 350
> Unique critical detections: 29
> Unique high detections: 156
> Unique medium detections: 95
> Unique low detections: 44
> Unique informational detections: 26
> Unique undefined detections: 0
> 
> Elapsed Time: 00:00:37.581

2022-03-08 12:36 UTC, hitenkoku commented on src/detections/print.rs
> +            let array_str;
https://github.com/Yamato-Security/hayabusa/pull/442/commits/c33399b6815d0f3059b0be97ba8cd125e7efa82e で走査部分をこちらで作成しましたのでresolveにします

2022-03-08 12:46 UTC, kazuminn commented
おお！さすが！ありがとうございます！

2022-03-09 03:41 UTC, YamatoSecurity commented
@hitenkoku ありがとうございます！
時間がある時に確認します。

2022-03-09 21:54 UTC, YamatoSecurity commented
<img width="1152" alt="Screen Shot 2022-03-10 at 6 52 49" src="https://user-images.githubusercontent.com/71482215/157542741-95beea62-3499-4ae5-ba0f-92f7f17ba848.png">

動作確認してみましたが、こんなエラーが出ています。

2022-03-10 02:03 UTC, hitenkoku commented
developブランチの最新版を反映できていないせいかと思いますので対応します

2022-03-10 02:06 UTC, hitenkoku commented
@YamatoSecurity 対応が完了しました。お手数ですが、再度ご確認のほど、よろしくお願いいたします。

https://github.com/Yamato-Security/hayabusa/pull/442/commits/4c82ff4b70a01c9e6f77d4770d2bc3b1e0fb2e79 で最新のdevelopブランチの変更を反映しました。

2022-03-10 10:01 UTC, YamatoSecurity commented
<img width="1158" alt="Screen Shot 2022-03-10 at 19 00 17" src="https://user-images.githubusercontent.com/71482215/157638010-a366a521-7bdf-4f61-864a-acbce0560b5a.png">

試してみましたが、panicで死にます・・

2022-03-10 11:39 UTC, hitenkoku commented
@YamatoSecurity  確認したところ、filter.rsで参照しているファイルが存在しないというエラーなので hayabusa.exe -uを実行してもらっても良いでしょうか？

2022-03-10 12:22 UTC, hitenkoku commented
@YamatoSecurity  ソースコードを確認したらfilter.rsにファイルが無いときの処理に問題があったので修正をつけておきました(ファイルが無かったらwarnを出してそのまま処理を続行させるように変更を https://github.com/Yamato-Security/hayabusa/pull/442/commits/5cc06577a8bacb98a6a1d02ca8d4f60232ff95dd で行いました。ご確認のほど、よろしくお願い致します。

2022-03-10 21:56 UTC, YamatoSecurity commented
対応ありがとうございます！今回は実行できました。

しかし、eventkey_alias.txtのEvent.EventDataの行を削除したら検知率が大分下がりました：
develop branch:
```
Analyzing event files: 509
Hayabusa rules: 67
Sigma rules: 1358
Ignored rules: 59
Rule parsing errors: 0
Total enabled detection rules: 1425

Total detections: 16398
Total critical detections: 110
Total high detections: 5635
Total medium detections: 593
Total low detections: 5251
Total informational detections: 4809
Total undefined detections: 0
Unique detections: 360
Unique critical detections: 30
Unique high detections: 161
Unique medium detections: 96
Unique low detections: 47
Unique informational detections: 26
Unique undefined detections: 0

Elapsed Time: 00:00:10.986
```

feature/no_alias_keyブランチ (unique detectionが360から361に上がりました）:
```
Analyzing event files: 509
Hayabusa rules: 67
Sigma rules: 1358
Ignored rules: 59
Rule parsing errors: 0
Total enabled detection rules: 1425

Total detections: 16405
Total critical detections: 110
Total high detections: 5642
Total medium detections: 593
Total low detections: 5251
Total informational detections: 4809
Total undefined detections: 0
Unique detections: 361
Unique critical detections: 30
Unique high detections: 162
Unique medium detections: 96
Unique low detections: 47
Unique informational detections: 26
Unique undefined detections: 0

Elapsed Time: 00:00:10.748
```

feature/no_alias_keyブランチでEvent.EventDataの行を削除した後 (unique detectionが360から309に下がりました）:
```
Analyzing event files: 509
Hayabusa rules: 67
Sigma rules: 1358
Ignored rules: 59
Rule parsing errors: 0
Total enabled detection rules: 1425

Total detections: 5772
Total critical detections: 110
Total high detections: 4882
Total medium detections: 545
Total low detections: 229
Total informational detections: 6
Total undefined detections: 0
Unique detections: 309
Unique critical detections: 30
Unique high detections: 150
Unique medium detections: 85
Unique low detections: 41
Unique informational detections: 3
Unique undefined detections: 0

Elapsed Time: 00:00:10.491
```

使ったeventkey_alias.txtを添付しました
[eventkey_alias.txt](https://github.com/Yamato-Security/hayabusa/files/8227384/eventkey_alias.txt)
。

2022-03-11 00:18 UTC, hitenkoku commented
@YamatoSecurity  ご確認いただき誠にありがとうございます。
ご提供いただいたeventkey_alias.txtを見たところ、今回の修正では対応できないおのがあります。

- 「_」でつなげるタイプの属性値を見に行くタイプ
  - こちらはできないわけではありませんが対応しようとすると、キーの一覧をすべて読みに行く必要が出てくる(走査した取得したキーを全部1回走査して、合致したら今回の検索用のために登録するという方法もありはしますのでできなくはないですが、パフォーマンスの面であまりよくない状態を引き起こす可能性はありそうです)。ただこれも「_」が入っているものにすべて対応できるかと言われたらそうではありません。対応できるのは以下のようなケースのみです。[test]は任意の文字です。こちらは対応しておきますか？その代わり各レコードごとに対象の要素をチェックし始めるのでパフォーマンスへの影響は大きいと思われます。
  　XXX, Event.EventData.[test]_XXX
  
- key名がそもそも検索する場所の末端の要素の名前と一致しないタイプ(Case Sensitiveです。ex. XXX,System.Event.EventData.YYY)
  - これはそもそも正解がわからないので実装ができないです

現在、対応ができるだろうもののみを省いた場合のeventkey_alias.txtを共有します。これであれば検知数等が下がることもないと思います。利用したルールは https://github.com/Yamato-Security/hayabusa-rules/commit/a8b83d107e643de91399fd1039697a1ea0ef8732 です。

[eventkey_alias.txt](https://github.com/Yamato-Security/hayabusa/files/8227948/eventkey_alias.txt)


- developブランチ
```
Analyzing event files: 509
Hayabusa rules: 67
Sigma rules: 1348
Ignored rules: 83
Rule parsing errors: 0
Total enabled detection rules: 1415

Total detections: 12263
Total critical detections: 109
Total high detections: 1574
Total medium detections: 532
Total low detections: 5239
Total informational detections: 4809
Total undefined detections: 0
Unique detections: 349
Unique critical detections: 29
Unique high detections: 155
Unique medium detections: 95
Unique low detections: 44
Unique informational detections: 26
Unique undefined detections: 0
````

- feature/no_alias_key(configの削除無し版)

```
Analyzing event files: 509
Hayabusa rules: 67
Sigma rules: 1348
Ignored rules: 83
Rule parsing errors: 0
Total enabled detection rules: 1415

Total detections: 12270
Total critical detections: 109
Total high detections: 1581
Total medium detections: 532
Total low detections: 5239
Total informational detections: 4809
Total undefined detections: 0
Unique detections: 350
Unique critical detections: 29
Unique high detections: 156
Unique medium detections: 95
Unique low detections: 44
Unique informational detections: 26
Unique undefined detections: 0
```

- feature/no_alias_key(configの削除あり版)

```
Analyzing event files: 509
Sigma rules: 1348
Hayabusa rules: 67
Ignored rules: 83
Rule parsing errors: 0
Total enabled detection rules: 1415

Total detections: 12270
Total critical detections: 109
Total high detections: 1581
Total medium detections: 532
Total low detections: 5239
Total informational detections: 4809
Total undefined detections: 0
Unique detections: 350
Unique critical detections: 29
Unique high detections: 156
Unique medium detections: 95
Unique low detections: 44
Unique informational detections: 26
Unique undefined detections: 0

Elapsed Time: 00:00:27.859
```

2022-03-11 03:12 UTC, YamatoSecurity commented
なるほど、ありがとうございます！
では、問題ありません。しばらくv1.1.0と互換性があるように今のeventkey_alias.txtを使いましょうか？
(1.3等のタイミングで作って頂いた短いeventkey_alias.txtと差し替えても良いと思います。)

2022-03-11 03:12 UTC, YamatoSecurity approved these changes
これでOKです。マージしましょう。

2022-03-11 04:24 UTC, hitenkoku approved these changes
対応済みで、合意も取れたのでApproveします

2022-03-11 04:24 UTC, merged