Feature/level tuning#390
Yamato-Security/hayabusa pull request #459
Opened 2022-03-23 17:06 UTC by itiB

closes #390

2022-03-23 23:51 UTC, itiB commented
yamlリーダーの変更。
https://github.com/chyh1990/yaml-rust
↓
https://github.com/dtolnay/serde-yaml

- 理由
  - ファイルの上書きがyaml-rustでできない
  - 更新がだいぶ止まっている

2022-03-30 06:35 UTC, hitenkoku commented
yamlリーダの変更は #461 が対応するissue

2022-04-03 16:45 UTC, itiB commented
うーん、上書きまえのルールの文字数が上書き後の文字数より多いと残ってしまう...

2022-04-06 04:18 UTC, YamatoSecurity commented
<img width="506" alt="Screen Shot 2022-04-06 at 13 18 00" src="https://user-images.githubusercontent.com/71482215/161894849-a97a5d01-e2f8-4e4b-9ab1-bd8b2cfaf33a.png">

あれ、hayabusaだけを実行したら、ヘルプ画面が表示されません。

2022-04-06 04:24 UTC, YamatoSecurity commented
`-h`を指定したら、`--level-tuning <LEVEL_TUNING_FILE>    Fix rule file's level [default: ./config/level_tuning.txt]`は出て来ますが、USAGEには出て来ないので、追加をお願いできますか？

2022-04-06 04:32 UTC, YamatoSecurity commented
<img width="774" alt="Screen Shot 2022-04-06 at 13 29 09" src="https://user-images.githubusercontent.com/71482215/161895968-df4a9a90-bab3-4211-990c-067714f87df5.png">

メッセージは正しく表示されていますが、criticalルールをlowに変えようとしたら、なぜかinformationalに変わりました。

2022-04-06 04:35 UTC, YamatoSecurity commented
`sample leveltunig line` -> `sample level tuning line`

2022-04-06 09:49 UTC, hitenkoku commented on src/options/level_tuning.rs
> +    // }
私の方で対応してみます。

2022-04-06 12:39 UTC, hitenkoku commented on src/options/level_tuning.rs
> +    // }
@itiB お手数ですが、level_tuning_error2.txtをaddしてもらってもよろしいでしょうか……？

2022-04-06 13:38 UTC, hitenkoku commented
以下の2件ですが、こちらでテストを作ってみたところ、テストが通っていないみたいなので、確認がてら修正しておきます。


> 少し英語の修正： `sample leveltunig line` -> `sample level tuning line` `next_level`より`new_level`の方が分かりやすいかも。`next`だと次のレベルしか指定できないように見えます。



> <img alt="Screen Shot 2022-04-06 at 13 29 09" width="774" src="https://user-images.githubusercontent.com/71482215/161895968-df4a9a90-bab3-4211-990c-067714f87df5.png">
> 
> メッセージは正しく表示されていますが、criticalルールをlowに変えようとしたら、なぜかinformationalに変わりました。

2022-04-06 15:16 UTC, hitenkoku commented on src/options/level_tuning.rs
> +    // }
itibさんのhelp内容はconfigのargsでのmatch内容をtestの時に変更させたいという話ということを理解しました。
色々いじっては見たのですが、素直にrunの引数を1つ増やしてそちらにrulesの値を外部から受け入れるように変更して対応を行いました。args側を上書きすることも考えましたが、見やすさを考慮するとそちらの方がいいかと思いそちらで書いてみました。

ご確認いただき、問題なければresolveをお願いいたします。

2022-04-06 16:09 UTC, itiB commented on src/options/level_tuning.rs
> +    // }
a35e8ad5cbec077fb295e6caccc89ed395cba8da 確認しました。
やることが外に移ったのみ & テストができるようになった点でOKです！！ご助力ありがとうございます。

2022-04-06 16:13 UTC, itiB commented on src/options/level_tuning.rs
> +    // }
@hitenkoku 
https://github.com/Yamato-Security/hayabusa/pull/459/files#diff-fda90af78d831a657403485dcc08347f2d9135ab01a3c5809589aa9413d49159R168-R176
なんですがその下の assert と内容が同じかと思ったのですがどこか違うところありますか？
まったく同じであればどちらか消してしまいたいと思いました

2022-04-06 16:59 UTC, itiB commented on src/main.rs
> +        if configs::CONFIG
/hayabusa.exe でオプションが表示されないこと調査しようと思いましたが自分は再現できませんでした。
ほかになる方いますか？

![image](https://user-images.githubusercontent.com/24380190/162027701-b778f096-4378-48d7-8b76-ce2ac74bb2f5.png)

また --level-tuning コマンドがなにか後につけろーって怒られるようになりました

![image](https://user-images.githubusercontent.com/24380190/162027335-ab7c77da-1b21-441b-a5a2-a8a92d5bd4b2.png).

2022-04-06 17:08 UTC, hitenkoku commented on src/options/level_tuning.rs
> +        let path = "test_files/rules/level_tuning.txt";
ここのpathはyamlのファイルを作らないとParseYamlの読み込み対象にならないと思いますので `level_tuning_sample.yml`に戻してもいいですか？

2022-04-06 17:09 UTC, itiB commented on src/options/level_tuning.rs
> +        let path = "test_files/rules/level_tuning.txt";
そういえばそうでした…！！戻して大丈夫です

2022-04-06 17:10 UTC, hitenkoku commented on src/main.rs
> +        if configs::CONFIG
あ、それ多分私の修正のせいです。 e715935 で対応できたかと思っていたのですが……おそらく 説明文内に<>で記載が入っていたため必須パラメータ扱いにあってしまったのだとおもっていました

2022-04-06 17:13 UTC, hitenkoku commented on src/main.rs
> +        if configs::CONFIG
多分対応する修正箇所は https://github.com/Yamato-Security/hayabusa/pull/459/files/f3a679d845936742a7867c0d6b50aaab121ed3d0#diff-8c7ff28a9096bccff872f0718affb12d1c694d7f8908fcb8fcd38b41b585a2c5R83 だと思っています

2022-04-06 17:20 UTC, hitenkoku commented on src/main.rs
> +        if configs::CONFIG
この件、私がconfigをなおそうとしてusageの中に投入対応をしていたのが原因でした。失礼いたしました。いったん対象の個所を戻そうと思います

2022-04-06 17:27 UTC, hitenkoku commented on src/main.rs
> +        if configs::CONFIG
https://github.com/Yamato-Security/hayabusa/pull/459/commits/0bac82699f6bf7516dc7fcb4d465a78b600ea892 で元への戻しが完了しました。ご迷惑をおかけしてしまいもうしわけございません。 これってusageの中には入らずにoptionとしてのみ入る形になるんですね……

2022-04-06 17:32 UTC, hitenkoku commented on src/options/level_tuning.rs
> +    // }
単純にlevelだけしか見ていない為、ファイルとして中身を確認するのかなと思っていました。ただ、複数ファイルを読み込ますのであれば他の番号も合致しているのか……？と思って L168とかの処理を追加していました。

2022-04-06 17:44 UTC, hitenkoku commented
残りの残課題は以下の2つだと認識しています。
- https://github.com/Yamato-Security/hayabusa/pull/459#issuecomment-1089795906

> <img alt="Screen Shot 2022-04-06 at 13 18 00" width="506" src="https://user-images.githubusercontent.com/71482215/161894849-a97a5d01-e2f8-4e4b-9ab1-bd8b2cfaf33a.png">
> 
> あれ、hayabusaだけを実行したら、ヘルプ画面が表示されません。

- https://github.com/Yamato-Security/hayabusa/pull/459#issuecomment-1089800993

> `-h`を指定したら、`--level-tuning <LEVEL_TUNING_FILE> Fix rule file's level [default: ./config/level_tuning.txt]`は出て来ますが、USAGEには出て来ないので、追加をお願いできますか？

2022-04-09 15:19 UTC, itiB commented
@hitenkoku 
>こちらのほうは、usageの中に記載をしてしまうと --level-tuningオプションを指定したら [LEVEL_TUNING_FILE]の値は必ず投入する必要が出てくるためitibさんからコメントいただいた以下の警告が出るようになります。

この修正が入った[e715935](https://github.com/Yamato-Security/hayabusa/pull/459/commits/e715935bb6e11c2451aedcfa4c15c7ce30c4ad6c)について聞きたいのですがここは必須オプションにしなくてもいいかなと思っていました。
`--level-tuning` でconfigファイルがデフォルト位置になければエラーは出るしその気になれば自由にconfigファイルを指定できる裏オプションくらいの気持ちでファイルのパス入力を受け付けていました。
たくさんのオプションと入力があるとわかりにくいなぁと思うツールが多かったので自分はこう実装しましたがいかがでしょうか。

## 内容

@YamatoSecurity の意見もうかがいたいです✋
`--level-tuning=<level-tuning.txtへのパス>` を必須にするか。

`--level-tuning` だけなら デフォルトの`config/level-tuning.txt` を読んでレベルチューニングが行われ、その気になれば `--level-tuning=<level-tuning.txtへのパス>` で好きなlevel-tuning.txtを読めるという形式にしていた。
現在`--level-tuning=<level-tuningtxt>`の形式での入力を必須にしていまるがどちらのほうがいいか

2022-04-10 07:19 UTC, hitenkoku reviewed
@itiB  確認しました。今回の修正でusageに --level-tuningを投入することができるようのになったはずなのでusageに投入できるかどうか少し確認してみます。
それ以外で気になるところにコメントを入れてみたのでご確認ください。

2022-04-10 07:19 UTC, hitenkoku commented on src/main.rs
> +        if std::env::args().len() == 1 {
これだと、登録していないオプションが入ったときにここのif文を通過してしまうと思います。

対象の処理は https://github.com/Yamato-Security/hayabusa/pull/459/commits/8061733fd90e1d263b94bf1b76aaf8478721491a#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcL153 で記載されており、こちらだと、登録されたオプション以外はカウントしないようになっているのですが、この修正の意図を教えてもらってもよろしいでしょうか。

2022-04-10 07:19 UTC, hitenkoku commented on src/main.rs
> +                    "Need rule_levels.txt file to use --level-tuning option",
できればlevel_tuning_config_pathの値をここで出力したほうが良いかと思います。

デフォルト値はhelpに書いていますが、それを読んでない人向けに 
`--level-tuning: (level_tuning_config_pathの値)` とかをアラートで出しておければ良いかなと思っています。

2022-04-10 07:21 UTC, hitenkoku commented on src/main.rs
> +        if std::env::args().len() == 1 {
こちらの指摘ですが、私の誤りでしたので対処不要です。失礼いたしました。

2022-04-10 07:45 UTC, hitenkoku commented
@YamatoSecurity  @itiB  https://github.com/Yamato-Security/hayabusa/pull/459/commits/e6a74090a3ddc85399906aeaca8a4fd5ba98832a で以下の問題に対応完了しました。usageを設定した後にargsで追加することで　--level-tuning の値がなくてもデフォルトの値を参照しに行くようにできました。ご確認のほどよろしくお願いいたします。

> 
> > `-h`を指定したら、`--level-tuning <LEVEL_TUNING_FILE> Fix rule file's level [default: ./config/level_tuning.txt]`は出て来ますが、USAGEには出て来ないので、追加をお願いできますか？
> 
> こちらのほうは、usageの中に記載をしてしまうと --level-tuningオプションを指定したら` [LEVEL_TUNING_FILE]`の値は必ず投入する必要が出てくるためitibさんからコメントいただいた以下の警告が出るようになります。
> 
> > また --level-tuning コマンドがなにか後につけろーって怒られるようになりました
> > ![image](https://user-images.githubusercontent.com/24380190/162027335-ab7c77da-1b21-441b-a5a2-a8a92d5bd4b2.png).

Evidence

> PS >.\hayabusa.exe        
> USAGE:
>     -d --directory=[DIRECTORY] 'Directory of multiple .evtx files.'
>     -f --filepath=[FILEPATH] 'File path to one .evtx file.'
>     -r --rules=[RULEFILE/RULEDIRECTORY] 'Rule file or directory. (Default: ./rules)'
>     -c --color 'Output with color. (Terminal needs to support True Color.)'
>     -C --config=[RULECONFIGDIRECTORY] 'Rule config folder. (Default: ./rules/config)'
>     -o --output=[CSV_TIMELINE] 'Save the timeline in CSV format. (Example: results.csv)'
>     -v --verbose 'Output verbose information.'
>     -D --enable-deprecated-rules 'Enable rules marked as deprecated.'
>     -n --enable-noisy-rules 'Enable rules marked as noisy.'
>     -u --update-rules 'Update to the latest rules in the hayabusa-rules github repository.'
>     -m --min-level=[LEVEL] 'Minimum level for rules. (Default: informational)'
>     -l --live-analysis 'Analyze the local C:\Windows\System32\winevt\Logs folder (Windows Only. Administrator privileges required.)'
>     --level-tuning=[LEVEL_TUNING_FILE] 'Fix rule file's level(Default: ./config/level_tuning.txt)'
>     --start-timeline=[STARTTIMELINE] 'Start time of the event logs to load. (Example: '2018/11/28 12:00:00 +09:00')'
>     --end-timeline=[ENDTIMELINE] 'End time of the event logs to load. (Example: '2018/11/28 12:00:00 +09:00')'
>     --rfc-2822 'Output date and time in RFC 2822 format. (Example: Mon, 07 Aug 2006 12:34:56 -0600)'
>     --rfc-3339 'Output date and time in RFC 3339 format. (Example: 2006-08-07T12:34:56.485214 -06:00)'
>     -U --utc 'Output time in UTC format. (Default: local time)'
>     -t --thread-number=[NUMBER] 'Thread number. (Default: Optimal number for performance.)'
>     -s --statistics 'Prints statistics of event IDs.'
>     -q --quiet 'Quiet mode. Do not display the launch banner.'
>     -Q --quiet-errors 'Quiet errors mode. Do not save error logs.'
>     --contributors 'Prints the list of contributors.'
> 
> PS >cat .\config\level_tuning.txt
> id,new_level
> 00000000-0000-0000-0000-000000000000,informational # sample level tuning line
> 671bb7e3-a020-4824-a00e-2ee5b55f385e,high
> PS >.\hayabusa.exe --level-tuning
> 
> ██╗  ██╗ █████╗ ██╗   ██╗ █████╗ ██████╗ ██╗   ██╗███████╗ █████╗
> ██║  ██║██╔══██╗╚██╗ ██╔╝██╔══██╗██╔══██╗██║   ██║██╔════╝██╔══██╗
> ███████║███████║ ╚████╔╝ ███████║██████╔╝██║   ██║███████╗███████║
> ██╔══██║██╔══██║  ╚██╔╝  ██╔══██║██╔══██╗██║   ██║╚════██║██╔══██║
> ██║  ██║██║  ██║   ██║   ██║  ██║██████╔╝╚██████╔╝███████║██║  ██║
> ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝
>    by Yamato Security 
> 
> path: rules\sigma\image_load\sysmon_wmi_module_load.yml
> level: informational -> high
> PS >.\hayabusa.exe --help        
> hayabusa 1.1.0
> Yamato Security (https://github.com/Yamato-Security/hayabusa)
> Hayabusa: Aiming to be the world's greatest Windows event log analysis tool!
> 
> USAGE:
>     -d --directory=[DIRECTORY] 'Directory of multiple .evtx files.'
>     -f --filepath=[FILEPATH] 'File path to one .evtx file.'
>     -r --rules=[RULEFILE/RULEDIRECTORY] 'Rule file or directory. (Default: ./rules)'
>     -c --color 'Output with color. (Terminal needs to support True Color.)'
>     -C --config=[RULECONFIGDIRECTORY] 'Rule config folder. (Default: ./rules/config)'
>     -o --output=[CSV_TIMELINE] 'Save the timeline in CSV format. (Example: results.csv)'
>     -v --verbose 'Output verbose information.'
>     -D --enable-deprecated-rules 'Enable rules marked as deprecated.'
>     -n --enable-noisy-rules 'Enable rules marked as noisy.'
>     -u --update-rules 'Update to the latest rules in the hayabusa-rules github repository.'
>     -m --min-level=[LEVEL] 'Minimum level for rules. (Default: informational)'
>     -l --live-analysis 'Analyze the local C:\Windows\System32\winevt\Logs folder (Windows Only. Administrator privileges required.)'
>     --level-tuning=[LEVEL_TUNING_FILE] 'Fix rule file's level(Default: ./config/level_tuning.txt)'
>     --start-timeline=[STARTTIMELINE] 'Start time of the event logs to load. (Example: '2018/11/28 12:00:00 +09:00')'
>     --end-timeline=[ENDTIMELINE] 'End time of the event logs to load. (Example: '2018/11/28 12:00:00 +09:00')'
>     --rfc-2822 'Output date and time in RFC 2822 format. (Example: Mon, 07 Aug 2006 12:34:56 -0600)'
>     --rfc-3339 'Output date and time in RFC 3339 format. (Example: 2006-08-07T12:34:56.485214 -06:00)'
>     -U --utc 'Output time in UTC format. (Default: local time)'
>     -t --thread-number=[NUMBER] 'Thread number. (Default: Optimal number for performance.)'
>     -s --statistics 'Prints statistics of event IDs.'
>     -v, --verbose                    Output verbose information.
> 
> OPTIONS:
>     -C, --config <RULECONFIGDIRECTORY>        Rule config folder. (Default: ./rules/config)
>     -d, --directory <DIRECTORY>               Directory of multiple .evtx files.
>         --end-timeline <ENDTIMELINE>          End time of the event logs to load. (Example: '2018/11/28 12:00:00
>                                               +09:00')
>     -f, --filepath <FILEPATH>                 File path to one .evtx file.
>         --level-tuning <LEVEL_TUNING_FILE>    Fix rule file's level [default: ./config/level_tuning.txt]
>     -m, --min-level <LEVEL>                   Minimum level for rules. (Default: informational)
>     -o, --output <CSV_TIMELINE>               Save the timeline in CSV format. (Example: results.csv)
>     -r, --rules <RULEFILE/RULEDIRECTORY>      Rule file or directory. (Default: ./rules)
>         --start-timeline <STARTTIMELINE>      Start time of the event logs to load. (Example: '2018/11/28 12:00:00
>                                               +09:00')
>     -t, --thread-number <NUMBER>              Thread number. (Default: Optimal number for performance.)

2022-04-10 07:55 UTC, hitenkoku commented
testの方でエラーが出てしまうようなので、ちょっと控えたほうが良さそうですかね……revertしておきます

2022-04-11 00:56 UTC, YamatoSecurity requested changes
usageに投入するのは難しいですね。なるほど、でしたらUSAGE記載なしで大丈夫です。
こちらでも機能を確認できましたが、./target/releases/hayabusaだけを実行したら、ロゴ(バナー)がなぜか表示されないので、(USAGEのみなので）、それだけ確認して頂けますか？

2022-04-11 09:25 UTC, YamatoSecurity commented
v1.2の最後のPRなので、ついでにhayabusa versionを1.2.0に更新して、cargoパッケージも更新しておきました。

2022-04-11 15:20 UTC, itiB commented on src/options/level_tuning.rs
> +    // }
@hitenkoku ごめんなさい！なんか勝手にResolveになってしまっていました。
177がなぜか失敗して168が通るのはなぜか～まったく同じことをしているのに...と思っていたところが解決してよかったです。
追加していただいたテストと177のテスト内容はやはり同一のものをテストしていると思うので削除します！✋
a1812e013b549ff1c4f2027230e3f7e0231c6e50

2022-04-11 15:27 UTC, itiB commented
@YamatoSecurity 
> usageに投入するのは難しいですね。なるほど、でしたらUSAGE記載なしで大丈夫です。
こちらでも機能を確認できましたが、./target/releases/hayabusaだけを実行したら、ロゴ(バナー)がなぜか表示されないので、(USAGEのみなので）、それだけ確認して頂けますか？

対応しました。 9fa60dd26dd0729113d0c0539d5e99469b637c12
こちら入れましたが `--help` オプション等の時も同様に出ません。
Helpを修正するにはclap側(Usageとかいろいろ作っているライブラリ)をすこし上書きしたりして～が必要になるかと思われます。

2022-04-11 23:42 UTC, YamatoSecurity approved these changes
ありがとうございます！

2022-04-11 23:54 UTC, merged