Remove unnecessary code from timeline_event_info and rename files for…
Yamato-Security/hayabusa pull request #470
Opened 2022-03-28 15:05 UTC by garigariganzy

#462 で以下、対応いたしました。ご確認をお願いします。
・ファイル名(statistics_event_info.txt)を変更しました。
・detect_flgとcommentのデータ削除と参照箇所の処理を削除。

2022-03-29 04:07 UTC, hitenkoku requested changes
確認しました。コメントアウトはできれば削除してほしいです。
削除ではなくコメントアウトにしている理由がありましたらコメントいただけますと幸いです。

2022-03-29 04:07 UTC, hitenkoku commented on src/detections/configs.rs
> +    //    pub detectflg: String,
不要であれば削除してしまって良いと思います。コメントアウトをしている理由は何でしょうか？

2022-03-29 04:07 UTC, hitenkoku commented on src/detections/configs.rs
> +        //        if line.len() != 4 {
```suggestion
```

不要であれば混乱を回避するためにコメントアウトより削除をしてしまったほうが良いと思いますが、このコメントアウトの理由は何でしょうか？

2022-03-29 12:05 UTC, garigariganzy commented on src/detections/configs.rs
> +    //    pub detectflg: String,
了解しました。削除するようにいたします。

2022-03-29 12:05 UTC, garigariganzy commented on src/detections/configs.rs
> +        //        if line.len() != 4 {
了解しました。削除するようにいたします。

2022-03-29 12:36 UTC, garigariganzy commented on src/detections/configs.rs
> +    //    pub detectflg: String,
コメントアウト箇所を削除しました。ご確認をお願いいたします。

2022-03-29 12:36 UTC, garigariganzy commented on src/detections/configs.rs
> +        //        if line.len() != 4 {
コメントアウト箇所を削除しました。ご確認をお願いいたします。

2022-03-30 00:44 UTC, hitenkoku approved these changes
ご対応ありがとうございます。問題ないと思います

2022-03-30 00:45 UTC, hitenkoku commented on src/detections/configs.rs
> +        //        if line.len() != 4 {
確認しました。ありがとうございます

2022-03-30 00:46 UTC, hitenkoku commented on src/detections/configs.rs
> +    //    pub detectflg: String,
確認しました。ご対応ありがとうございます

2022-03-30 00:46 UTC, merged