fixed event timeline frequency font color changed when use f option #542
Yamato-Security/hayabusa pull request #544
Opened 2022-05-24 12:32 UTC by hitenkoku

Closes #541 , Closes #542 , Closes #543

## What Changed

- fixed  same color output Event Frequency Timeline color when prev detection output is colored. #542 
- fixed duplicate count detection to same record in data reduction. #543 
- fixed error when detection record is few #541 

## Evidence

- when -d option is used

```powershell
./hayabusa.exe -d hayabusa-sample-evtx -m HIGH

```

![image](https://user-images.githubusercontent.com/2350416/170035349-c1471166-d98a-42d8-ab5a-6479d21a0f36.png)

- when -f option is used

```powershell
> PS >.\hayabusa.exe -f ./hayabusa-sample-evtx/DeepBlueCLI/metasploit-psexec-powershell-target-system.evtx
```
![image](https://user-images.githubusercontent.com/2350416/170034693-71e94ae6-a8ce-449c-a259-80ec5e62248d.png)

2022-05-24 22:46 UTC, YamatoSecurity requested changes
色出力は直りましたが、Data Reductionの値がまだおかしくなっています。
`./target/release/hayabusa -f ../hayabusa-sample-evtx/DeepBlueCLI/metasploit-psexec-powershell-target-system.evtx --output a.csv`　で検証しています。

2022-05-25 00:05 UTC, hitenkoku commented
@YamatoSecurity  失礼いたしました。リモートレポジトリへのpush漏れでした。pushが完了しましたのでご家訓のほどよろしくお願いいたします。

2022-05-25 01:58 UTC, YamatoSecurity commented
`./target/release/hayabusa -f ../hayabusa-sample-evtx/DeepBlueCLI/metasploit-psexec-powershell-target-system.evtx`
で検証していますが、以下のエラーが出ています：

```
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 3', /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/krapslog-0.4.0/src/lib.rs:82:24
stack backtrace:
   0:        0x106dd78f6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4cae82d438451481
   1:        0x106c76b8b - core::fmt::write::hb68c3045179d0cad
   2:        0x106dd6300 - std::io::Write::write_fmt::haf84c797e63d79f0
   3:        0x106ddb2e2 - std::panicking::default_hook::{{closure}}::he18137441e51da1f
   4:        0x106ddc30c - std::panicking::rust_panic_with_hook::h429a7ddefa5f0258
   5:        0x106ddbd74 - std::panicking::begin_panic_handler::{{closure}}::h9b033a6b15b84a74
   6:        0x106ddbce9 - std::sys_common::backtrace::__rust_end_short_backtrace::hcdd3bec8e0e38aa6
   7:        0x106ddbca5 - _rust_begin_unwind
   8:        0x106fe8ac3 - core::panicking::panic_fmt::hf7d6e5207e013f69
   9:        0x106fe8a86 - core::panicking::panic_bounds_check::h4dad0bcdf31bc1e8
  10:        0x106cce862 - hayabusa::afterfact::emit_csv::hd5bbb1bf5a0a95e0
  11:        0x106c110c6 - hayabusa::App::analysis_files::h4e0876ecbb399a55
  12:        0x106bfade4 - hayabusa::App::exec::h5684ddb963c4acea
  13:        0x106bf4cbb - hayabusa::main::h885300da9a6f19e7
  14:        0x106d2d326 - std::sys_common::backtrace::__rust_begin_short_backtrace::he0780667e9ddf0b7
  15:        0x106c1906d - _main
```

2022-05-25 07:47 UTC, hitenkoku commented
以下の問題は #541 と同じエラーですのでそちらで対応をさせてください。

https://github.com/Yamato-Security/hayabusa/pull/544#issuecomment-1136628904

2022-05-25 09:29 UTC, hitenkoku commented
すみません。確認します。

2022-05-25 11:35 UTC, hitenkoku commented
原因がわかりました。私が検証のためにライブラリ側をいじっていたことが原因でした。
修正します。

1点確認が必要なところですが、Timelineはdetectionされたもの全てではなく、全ルールを通じて検知されたイベントの数(なので別のルールで同じイベントに対して検出してもまとめて1つと数える)という認識でよろしいでしょうか。

2022-05-25 12:48 UTC, hitenkoku commented
timelineのエラー回避のためには5レコード以上が必要であることがわかったので、検知したレコードの数が5レコードより小さければ表示をしないように修正をしました。

2022-05-25 22:05 UTC, YamatoSecurity commented
> 1点確認が必要なところですが、Timelineはdetectionされたもの全てではなく、全ルールを通じて検知されたイベントの数(なので別のルールで同じイベントに対して検出してもまとめて1つと数える)という認識でよろしいでしょうか。

はい、検知数ではなく、イベント数を可視化した方が良いと思います。

2022-05-25 22:07 UTC, YamatoSecurity approved these changes
うまくいっています。良いと思います。
エラーメッセージは検知数について書かれていたので、以下に修正しました：
Event Frequency Timeline could not be displayed as there needs to be more than 5 events.

2022-05-25 22:09 UTC, YamatoSecurity commented
<img width="1603" alt="Screen Shot 2022-05-26 at 7 08 17" src="https://user-images.githubusercontent.com/71482215/170375436-a4eb85dc-fe1f-4c54-96c4-969c56514fa3.png">

ついでに細かい修正ですみませんが、プログレスバーと`Timestamp等々`の間に１行のスペースを入れてくれますか？

2022-05-26 00:33 UTC, hitenkoku commented
@YamatoSecurity  ご確認とメッセージの修正をご対応いただきありがとうございます。
ソースコードの修正は完了しました。ご確認のほどよろしくお願いいたします。
ドキュメントの修正は現在実施中です。

2022-05-26 05:34 UTC, YamatoSecurity commented
確認しました。良いと思います。
ありがとうございました！ドキュメント修正が終わったら、教えてください。

2022-05-26 12:35 UTC, hitenkoku commented
@YamatoSecurity  Readmeの修正が完了しました。Screenshotも1枚追加し、結果出力のスクリーンショットも更新しておきました。

2022-05-27 00:45 UTC, YamatoSecurity commented
Readmeを確認しました。OKです！

2022-05-27 01:13 UTC, merged