557 display computers with most alerts
Yamato-Security/hayabusa pull request #558
Opened 2022-06-02 12:08 UTC by hitenkoku

Closes #557 

## What Changed

-  added display computer names with most alert by levels

## Evidence

![image](https://user-images.githubusercontent.com/2350416/171625524-e350d442-cd55-46d4-865f-f75767c4c245.png)

2022-06-02 14:12 UTC, hitenkoku commented
参考情報として各レベルでの集計件数をデバッグで出しておきました。

- Critical
>debug:[("mssql01.offsec.lan", 71), ("MSEDGEWIN10", 26), ("DC1.insecurebank.local", 21), ("rootdc1.offsec.lan", 8), ("IEWIN7", 7), ("srvdefender01.offsec.lan", 5), ("IE10Win7", 3), ("alice.insecurebank.local", 3), ("FS03.offsec.lan", 3), ("LAPTOP-JU4M3I0E", 2), ("ICORP-DC.internal.corp", 2), ("DESKTOP-PIU87N6", 1), ("01566s-win16-ir.threebeesco.com", 1), ("jump01.offsec.lan", 1), ("win10-02.offsec.lan", 1)]

- High

> debug:[("FS03.offsec.lan", 643), ("IEWIN7", 408), ("IE10Win7", 260), ("MSEDGEWIN10", 230), ("PC01.example.corp", 53), ("SEC511", 49), ("rootdc1.offsec.lan", 41), ("srvdefender01.offsec.lan", 29), ("WIN-77LTAPHIQ1R.example.corp", 22), ("fs03vuln.offsec.lan", 21), ("fs02.offsec.lan", 20), ("DC1.insecurebank.local", 16), ("LAPTOP-JU4M3I0E", 15), ("PC04.example.corp", 13), ("01566s-win16-ir.threebeesco.com", 12), ("jump01.offsec.lan", 11), ("alice.insecurebank.local", 10), ("fs01.offsec.lan", 9), ("DESKTOP-NTSSLJD", 8), ("win10-02.offsec.lan", 5), ("WIN10-client01.offsec.lan", 5), ("DC-Server-1.labcorp.local", 2), ("DESKTOP-PIU87N6", 2), ("SANS-TBT570", 2), ("02694w-win10.threebeesco.com", 2), ("IE8Win7", 2), ("DESKTOP-JR78RLP", 2), ("Sec504Student", 2), ("mssql01.offsec.lan", 2), ("PC-01.cybercat.local", 2), ("exchange01.offsec.lan", 2), ("2016dc.hqcorp.local", 1), ("PC02.example.corp", 1)]

- Medium

> debug:[("IE10Win7", 234), ("MSEDGEWIN10", 192), ("IEWIN7", 175), ("srvdefender01.offsec.lan", 136), ("win10-02.offsec.lan", 102), ("SEC511", 99), ("PC01.example.corp", 57), ("rootdc1.offsec.lan", 36), ("IE8Win7", 35), ("LAPTOP-JU4M3I0E", 30), ("fs03vuln.offsec.lan", 29), ("FS03.offsec.lan", 24), ("fs01.offsec.lan", 13), ("Sec504Student", 11), ("PC-01.cybercat.local", 8), ("DESKTOP-NTSSLJD", 7), ("fs02.offsec.lan", 7), ("DC1.insecurebank.local", 7), ("mssql01.offsec.lan", 6), ("01566s-win16-ir.threebeesco.com", 6), ("jump01.offsec.lan", 5), ("PC04.example.corp", 5), ("FX-BS7", 4), ("IE9Win7", 4), ("DC-Server-1.labcorp.local", 3), ("02694w-win10.threebeesco.com", 3), ("-", 3), ("DESKTOP-JR78RLP", 1), ("ICORP-DC.internal.corp", 1), ("win10.ecorp.com", 1), ("2012r2srv.maincorp.local", 1), ("DESKTOP-PIU87N6", 1)]

- Low

> debug:[("DESKTOP-M5SN04R", 3560), ("IE10Win7", 1067), ("FS03.offsec.lan", 764), ("IEWIN7", 252), ("MSEDGEWIN10", 237), ("mssql01.offsec.lan", 147), ("srvdefender01.offsec.lan", 78), ("fs01.offsec.lan", 43), ("LAPTOP-JU4M3I0E", 39), ("rootdc1.offsec.lan", 18), ("win10-02.offsec.lan", 16), ("alice.insecurebank.local", 13), ("fs03vuln.offsec.lan", 11), ("jump01.offsec.lan", 10), ("PC01.example.corp", 9), ("FX-BS7", 6), ("PC04.example.corp", 6), ("WIN-77LTAPHIQ1R.example.corp", 3), ("fs02.offsec.lan", 3), ("04246w-win10.threebeesco.com", 3), ("DC1.insecurebank.local", 3), ("WIN10-client01.offsec.lan", 3), ("PC-01.cybercat.local", 2), ("IE8Win7", 2), ("DESKTOP-NTSSLJD", 2), ("sv-dc.hinokabegakure-no-sato.local", 1), ("SEC511", 1), ("PC02.example.corp", 1), ("win10.ecorp.com", 1)]

- Informational

> debug:[("MSEDGEWIN10", 1330), ("PC01.example.corp", 1158), ("fs03vuln.offsec.lan", 1046), ("FS03.offsec.lan", 843), ("srvdefender01.offsec.lan", 395), ("SEC511", 372), ("IEWIN7", 349), ("win10-02.offsec.lan", 331), ("DESKTOP-JR78RLP", 294), ("IE8Win7", 160), ("IE10Win7", 139), ("mssql01.offsec.lan", 81), ("rootdc1.offsec.lan", 80), ("LAPTOP-JU4M3I0E", 60), ("fs01.offsec.lan", 58), ("fs02.offsec.lan", 44), ("jump01.offsec.lan", 41), ("WIN-77LTAPHIQ1R.example.corp", 37), ("01566s-win16-ir.threebeesco.com", 29), ("IE9Win7", 25), ("PC04.example.corp", 24), ("DC-Server-1.labcorp.local", 20), ("alice.insecurebank.local", 19), ("dhcp01.offsec.lan", 12), ("37L4247D28-05", 10), ("DESKTOP-NTSSLJD", 10), ("DC1.insecurebank.local", 8), ("02694w-win10.threebeesco.com", 7), ("exchange01.offsec.lan", 7), ("prtg-mon.offsec.lan", 6), ("pki01.offsec.lan", 6), ("PC02.example.corp", 6), ("PC-01.cybercat.local", 6), ("atacore01.offsec.lan", 6), ("atanids01.offsec.lan", 6), ("adfs01.offsec.lan", 6), ("wsus01.offsec.lan", 6), ("webiis01.offsec.lan", 6), ("win10.ecorp.com", 4), ("DESKTOP-PIU87N6", 3), ("ICORP-DC.internal.corp", 3), ("SANS-TBT570", 2), ("04246w-win10.threebeesco.com", 2), ("sv-dc.hinokabegakure-no-sato.local", 1), ("DESKTOP-M5SN04R", 1)]

2022-06-02 19:05 UTC, YamatoSecurity requested changes
対応ありがとうございました！
1. １行に５台の端末名が入れそうなので、Top 3からTop 5にしましょうか？
2.
<img width="1031" alt="Screen Shot 2022-06-03 at 3 47 54" src="https://user-images.githubusercontent.com/71482215/171710111-97692e01-9500-4663-b813-b4de691dc9c2.png">
1台の端末の場合は、同じエラーメッセージが沢山出ています。
 １台の場合は、このサマリを完全に出力しない方が良いかなと最初思っていましたが、「なぜある場合とない場合があるの？」と混乱するユーザが居そうなので、端末１台の場合でも同じように表示しましょう。
例：
```
Top 5 computers with critical alerts: ComputerA (2)
Top 5 computers with high alerts: n/a 
Top 5 computers with medium alerts: ComputerA (1)
等々
```
無い場合は「n/a」を出力する。Computerフィールドが「-」になる時があるようで、誤検知っぽいので、Computer名が「-」の場合は無視しましょうか？

2022-06-02 19:07 UTC, YamatoSecurity commented
Top 3 computers with alertsのメッセージが上記のDates with top alertsと同じ文章だったので、修正しました。

2022-06-02 23:18 UTC, hitenkoku commented
@YamatoSecurity unique detectionsで集計をすると、
AルールにおいてComputer 1が検知したあとに、同じAルールでComputer 2が検知しても集計対象にならなくなってしますが問題ないでしょうか。

内容から察すると、コンピュータ名かつルール名をキーとして、n回検知しても集計としては1回としてカウントするという認識でよろしいでしょうか。

2022-06-02 23:22 UTC, hitenkoku commented
@YamatoSecurity  以下の件は https://github.com/Yamato-Security/hayabusa/pull/558/commits/0b033247020922ff86ead127932842b30d84bd2b で対応が完了しました。

> 1. １行に５台の端末名が入れそうなので、Top 3からTop 5にしましょうか？
> 
> 1台の端末の場合は、同じエラーメッセージが沢山出ています。 １台の場合は、このサマリを完全に出力しない方が良いかなと最初思っていましたが、「なぜある場合とない場合があるの？」と混乱するユーザが居そうなので、端末１台の場合でも同じように表示しましょう。 例：
> ```
> Top 5 computers with critical alerts: ComputerA (2)
> Top 5 computers with high alerts: n/a 
> Top 5 computers with medium alerts: ComputerA (1)
> 等々
> ```
> 
> 無い場合は「n/a」を出力する。Computerフィールドが「-」になる時があるようで、誤検知っぽいので、Computer名が「-」の場合は無視しましょうか？

2022-06-02 23:50 UTC, hitenkoku commented
@YamatoSecurity 以下の考え方で https://github.com/Yamato-Security/hayabusa/pull/558/commits/0b033247020922ff86ead127932842b30d84bd2b にて実装を完了しました。想定されているものになっているかお手数ですがご確認のほどよろしくお願いいたします。

> 
> 内容から察すると、コンピュータ名かつルール名をキーとして、n回検知しても集計としては1回としてカウントするという認識でよろしいでしょうか。

2022-06-03 02:37 UTC, hitenkoku commented
#560 と同様のバグがこちらに入ってしまっているので対応しておきます。

2022-06-03 03:01 UTC, merged