Feature/improve parallel processing
Yamato-Security/hayabusa pull request #622
Opened 2022-07-07 15:08 UTC by kazuminn

fix #479.

DashMapという並列HashMapを使うと、

私の環境では、2割ほど早くなりました。

実装するにあたって、
Message構造体をなくして、グローバルに直にMESSAGEを定義しています。
なぜそうしているかというと、早い話、速度が出ないからです。
セグメントごとに所有権を持ってスレッドに渡しているのに、それらをラップして一つの所有権にしてしまうので、
速度が出ないです。

そのため、いろいろMessageのスレッドになっていましたが、トップにじかに書いています。

あと、ファイル名の名前が分かりずらいと感じだので、変更しました。print.rsをmessage.rsに変えました。
message::insertとかになるので、この方が分かりやすいかなと。

DashMapを使うにあたって、
test_create_and_append_messageというテストを動くように書けないので、消しました。
DashMapの方のmemberを文字列として取得したいが、privateなので、できませんでした。
https://github.com/Yamato-Security/hayabusa/commit/7fcb3496b3279775161c86a0c8589da5f688c3c1
こんな感じで試行錯誤したけど、無理でした。

2022-07-07 15:28 UTC, kazuminn commented
about 00:20:00. -> 00:11:53.297
の結果が出ました。

@YamatoSecurity ベンチマークの方お願いします。

2022-07-07 15:50 UTC, kazuminn commented
あ。すみません。時間でソートをするのを忘れていました汗

2022-07-11 00:14 UTC, YamatoSecurity commented
@kazuminn ありがとうございます！
今ベンチマークを取っているので、少々お待ちください。

2022-07-13 07:20 UTC, YamatoSecurity commented
@kazuminn 大変お待たせしました！
macでもwindowsでも動作確認していたので、結構時間かかりました。
私の環境では、evtxファイルが小さい場合は同じぐらいで、7.6GBのデータで試したら、17分から15分まで約15%早くなっています。
良いと思います！

ソースコードが結構変わっているので、念の為 @hitenkoku さんか @hach1yon さんにソースの確認をお願いできますか？
(他に誰か変更を把握した方が良さそうだし）

2022-07-13 09:49 UTC, hitenkoku requested changes
一部不要なコメントがあるので消してください。
　あと、ファイル名の変更については他作業者の影響を考えて理由がない場合は最小限としてください

2022-07-13 09:49 UTC, hitenkoku commented on src/detections/message.rs
> +///----------------------end for struct MESSAGE------------------------------
不要なコメントなので削除しておいてください

2022-07-13 09:49 UTC, hitenkoku commented on src/detections/message.rs
> +///----------------------start for struct MESSAGE------------------------------
不要なコメントなので削除しておいてください

2022-07-13 15:46 UTC, kazuminn commented on src/detections/message.rs
> +///----------------------end for struct MESSAGE------------------------------
削除しました。

2022-07-13 15:46 UTC, kazuminn commented on src/detections/message.rs
> +///----------------------start for struct MESSAGE------------------------------
削除しました。

2022-07-13 15:50 UTC, kazuminn commented on src/detections/message.rs
> +///----------------------end for struct MESSAGE------------------------------
ファイル名に関してですが、コミットに理由を含めて書いていなくて申し訳ないです。
理由といたしましては、上記に書きました

> ファイル名の名前が分かりずらいと感じだので、変更しました。print.rsをmessage.rsに変えました。
message::insert()とかになるので、この方が分かりやすいかなと。

print::insert()とかになるとわかりにくい

2022-07-13 15:59 UTC, hitenkoku approved these changes

2022-07-14 03:33 UTC, merged