auto clear PIVOT_KEYWORD in every unit test
Yamato-Security/hayabusa pull request #702
Opened 2022-09-18 08:30 UTC by kazuminn

Old code consider programer side effect of PIVOT_KEYWORD.
So I add auto clear code. Because I wanna to be miss is off.

2022-09-18 08:59 UTC, kazuminn commented
並列にテストするので、テストでこけちゃうのですが、
CIでcargo test -- --test-threads=1みたいにできるなら、ワンスレッドでテストを回すのがよさそうだと思うのですが、どうでしょう？
　
https://github.com/Yamato-Security/hayabusa/issues/639
このissueのrace conditionのテストもワンスレッドじゃないので、ignoreにしているので、平常時は無視されます。
ワンスレッドにすると、時間はかかるのですが、毎度のテストカバー率が上がります。　
できるのかを確認していないのですが、どうでしょうか？
@YamatoSecurity @hitenkoku

2022-09-18 09:00 UTC, hitenkoku commented
@kazuminn テストが通ってないのでまずそこの確認をお願いいたします

2022-09-18 09:03 UTC, hitenkoku commented
@YamatoSecurity  それであれば、このpull requestで cargo test -- test-threads=1 を `.github/workflows/rust.yml` で修正をかけてもらってよろしいでしょうか。現状だとCIでうまく動作するかの判断ができないため、このpull-requestでCIも確認できるか対応してください。

2022-09-18 09:04 UTC, hitenkoku requested changes
@kazuminn  それであれば、このpull requestで cargo test -- test-threads=1 を .github/workflows/rust.yml で修正をかけてもらってよろしいでしょうか。現状だとCIでうまく動作するかの判断ができないため、このpull-requestでCIも確認できるか対応してください。

@YamatoSecurity  これはテストの対応の話ではありますので、確実にテストコードが通るようにしてからマージをしたいと思いますがいかがでしょうか。

2022-09-18 10:27 UTC, hitenkoku commented
@kazuminn CIのテストをパスしていることを確認しました。race conditionのテストについてもignoreを除外して動作するかどうか確認をお願いできますでしょうか

2022-09-18 10:36 UTC, kazuminn commented
@hitenkoku これ今パスしていますが、なにもテストしてない状態です。ただ今少し、調整中です。

2022-09-19 01:54 UTC, YamatoSecurity commented
@kazuminn 、PRありがとうございます！
ワンスレッドにして、毎度のテストカバー率が上がるのであれば、時間がよりかかっても大丈夫です。品質を優先したいです。

@hitenkoku 
> これはテストの対応の話ではありますので、確実にテストコードが通るようにしてからマージをしたいと思いますがいかがでしょうか。

はい、大丈夫です。

2022-09-19 10:11 UTC, kazuminn commented
@YamatoSecurity 了解です。



-- test-threads=1をつけ足せば、通常なら、いけますが、hayabusaのコマンドラインパースが悪さをしていて、現状エラーを吐きます。https://rust-lang-jp.zulipchat.com/#narrow/stream/124300-questions/topic/cargo.20test.E3.81.A7.E3.83.86.E3.82.B9.E3.83.88.E5.90.8D.E3.82.92.E6.8C.87.E5.AE.9A.E3.81.99.E3.82.8B.E3.81.A8.E3.82.A8.E3.83.A9.E3.83.BC.E3.81.AB.E3.81.AA.E3.82.8B/near/299430908

時間はかかりますが、対応します。

2022-09-20 09:20 UTC, kazuminn commented
現状clapの使い方が良くないせいで、テスト時にエラーが出ています。
現状、グローバルでConfigを持つために、テストからでもコマンドライン引数をパースしてしまいますが、これだとcargoテストの引数をhayabusa側に渡してしまって、そんなサブコマンドないよ、とエラーが出ます。
mainなどでコマンドライン引数をパースして、関数に必要な項目だけを渡すのが普通のclapの使い方のようです。

コミュニティーの方でそれらを質問していました。
https://github.com/clap-rs/clap/discussions/4234

上のことが伝わるかわかりませんが、
要は、コマンドライン引数を
グローバルに持っている　→　できるだけ上の関数でもって、引数で渡してあげる
に変更したいということです。

かなりの広範囲を書き換えることになりそうですが、よさそうでしょうか？
@hitenkoku @YamatoSecurity

2022-09-20 09:37 UTC, YamatoSecurity commented
なるほど、clapを書き換えるなら、まず https://github.com/Yamato-Security/hayabusa/issues/656 で書かれているように各アクションをサブコマンドにしたいです。今Dさんがアサインされていますが、どうしましょう？

2022-09-20 10:24 UTC, hitenkoku commented
@YamatoSecurity  話題に上がっている内容ですが、hayabusaの初期リリース時からどうするかという話が上がっていましたが、対処が難しく、リリースを優先するためずっと課題としていた問題になります。
違ったら申し訳ないですが、現在の形のシングルトンを採用したのってテストを実施したときにテストが並列で走ることによって検知データ周りのテストがうまくいかないということが原因だったかと思っています。

 @hach1yon さんだったら詳細な理由をご存知かもしれません。

私がやろうとしていたサブコマンドですが、もともとのグローバル(config.rs)でシングルトンで保持をして対応をする方針は変わらないのでこの問題は解決はしないと思います。

2022-09-20 11:24 UTC, hitenkoku commented
https://github.com/Yamato-Security/hayabusa/issues/65 おそらく関連するissueはこちらだと思います

2022-09-20 11:41 UTC, kazuminn commented
そのissueだと、わからないから、その場しのぎで、エラー起きなくしよう、みたいな感じなんですね。





（作業量多そうですけど、手が動く余裕があるので、やろうかな？と思っていることは、表明しておきます。

2022-09-20 16:31 UTC, fukusuket commented
Excuse me for cutting in, If all you want is to test in a single thread,
It works for my enviroment with the [env variable(RUST_TEST_THREADS=1)](https://doc.rust-lang.org/rustc/tests/index.html#--test-threads-num_threads).
(It won't solve [the actual cause of the problem](https://github.com/Yamato-Security/hayabusa/pull/702#issuecomment-1252076778) ... 🫣 and I haven't tested whether it works with CI...)

- macOS: 
  - `RUST_TEST_THREADS=1 cargo test --verbose`

- Windows(Powershell):
  - `$env:RUST_TEST_THREADS=1; cargo test --verbose`

If this is known, please ignore🚀

2022-09-21 00:45 UTC, hitenkoku commented
参考ですが、初期の段階ではtestmodeというものを作成していたようなのでそちらを実装してもらってtestのエラーをパスするという方法をやっていたようです。

https://github.com/Yamato-Security/hayabusa/pull/67

2022-09-21 12:51 UTC, hitenkoku commented
@fukusuket Thank you for your comment.
If env is enabled in CI, I think it is better than a big change for the test.
I will test whether the env is set in CI or not.

@YamatoSecurity 
fukuketさんが書かれている内容でCIが通せるのであればそれでよさそうかなとも思っています。発表とかもあるので大きな修正をかけて全部動かなくなるという状態は避けたいと思っています。
一旦私の別のブランチでテストできないか確認してみます。

2022-09-22 02:13 UTC, YamatoSecurity commented
@hitenkoku チェックと情報共有ありがとうございます！
@kazuminn がこのPRの担当者なので、彼に任せようと思っています。もし何か不具合があれば、すぐrevertできると思います。kazuminさん、どうしたいですか？
また、発表の時にリリースページで用意されているバイナリを使うので、開発用のmainブランチを変えても構いません。

2022-09-22 03:09 UTC, kazuminn commented
@YamatoSecurity そうですね。fukuketさんが書かれている内容でCIが通せたので、一旦これでいこうと思います。

2022-09-22 03:13 UTC, kazuminn commented
CIのテストをパスしていることを確認しました。race conditionのテストについてもignoreを除外して動作するかどうか確認をもできました。
レビューの方よろしくお願いします。 @hitenkoku 

```
.
.
.
test yaml::tests::test_read_yaml ... ok

test result: ok. 205 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.71s
```

2022-09-22 04:05 UTC, hitenkoku approved these changes
LGTM

2022-09-22 04:18 UTC, merged

2022-09-22 04:49 UTC, kazuminn commented
@fukusuket thanks for the infomation.

2022-09-22 11:27 UTC, kazuminn commented
NOTE:
今現在、無視しているテストはなく、すべてのテストが通っています。




> @hach1yon さんだったら詳細な理由をご存知かもしれません。

広範囲で使うから引数で渡すの面倒だから　< @hach1yon より

2022-09-22 11:32 UTC, kazuminn commented
Note:
はじめから今まで並列でテストが走っており、これからシングルスレッド運用になった。