Reduct DetectInfo fields memory
Yamato-Security/hayabusa pull request #806
Opened 2022-11-14 01:04 UTC by fukusuket

## What Changed

- Reduced memory usage of DetectInfo #789
- add `Profile` Enum in `option/profile.rs ` and remove lazy_static `PRELOAD_xx`.
  - for storing follows data.
    - profiles.yaml key-value (before convertion)
    - converted value (ex. `%Temestamp%` -> `2013-10-24 01:16:13.843 +09:00`)
  - for Pattern matching for profile function
- change `DetectInfo` fileds and behaviors as follows
  - change `ext_field`  type `Nested<Vec<CompactString>>` -> `Vec<(CompactString, Profile)>`(tuple)
  - add `is_condition` to check whether the detected rule was `[condition]` based.
  - clear `details` when the moment stored details string in `ext_field`
    - I think this change has the most affected on memory reduction in this PR.
## Evidence
I got the benchmark with [this environment and procedure](https://github.com/Yamato-Security/hayabusa/issues/778#issuecomment-1296504766). ]
Compared to version 1.8.0, I confirmed reduction of memory usage : -200MB(avg) -510MB(max peak).

|version |avg mem| max mem|Elapsed Time|
|-----|--------------|----------------|------------------------------|
|v180| 3.13GB| peak 5.64GB |00:13:22.948|
|v190-dev| 2.93GB| peak 5.13GB |00:13:18.767|

2022-11-14 07:28 UTC, YamatoSecurity commented
@fukusuket 
対応ありがとうございます！
Intel Macで14GBのデータに対して、`-P super-verbose`プロファイルで比較してみました。

1.8.0: 
メモリ: 20 GB
処理時間: 00:30:04.921

1.9.0-dev:
メモリ: 18.5 GB (7.5%削減)
処理時間: 00:27:24.418 (9%加速)

検知数は一緒ですが、Events with hitsとData reductionの合計が変わっています。
1.8.0:
```
Events with hits / Total events: 2,705,252 / 14,213,054 (Data reduction: 11,507,802 events (80.97%))

Total | Unique detections: 3,925,540 | 749
Total | Unique critical detections: 104 (0.00%) | 21 (2.80%)
Total | Unique high detections: 451,919 (11.51%) | 303 (40.45%)
Total | Unique medium detections: 185,392 (4.72%) | 249 (33.24%)
Total | Unique low detections: 1,201,680 (30.61%) | 105 (14.02%)
Total | Unique informational detections: 2,086,445 (53.15%) | 71 (9.48%)
```

1.9.0-dev:
```
Events with hits / Total events: 2,706,807 / 14,213,054 (Data reduction: 11,506,247 events (80.96%))

Total | Unique detections: 3,925,540 | 749
Total | Unique critical detections: 104 (0.00%) | 21 (2.80%)
Total | Unique high detections: 451,919 (11.51%) | 303 (40.45%)
Total | Unique medium detections: 185,392 (4.72%) | 249 (33.24%)
Total | Unique low detections: 1,201,680 (30.61%) | 105 (14.02%)
Total | Unique informational detections: 2,086,445 (53.15%) | 71 (9.48%)
```

確認して頂けますか？

2022-11-14 09:07 UTC, YamatoSecurity commented
`-P minimal`プロファイルでも比較してみました。

1.8.0: 
メモリ: 9.26 GB
処理時間: 00:27:20.853

1.9.0-dev:
メモリ: 8 GB (約15%削減)
処理時間: 00:26:57.496 (約2%加速)

`minimal`プロファイルの方がメモリ使用が削減されますが、処理時間はそんな変わらないようですね。

参考に1.4.3も同じルールで試しました:
メモリ: 100%時に5.3GB、スキャン後に6.75GBに増えた
処理時間: 00:33:47.368

```
Total events: 10012719
Data reduction: 7306619 events (72.97%)

Total detections: 3929895
Total critical detections: 104
Total high detections: 452326
Total medium detections: 189474
Total low detections: 1201564
Total informational detections: 2086427

Unique detections: 751
Unique critical detections: 21
Unique high detections: 305
Unique medium detections: 250
Unique low detections: 104
Unique informational detections: 71
```

2022-11-14 11:22 UTC, fukusuket commented
@YamatoSecurity 

検証いただき、ありがとうございます🙇 Events with hitsのリグレッションすみません、修正いたします！
現在の修正は、%Details%のメモリ削減を見込んでいるのですが(そのため、minimalのほうが効果が大きく見えると思われます)、%AllFieldInfo%も同じ手法で削減できないか確認いたします！

2022-11-15 00:31 UTC, fukusuket commented
Events with hits件数不具合修正と、%AllFieldInfo%改善版作成いたしました！
%AllFieldInfo%でも%Details%と同様に途中でStringをクリアする処理を入れたところ、修正前後の結果は以下の通りでした。
|version| profile | avg mem | max mem | elasped time|
|----| ------- |------| ------|------------|
|v180| default |3.13GB| 5.64GB|00:13:22.948|
|v190-dev  [03411da](https://github.com/Yamato-Security/hayabusa/pull/806/commits/03411daac4448b9e4ca97d32cc8b92e01a98c1b8) (%AllFieldInfo%改善後)| default| 2.92GB| 4.85GB|00:13:07.053|
|v190-dev [03411da](https://github.com/Yamato-Security/hayabusa/pull/806/commits/03411daac4448b9e4ca97d32cc8b92e01a98c1b8) (%AllFieldInfo%改善後) | super-verbose|4.33GB| 8.66GB|00:13:08.769|
|v190-dev [3dc9e80](https://github.com/Yamato-Security/hayabusa/pull/806/commits/3dc9e80cba615eaecde04783025fa1b47cbdf6b5) (%AllFieldInfo%改善前)| super-verbose| 4.91GB| 9.88GB|00:13:08.920|

また%Details%の処理ももう少し改善(不要なvec/hashmapアクセスの削除)を加えたところ、少し速度改善したようです :)

2022-11-15 12:12 UTC, YamatoSecurity commented
@fukusuket あれ、Githubチェックは無事のようですが、cargoをアップデートしたら、ローカル環境で以下の警告が出ていました：
```
warning: use of deprecated associated function `chrono::TimeZone::timestamp`: use `timestamp_opt()` instead
   --> src/afterfact.rs:955:32
    |
955 |         let offset_sec = Local.timestamp(0, 0).offset().local_minus_utc();
    |                                ^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `chrono::TimeZone::ymd`: use `with_ymd_and_hms()` instead
   --> src/detections/detection.rs:258:32
    |
258 |         let default_time = Utc.ymd(1970, 1, 1).and_hms(0, 0, 0);
    |                                ^^^

warning: use of deprecated associated function `chrono::Date::<Tz>::and_hms`: Use and_hms_opt() instead
   --> src/detections/detection.rs:258:48
    |
258 |         let default_time = Utc.ymd(1970, 1, 1).and_hms(0, 0, 0);
    |                                                ^^^^^^^

warning: use of deprecated associated function `chrono::TimeZone::ymd`: use `with_ymd_and_hms()` instead
  --> src/detections/rule/count.rs:31:28
   |
31 |     let default_time = Utc.ymd(1977, 1, 1).and_hms(0, 0, 0);
   |                            ^^^

warning: use of deprecated associated function `chrono::Date::<Tz>::and_hms`: Use and_hms_opt() instead
  --> src/detections/rule/count.rs:31:44
   |
31 |     let default_time = Utc.ymd(1977, 1, 1).and_hms(0, 0, 0);
   |                                            ^^^^^^^

warning: use of deprecated associated function `chrono::TimeZone::timestamp`: use `timestamp_opt()` instead
   --> src/options/update.rs:223:44
    |
223 |         let mut latest_update_date = Local.timestamp(0, 0);
    |                                            ^^^^^^^^^

warning: `hayabusa` (lib) generated 6 warnings
```

念の為、確認をお願いできますか？

2022-11-15 12:28 UTC, YamatoSecurity commented
`-P super-verbose`でもう一回試したら、20GB -> 18.5 -> 更に 16GBまで減りました！
とても良い感じです！

Events数も直りました。ありがとうございました！

2022-11-15 12:29 UTC, YamatoSecurity approved these changes
LGTM!
@hitenkoku どうですか？

2022-11-15 13:53 UTC, YamatoSecurity commented
なるほど、良いと思います。では、とりあえずChronoを0.4.22に固定しました。

> Chrono 0.4.23リリース(3days ago)で現在使っているいくつかの関数がdeprecatedになったことが原因のようです :( 別issueでChronoのdeprecate関数の削除を対応するのがよさそうかと思いました！ https://docs.rs/chrono/0.4.23/chrono/offset/trait.TimeZone.html#method.ymd https://github.com/chronotope/chrono/releases/tag/v0.4.23

2022-11-15 14:13 UTC, fukusuket commented
すみません...🙇 1点まだ不具合があり、%AllFieldInfo%に値ないときは、- (ハイフン)を出力するのがもともとの仕様だったため、そちら修正いたします！

2022-11-15 15:50 UTC, fukusuket commented
>%AllFieldInfo%に値ないときは、- (ハイフン)を出力する

↑の修正および
v180と比較して、-j, -J, -P minimal,-P (standard),-P all-field-info オプションの出力結果に不要な差分がないことを確認しました。手元でのテストは完了です。

@YamatoSecurity @hitenkoku  こちらのcommitにてレビュー頂けますと幸いです、よろしくお願いいたします🙇

2022-11-15 19:38 UTC, hitenkoku commented
この件は既にmainにマージされている 7266abff2bfe678e33b27d84386ddb3febc7657d で対応済みです。

> @fukusuket あれ、Githubチェックは無事のようですが、cargoをアップデートしたら、ローカル環境で以下の警告が出ていました：
> 
> ```
> warning: use of deprecated associated function `chrono::TimeZone::timestamp`: use `timestamp_opt()` instead
>    --> src/afterfact.rs:955:32
>     |
> 955 |         let offset_sec = Local.timestamp(0, 0).offset().local_minus_utc();
>     |                                ^^^^^^^^^
>     |
>     = note: `#[warn(deprecated)]` on by default
> 
> warning: use of deprecated associated function `chrono::TimeZone::ymd`: use `with_ymd_and_hms()` instead
>    --> src/detections/detection.rs:258:32
>     |
> 258 |         let default_time = Utc.ymd(1970, 1, 1).and_hms(0, 0, 0);
>     |                                ^^^
> 
> warning: use of deprecated associated function `chrono::Date::<Tz>::and_hms`: Use and_hms_opt() instead
>    --> src/detections/detection.rs:258:48
>     |
> 258 |         let default_time = Utc.ymd(1970, 1, 1).and_hms(0, 0, 0);
>     |                                                ^^^^^^^
> 
> warning: use of deprecated associated function `chrono::TimeZone::ymd`: use `with_ymd_and_hms()` instead
>   --> src/detections/rule/count.rs:31:28
>    |
> 31 |     let default_time = Utc.ymd(1977, 1, 1).and_hms(0, 0, 0);
>    |                            ^^^
> 
> warning: use of deprecated associated function `chrono::Date::<Tz>::and_hms`: Use and_hms_opt() instead
>   --> src/detections/rule/count.rs:31:44
>    |
> 31 |     let default_time = Utc.ymd(1977, 1, 1).and_hms(0, 0, 0);
>    |                                            ^^^^^^^
> 
> warning: use of deprecated associated function `chrono::TimeZone::timestamp`: use `timestamp_opt()` instead
>    --> src/options/update.rs:223:44
>     |
> 223 |         let mut latest_update_date = Local.timestamp(0, 0);
>     |                                            ^^^^^^^^^
> 
> warning: `hayabusa` (lib) generated 6 warnings
> ```
> 
> 念の為、確認をお願いできますか？

2022-11-15 19:41 UTC, hitenkoku requested changes
確認しました。chronoのlintエラーに関連したバージョン固定は不要ですのでそちらを戻していただければ他は問題ありません

2022-11-15 19:41 UTC, hitenkoku commented on Cargo.toml
> +chrono = "0.4.22"
ここのlintエラーは既に 7266abff2bfe678e33b27d84386ddb3febc7657d で対応済みなのでmainをマージした後に問題が発生しなければ元に戻していただけますでしょうか

2022-11-15 23:46 UTC, fukusuket commented on Cargo.toml
> +chrono = "0.4.22"
対応済みとのこと承知しました！ありがとうございます、修正いたします！

2022-11-16 00:08 UTC, fukusuket commented on Cargo.toml
> +chrono = "0.4.22"
修正いたしました！ご確認いただけますと幸いです🙇

2022-11-16 00:29 UTC, hitenkoku approved these changes
LGTM。ご対応ありがとうございます。

2022-11-16 00:30 UTC, merged