[WIP] add grcov ( test coverage ) in CI
Yamato-Security/hayabusa pull request #813
Opened 2022-11-18 14:06 UTC by kazuminn

## What Changed

- Changed 1
- add grcov ( test coverage ) in CI

## Evidence

Please describe the functionality gained by merging this pull-request and the evidence that the bug has been fixed.

2022-11-19 02:04 UTC, YamatoSecurity requested changes
toolchainは`nightly`より`stable`の方が良いのでは？

2022-11-20 06:19 UTC, hitenkoku commented
@YamatoSecurity 

> Annotationsにある警告を直したいですね〜
> 
> あ、別のissueで対応します？

https://github.com/Yamato-Security/hayabusa/issues/815

2022-11-20 09:56 UTC, kazuminn commented
@YamatoSecurity 
> toolchainはnightlyよりstableの方が良いのでは？

profileを吐き出すために、-zオプションが必要なのですが、nightlyじゃないとそのオプションが使えないです。
なので、nightlyじゃないとだめです。
他のworkflowと独立しているので、大丈夫だと思います。

2022-11-20 10:13 UTC, kazuminn commented
ci上でcoverageを計測するところまでできました。

@YamatoSecurity 
READMEにバッチを表示したり、可視化したりするのにcodecovというwebサードパーティーと連帯する必要があるのですが、
githubのSettingsにアクセスする必要があり権限が必要です。
私に権限を振るか、以下のページに従って、アプリをインストールしていただくとありがたいです。
https://qiita.com/shinya_sun_sun/items/6c14e7145235713db434

2022-11-20 10:37 UTC, YamatoSecurity commented
> profileを吐き出すために、-zオプションが必要なのですが、nightlyじゃないとそのオプションが使えないです。
> なので、nightlyじゃないとだめです。
> 他のworkflowと独立しているので、大丈夫だと思います。

なるほど！なら、大丈夫です！

2022-11-20 10:38 UTC, YamatoSecurity commented
> READMEにバッチを表示したり、可視化したりするのにcodecovというwebサードパーティーと連帯する必要があるのですが、
> githubのSettingsにアクセスする必要があり権限が必要です。
> 私に権限を振るか、以下のページに従って、アプリをインストールしていただくとありがたいです。

了解です。こちらでインストールしてみます！

2022-11-21 11:36 UTC, kazuminn commented
> CodecovのGitHubアプリをインストールしました。確認して頂けますか？


@YamatoSecurity 確認できました。ありがとうございます。

2022-11-22 05:35 UTC, kazuminn commented
今現在、68.20%でした。
https://app.codecov.io/gh/Yamato-Security/hayabusa/tree/feature%2Fgrcov
（閲覧権限があると見れる。今のところ　yamatosecurity と kazuminnが見れる)



@YamatoSecurity　お疲れ様です。バッジを表示するために、codecovのsettingからmarkdownをコピーしてこないといけないのですが、お願いできますでしょうか？以下のページに従うと、できると思います。
https://qiita.com/shinya_sun_sun/items/6c14e7145235713db434#codecov%E3%81%AB%E9%80%A3%E6%90%BA%E3%81%97%E3%81%9F%E3%82%AB%E3%83%90%E3%83%AC%E3%83%83%E3%82%B8%E6%B8%AC%E5%AE%9A%E7%B5%90%E6%9E%9C%E3%82%92%E3%83%90%E3%83%83%E3%82%B8%E3%81%A7%E8%A1%A8%E7%A4%BA

2022-11-22 05:38 UTC, kazuminn commented
pushをすると、毎回報告してくるのを抑制したい。
https://github.com/Yamato-Security/hayabusa/pull/813#issuecomment-1323090856

2022-11-22 05:39 UTC, kazuminn commented
@YamatoSecurity すみません。私の方でできました。
> @YamatoSecurity　お疲れ様です。バッジを表示するために、codecovのsettingからmarkdownをコピーしてこないといけないのですが、お願いできますでしょうか？以下のページに従うと、できると思います。

2022-11-22 05:44 UTC, kazuminn commented
[![codecov](https://codecov.io/gh/Yamato-Security/hayabusa/branch/feature/grcov/graph/badge.svg?token=WFN5XO9W8C)](https://codecov.io/gh/Yamato-Security/hayabusa/)

2022-11-22 06:40 UTC, kazuminn commented
> pushをすると、毎回報告してくるのを抑制したい。
https://github.com/Yamato-Security/hayabusa/pull/813#issuecomment-1323090856

botにwrite権限を持たせないようにして、抑制した。

2022-11-22 06:43 UTC, kazuminn commented
これから、Annotationsを消せたら消す。

2022-11-22 07:01 UTC, kazuminn commented
@YamatoSecurity 
coverageのバッチですが、この数値で今READMEに表示しますか？
それとも、もう少し数値を上げてから、表示しますか？
現在、68%です。

2022-11-22 11:59 UTC, YamatoSecurity commented
> coverageのバッチですが、この数値で今READMEに表示しますか？
> それとも、もう少し数値を上げてから、表示しますか？

とりあえず載せましょうか？

2022-11-25 00:05 UTC, YamatoSecurity approved these changes
@kazuminn これはもうマージしてOKですか？
あとはバッジの追加？

2022-12-28 09:35 UTC, hitenkoku commented
@YamatoSecurity markdownへのbadge追加とmainブランチのマージを行ったところ、CIのgrcovでエラーが出るようになってしまったため私がcommitしたものは https://github.com/Yamato-Security/hayabusa/compare/82fc8b923ffcb8bb048e9efbb09e63343d71489a..ef733a62721262959e614ffaf8730ba171380ceb で取り下げました(私以外の人がその期間でcommitしていないのは確認済みです)

2022-12-29 01:57 UTC, hitenkoku commented
#856 で対応完了したためこのpull-requestはcloseします

2022-12-29 01:57 UTC, closed without merging