Update to clap 4.x
Yamato-Security/hayabusa pull request #817
Opened 2022-11-19 07:11 UTC by hitenkoku

## What Changed

- updated to clap v4

Note:  
```
Colored output is currently not supported in clap v4.

However, it appears that v4 will be developed with high priority, so another pull-request will be made once colored display is supported.
```
ref: https://github.com/clap-rs/clap/issues/4132#issuecomment-1292860508

## Evidence

https://github.com/clap-rs/clap/issues/4132#issuecomment-1292860508

<details>
<summary>main branch (216f9a02af281b5470ca15abc1896b6ca8a430e5) result </summary>

``` powershell
 >./main.exe -d ..\hayabusa-sample-evtx\ -o main.csv -q

...

Analyzing event files: 581
Total file size: 148.5 MB

Loading detections rules. Please wait.

Excluded rules: 14
Noisy rules: 5 (Disabled)

Experimental rules: 1892 (58.89%)
Stable rules: 213 (6.63%)
Test rules: 1108 (34.48%)

Hayabusa rules: 141
Sigma rules: 3072
Total enabled detection rules: 3213

...

Results Summary:

Events with hits / Total events: 19,565 / 76,967 (Data reduction: 57,402 events (74.58%))

Total | Unique detections: 32,742 | 587
Total | Unique critical detections: 46 (0.14%) | 18 (3.07%)
Total | Unique high detections: 6,237 (19.05%) | 265 (45.14%)
Total | Unique medium detections: 1,585 (4.84%) | 176 (29.98%)
Total | Unique low detections: 6,626 (20.24%) | 75 (12.78%)
Total | Unique informational detections: 18,248 (55.73%) | 53 (9.03%)

Dates with most total detections:
critical: 2019-07-19 (15), high: 2016-09-20 (3,664), medium: 2021-04-22 (186), low: 2016-09-20 (3,777), informational: 2016-08-19 (2,105)

Top 5 computers with most unique detections:
critical: MSEDGEWIN10 (6), IEWIN7 (3), rootdc1.offsec.lan (2), srvdefender01.offsec.lan (2), FS03.offsec.lan (2)
high: MSEDGEWIN10 (119), IEWIN7 (72), FS03.offsec.lan (34), fs03vuln.offsec.lan (29), IE10Win7 (24)
medium: MSEDGEWIN10 (67), IEWIN7 (40), FS03.offsec.lan (17), IE10Win7 (15), PC01.example.corp (15)
low: MSEDGEWIN10 (33), IEWIN7 (16), FS03.offsec.lan (16), fs03vuln.offsec.lan (13), fs01.offsec.lan (11)
informational: MSEDGEWIN10 (18), IEWIN7 (17), fs01.offsec.lan (15), PC01.example.corp (13), FS03.offsec.lan (12)

╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Top critical alerts:                                              Top high alerts:
                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Sticky Key Like Backdoor Usage (10)                               Metasploit SMB Authentication (3,562)               │
│ Active Directory Replication from Non Machine Account (6)         Malicious Svc Possibly Installed (271)              │
│ Meterpreter or Cobalt Strike Getsystem Service Installation (6)   Susp Svc Installed (257)
                  │
│ Defender Alert (Severe) (4)                                       PowerShell Scripts Installed as Services (253)      │
│ WannaCry Ransomware (4)                                           Suspicious Service Installation Script (250)        │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:                                                Top low alerts:
                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Potentially Malicious PwSh (235)                                  Logon Failure (Wrong Password) (3,564)              │
│ Proc Injection (104)                                              Susp CmdLine (Possible LOLBIN) (1,418)              │
│ Reg Key Value Set (Sysmon Alert) (103)                            Non Interactive PowerShell (325)
                  │
│ Suspicious Remote Thread Target (93)                              Rare Service Installations (321)
                  │
│ Wscript Execution from Non C Drive (61)                           Windows Processes Suspicious Parent Directory (282) │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top informational alerts:
                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Proc Exec (11,173)                                                Explicit Logon (342)
                  │
│ NetShare File Access (2,564)                                      Svc Installed (331)
                  │
│ PwSh Scriptblock (789)                                            New Non-USB PnP Device (268)                        │
│ PwSh Pipeline Exec (680)                                          Logon (Type 3 Network) (228)                        │
│ NetShare Access (433)                                             File Created (210)
                  │
╰─────────────────────────────────────────────────────────────────╌─────────────────────────────────────────────────────╯

Elapsed time: 00:00:10.736
Saved file: main.csv (16.3 MB)
```
</details>

<details>
<summarythis pull request results</summary>

```powershell

>.\725.exe -d ..\hayabusa-sample-evtx\ -o 725.csv -q
...

Analyzing event files: 581
Total file size: 148.5 MB

Loading detections rules. Please wait.

Excluded rules: 14
Noisy rules: 5 (Disabled)

Experimental rules: 1892 (58.89%)
Stable rules: 213 (6.63%)
Test rules: 1108 (34.48%)

Hayabusa rules: 141
Sigma rules: 3072
Total enabled detection rules: 3213

...

Results Summary:

Events with hits / Total events: 19,565 / 76,967 (Data reduction: 57,402 events (74.58%))

Total | Unique detections: 32,742 | 587
Total | Unique critical detections: 46 (0.14%) | 18 (3.07%)
Total | Unique high detections: 6,237 (19.05%) | 265 (45.14%)
Total | Unique medium detections: 1,585 (4.84%) | 176 (29.98%)
Total | Unique low detections: 6,626 (20.24%) | 75 (12.78%)
Total | Unique informational detections: 18,248 (55.73%) | 53 (9.03%)

Dates with most total detections:
critical: 2019-07-19 (15), high: 2016-09-20 (3,664), medium: 2021-04-22 (186), low: 2016-09-20 (3,777), informational: 2016-08-19 (2,105)

Top 5 computers with most unique detections:
critical: MSEDGEWIN10 (6), IEWIN7 (3), srvdefender01.offsec.lan (2), rootdc1.offsec.lan (2), FS03.offsec.lan (2)
high: MSEDGEWIN10 (119), IEWIN7 (72), FS03.offsec.lan (34), fs03vuln.offsec.lan (29), IE10Win7 (24)
medium: MSEDGEWIN10 (67), IEWIN7 (40), FS03.offsec.lan (17), PC01.example.corp (15), IE10Win7 (15)
low: MSEDGEWIN10 (33), IEWIN7 (16), FS03.offsec.lan (16), fs03vuln.offsec.lan (13), fs01.offsec.lan (11)
informational: MSEDGEWIN10 (18), IEWIN7 (17), fs01.offsec.lan (15), PC01.example.corp (13), IE8Win7 (12)

╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Top critical alerts:                                              Top high alerts:
                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Sticky Key Like Backdoor Usage (10)                               Metasploit SMB Authentication (3,562)               │
│ Active Directory Replication from Non Machine Account (6)         Malicious Svc Possibly Installed (271)              │
│ Meterpreter or Cobalt Strike Getsystem Service Installation (6)   Susp Svc Installed (257)
                  │
│ Defender Alert (Severe) (4)                                       PowerShell Scripts Installed as Services (253)      │
│ WannaCry Ransomware (4)                                           Suspicious Service Installation Script (250)        │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:                                                Top low alerts:
                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ P [...]

2022-11-19 13:06 UTC, YamatoSecurity commented
まだカラーに対応していないのは少し残念ですが、デフォルトでカテゴリごとにオプションが出力されて良いですね！
`--target-file-ext <EVTX_FILE_EXT>  Specify additional target file extensions (ex: evtx_data) (ex: evtx1 evtx2)`等の複数可能のオプションはCargo 3までは分かるように`<EVTX_FILE_EXT>...`だったと思いますが、Clap 4以上では`...`が無くなる感じですか？
(複数可能かどうか区別できた方が良さそうです）

2022-11-20 10:16 UTC, hitenkoku commented
確認してみます。Conflictも発生しているのでそこも直しておきます。

2022-11-21 10:02 UTC, YamatoSecurity commented
<img width="970" alt="Screen Shot 2022-11-21 at 19 01 37" src="https://user-images.githubusercontent.com/71482215/203022007-4a223a60-4de6-4ddb-a613-9c084a00fa63.png">

複数を設定してみたら、エラーが出たので、複数を指定できないっぽいです。

2022-11-21 16:06 UTC, hitenkoku commented
確認ありがとうございます。他の指定方法がないか確認してみます

2022-11-22 15:01 UTC, hitenkoku commented
Vecを指定することで複数の値を取得することは可能のようですので少々お待ちください

2022-11-22 15:51 UTC, hitenkoku commented
@YamatoSecurity  arg_numというのが新しく作られてそちらにまとめられたようです。
arg_numを指定することで以前のように以下のコマンドで問題なく動作することを確認しました。

どちらを採用するのか決めて頂けますでしょうか。

```
>./725.exe -d ..\hayabusa-sample-evtx\ --target-file-ext evtx2  evtx3

...
Analyzing event files: 582
Total file size: 148.5 MB

Loading detections rules. Please wait.

Excluded rules: 14
Noisy rules: 5 (Disabled)

Experimental rules: 1898 (58.96%)
Stable rules: 213 (6.62%)
Test rules: 1108 (34.42%)

Hayabusa rules: 141
Sigma rules: 3078
```

2022-11-23 01:56 UTC, YamatoSecurity requested changes
対応ありがとうございます！
一つだけ：
オプション指定なし、`-u`等々は毎回メモリのデバッグ情報が出力されています。
確認して頂けますか？

2022-11-23 03:32 UTC, hitenkoku commented
@YamatoSecurity  対応完了しました。ご確認下さい

2022-11-23 03:53 UTC, YamatoSecurity approved these changes
LGTM!
ありがとうございました！

2022-11-23 03:53 UTC, merged