Fixed  bug which cannot collect evtx file if enclosed in double quotes when running d at command prompt
Yamato-Security/hayabusa pull request #831
Opened 2022-12-04 16:30 UTC by hitenkoku

## What Changed

- Fixed collect evtx file if enclosed in double quotes when running -d at command prompt.

## Evidence

<details>
<summary>result</summary>

```
 >.\828.exe -d "C:\Users\nexts\opensource\hayabusa-sample-evtx" -o 828.csv　-q
Start time: 2022/12/05 01:29

Analyzing event files: 582
Total file size: 148.5 MB
...
Experimental rules: 1910 (59.11%)
Stable rules: 213 (6.59%)
Test rules: 1108 (34.29%)

Hayabusa rules: 141
Sigma rules: 3090
Total enabled detection rules: 3231

...
Results Summary:

Events with hits / Total events: 19,566 / 76,974 (Data reduction: 57,408 events (74.58%))

Total | Unique detections: 32,874 | 588
Total | Unique critical detections: 46 (0.14%) | 18 (3.06%)
Total | Unique high detections: 6,249 (19.01%) | 266 (45.24%)
Total | Unique medium detections: 1,701 (5.17%) | 176 (29.93%)
Total | Unique low detections: 6,629 (20.16%) | 75 (12.76%)
Total | Unique informational detections: 18,249 (55.51%) | 53 (9.01%)

Dates with most total detections:
critical: 2019-07-19 (15), high: 2016-09-20 (3,664), medium: 2021-04-22 (266), low: 2016-09-20 (3,777), informational: 2016-08-19 (2,105)

Top 5 computers with most unique detections:
critical: MSEDGEWIN10 (6), IEWIN7 (3), FS03.offsec.lan (2), rootdc1.offsec.lan (2), srvdefender01.offsec.lan (2)
high: MSEDGEWIN10 (118), IEWIN7 (72), FS03.offsec.lan (34), fs03vuln.offsec.lan (29), IE10Win7 (24)
medium: MSEDGEWIN10 (67), IEWIN7 (40), FS03.offsec.lan (17), PC01.example.corp (15), IE10Win7 (15)
low: MSEDGEWIN10 (33), IEWIN7 (16), FS03.offsec.lan (16), fs03vuln.offsec.lan (13), fs01.offsec.lan (11)
informational: MSEDGEWIN10 (18), IEWIN7 (17), fs01.offsec.lan (15), PC01.example.corp (13), IE8Win7 (12)
```
</details>

2022-12-05 02:52 UTC, YamatoSecurity commented
念の為、`-f`にも対応できますか？
こちらのWindows 10のコマンドプロンプトではバージョン1.8.1でも`"`で囲んでも無事にロードできたので、お手数をかけますが、検証を @fukusuket にお願いできますか？

2022-12-05 06:00 UTC, hitenkoku commented
@YamatoSecurity @fukusuket 対応が完了しました。ご確認のほどよろしくお願いいたします。

2022-12-05 13:03 UTC, fukusuket requested changes
`-f`は、先にファイル存在チェックがあったので、こちらの前でダブルクォーテーションの削除が必要かと思います！

https://github.com/Yamato-Security/hayabusa/blob/b49d09d1df0a69a1676b7e363ba2b1244a0f5612/src/main.rs#L348-L354

2022-12-05 13:11 UTC, fukusuket commented
@hitenkoku 

以下で`"`を3つ重ねることで([ref:引用符文字を含む引数の受け渡し](https://learn.microsoft.com/ja-jp/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7.3#passing-arguments-that-contain-quote-characters))、疑似的に事象再現と解消を確認できました。 
`-d`はOKでした！`-f`ではまだ事象再現するようで、ご確認いただけますと幸いです🙇
```
PS C:\tmp\hayabusa-1.9.0-dev-win-64-bit> .\hayabusa-1.8.1-win-x64.exe -d """C:\tmp\hayabusa-sample-evtx\\""" -o out.csv

╔╗ ╔╦═══╦╗  ╔╦═══╦══╗╔╗ ╔╦═══╦═══╗
║║ ║║╔═╗║╚╗╔╝║╔═╗║╔╗║║║ ║║╔═╗║╔═╗║
║╚═╝║║ ║╠╗╚╝╔╣║ ║║╚╝╚╣║ ║║╚══╣║ ║║
║╔═╗║╚═╝║╚╗╔╝║╚═╝║╔═╗║║ ║╠══╗║╚═╝║
║║ ║║╔═╗║ ║║ ║╔═╗║╚═╝║╚═╝║╚═╝║╔═╗║
╚╝ ╚╩╝ ╚╝ ╚╝ ╚╝ ╚╩═══╩═══╩═══╩╝ ╚╝
   by Yamato Security

Start time: 2022/12/05 21:54

[ERROR] No .evtx files were found.
PS C:\tmp\hayabusa-1.9.0-dev-win-64-bit> .\hayabusa.exe -d """C:\tmp\hayabusa-sample-evtx\\""" -o out.csv

╔╗ ╔╦═══╦╗  ╔╦═══╦══╗╔╗ ╔╦═══╦═══╗
║║ ║║╔═╗║╚╗╔╝║╔═╗║╔╗║║║ ║║╔═╗║╔═╗║
║╚═╝║║ ║╠╗╚╝╔╣║ ║║╚╝╚╣║ ║║╚══╣║ ║║
║╔═╗║╚═╝║╚╗╔╝║╚═╝║╔═╗║║ ║╠══╗║╚═╝║
║║ ║║╔═╗║ ║║ ║╔═╗║╚═╝║╚═╝║╚═╝║╔═╗║
╚╝ ╚╩╝ ╚╝ ╚╝ ╚╝ ╚╩═══╩═══╩═══╩╝ ╚╝
   by Yamato Security

Start time: 2022/12/05 21:54

Analyzing event files: 580
Total file size: 136.9 MB

Loading detections rules. Please wait.

Excluded rules: 14
```

2022-12-06 00:53 UTC, hitenkoku commented
@fukusuket  ご確認、ご指摘をしていただきありがとうございます。対応完了しました。以下の通りfilepathの時でも動作していることをこちらでも確認しました。

```
>  .\828.exe -f """..\hayabusa-sample-evtx\DeepBlueCLI\disablestop-eventlog.evtx""" -o out.csv -q
Start time: 2022/12/06 09:52

Analyzing event files: 1
Total file size: 69.6 KB

Loading detections rules. Please wait.
...
```

2022-12-06 05:06 UTC, fukusuket approved these changes

2022-12-06 05:07 UTC, fukusuket commented
ありがとうございます🙇 `-f`の修正確認できました、LGTMです！

2022-12-06 05:18 UTC, merged