enhancement separate help menu by commands
Yamato-Security/hayabusa pull request #832
Opened 2022-12-08 04:25 UTC by hitenkoku

## What Changed

- separate help menu by commands 

## Evidence

```
>./656.exe -h
  csv-timeline         Options can be set when outputting
  json-timeline        Options can be set when outputting
  logon-summary        Print a summary of successful and failed logons
  metrics              Print event ID metrics
  pivot-keywords-list  Create a list of pivot keywords
  update-rules         Update to the latest rules in the hayabusa-rules github repository
  level-tuning
  set-default-profile
  list-contributors    Print the list of contributors
  help                 Print this message or the help of the given subcommand(s)

Options:
  -h, --help     Print help information
  -V, --version  Print version information

Advanced:
  -t, --thread-number <NUMBER>    Thread number (default: optimal number for performance)
  -Q, --quiet-errors              Quiet errors mode: do not save error logs
  -c, --rules-config <DIRECTORY>  Specify custom rule config directory (default: ./rules/config)

Display Settings:
      --no-color  Disable color output
  -q, --quiet     Quiet mode: do not display the launch banner
      --debug     Print debug information (memory usage, etc...)
  -v, --verbose   Output verbose information

Other Actions:
      --list-profiles  List the output profiles
 >./656.exe csv-timeline -d ..\all-evtx\ --debug -q -P standard -o 656-csv.csv --no-color > 656-output_result.log
heap stats:    peak      total      freed    current       unit      count
  reserved:    6.3 GiB    6.3 GiB   56.0 MiB    6.2 GiB                        not all freed!
 committed:    4.8 GiB    6.5 GiB    1.6 GiB    4.8 GiB                        not all freed!
     reset:      0          0          0          0                            ok
   touched:  128.5 KiB    2.7 MiB   54.8 GiB  -54.8 GiB                        ok
  segments:     18         22         19          3                            not all freed!
-abandoned:      0          0          0          0                            ok
   -cached:      0          0          0          0                            ok
     pages:      0          0      751.1 Ki  -751.1 Ki                         ok
-abandoned:      0          0          0          0                            ok
 -extended:      0
 -noretire:      0
     mmaps:      0
   commits:    2.2 Ki
   threads:     32         32          0         32                            not all freed!
  searches:     0.0 avg
numa nodes:       1
   elapsed:     470.925 s
   process: user: 3409.312 s, system: 96.875 s, faults: 1260601, rss: 4.7 GiB, commit: 4.9 GiB

> 656-output_result.log
...
Saved file: 656-csv.csv (575.3 MB)
Elapsed time: 00:07:50.899

```

- main
```
PS >./main.exe -d ..\all-evtx\ -o main.csv -P standard -q --no-color  --debug > main-output_result.log
heap stats:    peak      total      freed    current       unit      count
  reserved:    6.1 GiB    6.1 GiB   56.0 MiB    6.1 GiB                        not all freed!
 committed:    4.8 GiB    5.7 GiB  952.1 MiB    4.8 GiB                        not all freed!
     reset:      0          0          0          0                            ok
   touched:  128.5 KiB    2.7 MiB   54.8 GiB  -54.8 GiB                        ok
  segments:     18         22         18          4                            not all freed!
-abandoned:      0          0          0          0
              ok
   -cached:      0          0          0          0
              ok
     pages:      0          0      749.0 Ki  -749.0 Ki
              ok
-abandoned:      0          0          0          0
              ok
 -extended:      0
 -noretire:      0
     mmaps:      0
   commits:    2.0 Ki
   threads:     32         32          0         32
              not all freed!
  searches:     0.0 avg
numa nodes:       1
   elapsed:     297.337 s
   process: user: 3025.718 s, system: 14.265 s, faults: 1269180, rss: 4.7 GiB, commit: 4.9 GiB

> cat main-output_result.log
...
Elapsed time: 00:04:57.326
Saved file: main.csv (575.3 MB)
```

2022-12-08 12:21 UTC, hitenkoku commented
@fukusuket @YamatoSecurity 

ひとまず、既存の機能をサブコマンドにした形になります。configのstatic変数を使わなくしたことにより、テストが書きやすくなりましたが、一方で並列処理のために今までstaticで参照していた情報をArc::cloneしなければならなくなったため処理時間が増える形になりました。こちらでもarc clone等を行わずに対応する方法がないかもう少し検討を行いますが

現状で機能面について問題ないか検証をお願いいたします。

2022-12-08 14:13 UTC, fukusuket commented
@hitenkoku @YamatoSecurity 
実装大変おつかれさまです🙇 トップのメニューとてもすっきりしていいですね🙂
以下細かい点が多く大変恐縮ですが、コメントになります！(見当違いのコメントありましたらご容赦ください🙇)

### トップのHelpメッセージ
1. Usageは`COMMAND`が明記されていると良さそうです、以下イメージです(`cargo`だと↓の感じでした)
```
Usage:
  hayabusa.exe [OPTIONS] [COMMAND]
```
2. timeline系のコマンドヘルプ文言は↓の感じが良いでしょうか🤔
```
  csv-timeline         Save the timeline in CSV format.
  json-timeline        Save the timeline in JSON(L) format.
```

3. 以下コマンドにヘルプがなかったので、↓追記あると良いと思います！
```
  level-tuning 　　　　 Tune alert levels (default: ./rules/config/level_tuning.txt)
  set-default-profile  Set default output profile
```
4. 以下はトップレベルでは表示ないほうがわかりやすいかと思ったのですが、どう思われますかね...？(要表示でしたら本指摘ご放念ください！)
```
Advanced:
...
Display Settings:
...
Other Actions:
...
```

###  サブコマンドのHelpメッセージ
####  json-timeline
以下はCSV formatはないほうがよさそうです！
```
-o, --output <FILE>       Save the timeline in CSV format (ex: results.csv)
```

#### 全体
`--list-profiles`は以下のサブコマンドだと不要かと思ったのですが、いかがでしょうか？🤔
- logon-summary
- metrics
- update-rules
- level-tuning
- list-contributors

2022-12-08 14:47 UTC, hitenkoku commented
ありがとうございます。少し確認してみてみます。文言修正は早めに行いますが、listprofileの除去はstructの構成が変わる可能性があるため確認含めて今週まで時間をください

2022-12-08 14:54 UTC, fukusuket requested changes
実装面LGTMです！ 下記の文言修正をよろしくお願いいたします🙇 
https://github.com/Yamato-Security/hayabusa/pull/832#issuecomment-1342799994

2022-12-09 00:30 UTC, fukusuket commented
@hitenkoku 
コマンドの実動作をpanic有無の観点で確認いたしました！ほとんど〇です💪
×の箇所だけpanicになるようで、お手数おかけしますがご確認いただけますと幸いです🙇

|command | help | デフォルト| デフォルト以外のオプション|
|-------------------| -- | -------------| -------|
|csv-timeline       | 〇 | 〇(`-d -o`)  | 〇(`-t -r -d -o -P -m -H --timeline-start --timeline-end -v -T`)|
|json-timeline      | 〇 | 〇(`-d -o`)  | 〇(`-f -J -o --exclude-status --ISO-8601 --debug`)|
|logon-summary      | 〇 | ×(`-d -o`)  | ×(`-f -o`) |
|update-rules       | 〇 | 〇 | 〇(`--no-color -v`) |
|metrics            | 〇 | ×(`-d`)     | - |
|pivot-keywords-list| 〇 | 〇(`-d -o`)  | - |
|update-rules       | 〇 | 〇 | 〇(`-d`) |
|level-tuning       | 〇  | 〇(`--level-tuning`) | - | 
|set-default-profile| 〇 | ×(`オプションなし`)  | 〇(`--list-profile`) |
|list-contributors  | 〇 | - | - |
|help               | 〇 | - | - |

各コマンド実動作確認できましたので、あと以下2観点のテストにて完了予定です！
- オプション毎の引数渡した時の動作
- 前バージョンと出力比較

2022-12-09 02:02 UTC, YamatoSecurity commented on src/detections/utils.rs
>          return Err("The required rules config files were not found. Please download them with --update-rules".to_string());
`The required rules config files were not found. Please download them with --update-rules`
を
`The required rules and config files were not found. Please download them with the update-rules command.`に変更をお願いします。

2022-12-09 02:12 UTC, YamatoSecurity commented
csv-timelineスキャンの途中でpanicでクラッシュしています:
`Thread 'main' panicked at 'called 'Option::unwrap()' on a 'None' value', src¥timeline¥metrics.rs:138:32`

csv-timeline時にEvent Metricsのコードが使われていますか？

2022-12-09 03:23 UTC, hitenkoku commented
確認します少々お待ちください

2022-12-09 03:32 UTC, hitenkoku commented
おそらくmetricsのフラグチェクの際に漏れたものと思われます。本日修正します

2022-12-09 06:40 UTC, hitenkoku commented on src/detections/utils.rs
>          return Err("The required rules config files were not found. Please download them with --update-rules".to_string());
c3ded42bc01f21c14798aa5c9af45db949b41372 で対応完了しました。

2022-12-09 06:44 UTC, hitenkoku commented
@YamatoSecurity 下記内容ですが、metricsの処理を行う条件分岐がtrue/false逆であったため、metricsの処理が入りpanicが発生していました。

03ba95c588d7869db389769d6e6a37dd3acf2ea1 で対応完了しました。

> csv-timelineスキャンの途中でpanicでクラッシュしています: `Thread 'main' panicked at 'called 'Option::unwrap()' on a 'None' value', src¥timeline¥metrics.rs:138:32`
> 
> csv-timeline時にEvent Metricsのコードが使われていますか？

2022-12-09 10:06 UTC, hitenkoku commented
@fukusuket 表示面のご指摘について対応完了しましたのでご連絡いたします。

> ### トップのHelpメッセージ
> 1. Usageは`COMMAND`が明記されていると良さそうです、以下イメージです(`cargo`だと↓の感じでした)
> 
> ```
> Usage:
>   hayabusa.exe [OPTIONS] [COMMAND]
> ```
> 

https://github.com/Yamato-Security/hayabusa/pull/832/commits/6ae53528c8ced22f8ae6d6917b1ae39ec903b6b8 で対応完了

> 2. timeline系のコマンドヘルプ文言は↓の感じが良いでしょうか🤔
> 
> ```
>   csv-timeline         Save the timeline in CSV format.
>   json-timeline        Save the timeline in JSON(L) format.
> ```
> 
> 3. 以下コマンドにヘルプがなかったので、↓追記あると良いと思います！
> 
> ```
>   level-tuning 　　　　 Tune alert levels (default: ./rules/config/level_tuning.txt)
>   set-default-profile  Set default output profile
> ```

https://github.com/Yamato-Security/hayabusa/pull/832/commits/dbab6d3ea6ec899067c4d1ca51e083e02eaf4436 で対応完了

> 
> 4. 以下はトップレベルでは表示ないほうがわかりやすいかと思ったのですが、どう思われますかね...？(要表示でしたら本指摘ご放念ください！)
> 
> ```
> Advanced:
> ...
> Display Settings:
> ...
> Other Actions:
> ...
> ```
> 

https://github.com/Yamato-Security/hayabusa/pull/832/commits/dbab6d3ea6ec899067c4d1ca51e083e02eaf4436 で対応完了


> ### サブコマンドのHelpメッセージ
> #### json-timeline
> 以下はCSV formatはないほうがよさそうです！
> 
> ```
> -o, --output <FILE>       Save the timeline in CSV format (ex: results.csv)
> ```

https://github.com/Yamato-Security/hayabusa/pull/832/commits/3120d1e1314da49fb799a3a8d9d98f53ba578042　で対応完了

> 
> #### 全体
> `--list-profiles`は以下のサブコマンドだと不要かと思ったのですが、いかがでしょうか？🤔
> 
> * logon-summary
> * metrics
> * update-rules
> * level-tuning
> * list-contributors

csv-timelineとjson-timeline以外は使わないため、その2つ以外は指定できないように  https://github.com/Yamato-Security/hayabusa/pull/832/commits/c69c3242e62d8032036184d26487a553add1cf5a で修正

2022-12-09 14:58 UTC, hitenkoku commented
@fukusuket ドキュメントの修正と以下でご指摘いただきました内容で☓の箇所のバグを修正いたしました。何度もご確認をお願いして申し訳ございませんがご確認のほどよろしくお願いいたします。

> @hitenkoku コマンドの実動作をpanic有無の観点で確認いたしました！ほとんど〇です💪 ×の箇所だけpanicになるようで、お手数おかけしますがご確認いただけますと幸いです🙇
> 
> command	help	デフォルト	デフォルト以外のオプション
> csv-timeline	〇	〇(`-d -o`)	〇(`-t -r -d -o -P -m -H --timeline-start --timeline-end -v -T`)
> json-timeline	〇	〇(`-d -o`)	〇(`-f -J -o --exclude-status --ISO-8601 --debug`)
> logon-summary	〇	×(`-d -o`)	×(`-f -o`)
> update-rules	〇	〇	〇(`--no-color -v`)
> metrics	〇	×(`-d`)	-
> pivot-keywords-list	〇	〇(`-d -o`)	-
> update-rules	〇	〇	〇(`-d`)
> level-tuning	〇	〇(`--level-tuning`)	-
> set-default-profile	〇	×(`オプションなし`)	〇(`--list-profile`)
> list-contributors	〇	〇	-
> help	〇	-	-
> 各コマンド実動作確認できましたので、あと以下2観点にてこちらのテストは完了予定です！
> 
> * オプション毎の引数渡した時の動作
> * 前バージョンと出力比較

2022-12-09 15:35 UTC, fukusuket commented
早々に実装いただきありがとうございます🙇 確認いたします！

2022-12-10 00:52 UTC, YamatoSecurity commented
CSVスキャンのベンチマークを取りました。検知数もファイルサイズも一緒で機能的には問題ないと思いますが、確かに約18%遅くなっています。(33分 -> 39分)
@fukusuket Cloneを使わない方法ないですかね？ (ChatGPTに聞いてみましょうか？ww)
メモリ使用はあまり変わっていないようです。

mainブランチ: 
```
Events with hits / Total events: 2,722,116 / 14,238,721 (Data reduction: 11,516,605 events (80.88%))

Total | Unique detections: 4,004,135 | 745
Total | Unique critical detections: 99 (0.00%) | 17 (2.28%)
Total | Unique high detections: 511,327 (12.77%) | 301 (40.40%)
Total | Unique medium detections: 185,607 (4.64%) | 248 (33.29%)
Total | Unique low detections: 1,198,841 (29.94%) | 102 (13.69%)
Total | Unique informational detections: 2,108,261 (52.65%) | 77 (10.34%)

Elapsed time: 00:33:01.379
Saved file: test-secret-main.csv (1.3 GB)

HTML report: test-secret-main.html

Memory usage stats:
heap stats:    peak      total      freed    current       unit      count
  reserved:    8.9 GiB    8.9 GiB  164.0 MiB    8.8 GiB                        not all freed!
 committed:    8.1 GiB   14.0 GiB    6.0 GiB    8.0 GiB                        not all freed!
     reset:      0          0          0          0                            ok
   touched:  128.5 KiB    3.2 MiB  321.3 GiB -321.3 GiB                        ok
  segments:     19         26         20          6                            not all freed!
-abandoned:      0          0          0          0                            ok
   -cached:      0          0          0          0                            ok
     pages:      0          0        3.0 Mi    -3.0 Mi                         ok
-abandoned:      0          0          0          0                            ok
 -extended:      0
 -noretire:      0
     mmaps:      0
   commits:    3.4 Ki
   threads:     16         16          0         16                            not all freed!
  searches:     0.0 avg
numa nodes:       1
   elapsed:    1981.386 s
   process: user: 14011.328 s, system: 48.640 s, faults: 2383524, rss: 8.0 GiB, commit: 8.2 GiB
```

656ブランチ:
```
Results Summary:

Events with hits / Total events: 2,722,116 / 14,238,721 (Data reduction: 11,516,605 events (80.88%))

Total | Unique detections: 4,004,135 | 745
Total | Unique critical detections: 99 (0.00%) | 17 (2.28%)
Total | Unique high detections: 511,327 (12.77%) | 301 (40.40%)
Total | Unique medium detections: 185,607 (4.64%) | 248 (33.29%)
Total | Unique low detections: 1,198,841 (29.94%) | 102 (13.69%)
Total | Unique informational detections: 2,108,261 (52.65%) | 77 (10.34%)

Saved file: test-secret-2.csv (1.3 GB)
HTML report: test-secret-2.html
Elapsed time: 00:39:03.632
Errors were generated. Please check ./logs/errorlog-20221210_093754.log for details.


Memory usage stats:
heap stats:    peak      total      freed    current       unit      count
  reserved:    9.0 GiB    9.0 GiB  164.0 MiB    8.9 GiB                        not all freed!
 committed:    8.3 GiB   14.8 GiB    6.5 GiB    8.2 GiB                        not all freed!
     reset:      0          0          0          0                            ok
   touched:  128.5 KiB    3.1 MiB  321.6 GiB -321.6 GiB                        ok
  segments:     19         25         22          3                            not all freed!
-abandoned:      0          0          0          0                            ok
   -cached:      0          0          0          0                            ok
     pages:      0          0        3.0 Mi    -3.0 Mi                         ok
-abandoned:      0          0          0          0                            ok
 -extended:      0
 -noretire:      0
     mmaps:      0
   commits:    3.7 Ki
   threads:     16         16          0         16                            not all freed!
  searches:     0.0 avg
numa nodes:       1
   elapsed:    2343.637 s
   process: user: 15318.218 s, system: 499.593 s, faults: 2365869, rss: 8.1 GiB, commit: 8.4 GiB
```

2022-12-10 04:42 UTC, hitenkoku commented
並列処理をするときにArcを使っているのですが、そのときにcloneをせざるを得ない状態に形になっています。
(今まではそれをstatic変数で読み込むように対応していたのでcloneの必要がなかった)

staticの変数を使ってなるべくcloneが発生しないようにしてみます

2022-12-10 05:14 UTC, fukusuket commented
> @fukusuket Cloneを使わない方法ないですかね？ (ChatGPTに聞いてみましょうか？ww)

@YamatoSecurity 
お力になれずすみません！まったくノーアイディアなのですがw  
こちらでもボトルネックになりそうな箇所という観点で調査してみます🔍

2022-12-10 05:33 UTC, hitenkoku commented
@YamatoSecurity  Arc::cloneをしないようにstatic変数で一部バイパスするように以下のcommitで行いました。お手数ですがご確認いただけますでしょうか。cargo testは問題なく通ることは確認済みです。

https://github.com/Yamato-Security/hayabusa/pull/832/commits/df2cbe1cc5d7f05f70e78624f554a455d7ba0195

2022-12-10 13:10 UTC, fukusuket approved these changes

2022-12-10 13:19 UTC, YamatoSecurity commented
@hitenkoku 対応、ありがとうございます！
最新のコミットを確認しましたが、１回目が38分で少しだけ早くなりましたが、２回目はまた39分でした。
今思い出しましたが、チェーンソーもサブコマンドを使っているので、もしかして参考にできるかも知れません。

2022-12-10 13:31 UTC, fukusuket commented on README-Japanese.md
> +  -J, --jsonl               JSONL形式でdタイムラインを保存する (ex: -J -o results.jsonl)
>JSONL形式でdタイムラインを
不要なdがあるので、削除をよろしくお願いいたします！

2022-12-10 13:35 UTC, hitenkoku commented
@YamatoSecurity  chainsawを確認してみましたが、サブコマンドの設定方法自体はstructを利用していますので同じ方法であることを確認しました。

原因として考えられるのはdetection周りのstatic変数を利用していたところを引数で対応しているのですが、そこの引き渡しが現状stored_configというまとまったデータを渡している形になるので、それを修正してみます

2022-12-10 13:39 UTC, fukusuket requested changes
https://github.com/Yamato-Security/hayabusa/blob/656-enhancement-separate-help-menu-by-commands/README-Japanese.md?plain=1#L728

>`-p`もしくは`--pivot-keywords-list`オプションを使うことで

`pivot-keywords-list` コマンドに変更よろしくお願いいたします！

2022-12-10 13:56 UTC, hitenkoku commented
@fukusuket コメントありがとうございます。こちらでもう少し確認して修正したものを https://github.com/Yamato-Security/hayabusa/pull/832/commits/264ea573ef9330e9bc1ed7499b8e20c325fe717e でpushしましたのでご確認をお願いいたします。

> https://github.com/Yamato-Security/hayabusa/blob/656-enhancement-separate-help-menu-by-commands/README-Japanese.md?plain=1#L728
> 
> > `-p`もしくは`--pivot-keywords-list`オプションを使うことで
> 
> `pivot-keywords-list` コマンドに変更よろしくお願いいたします！

2022-12-10 14:07 UTC, fukusuket approved these changes
LGTMです！！早々にありがとうございます🙇

2022-12-10 14:16 UTC, hitenkoku commented
@YamatoSecurity  以下のコミットで検知用の関数に渡す引数を最小限に変更しました。こちらでも確認をしてみますが、ご確認のほどよろしくお願いいたします。

https://github.com/Yamato-Security/hayabusa/pull/832/commits/c9e2b7d5fbcdc1cb7e0979a33d99abfb0971d455

2022-12-10 14:21 UTC, hitenkoku commented on README-Japanese.md
> +  -J, --jsonl               JSONL形式でdタイムラインを保存する (ex: -J -o results.jsonl)
e7d08ad94442919c633840b6c00248c884a6896d で対応完了しました。

2022-12-10 14:25 UTC, hitenkoku commented
今後の処理時間解析のためにもdebug機能の一環でセットしたタイマーで処理したいところの時間をprintするようにしたいと思いますがいかがでしょうか。

大まかに以下の条件が取れればよいかと思っています。

- ルールの読み込み時間
- 検知開始から検知完了までの時間
- 検知終了から出力完了までの時間

2022-12-10 14:27 UTC, fukusuket approved these changes

2022-12-11 03:57 UTC, hitenkoku commented
以下の機能の実装を https://github.com/Yamato-Security/hayabusa/pull/832/commits/9b22a7fbe48babf52384eb7155d63eaa2f0dbf5a で完了しました


> 今後の処理時間解析のためにもdebug機能の一環でセットしたタイマーで処理したいところの時間をprintするようにしたいと思いますがいかがでしょうか。
> 
> 大まかに処理時間が取れればよいかと思っています。
> 
> * ルールの読み込み時間
> * 検知開始から検知完了までの時間
> * 検知終了から出力完了までの時間

2022-12-11 05:32 UTC, YamatoSecurity commented
> 以下の機能の実装を [9b22a7f](https://github.com/Yamato-Security/hayabusa/commit/9b22a7fbe48babf52384eb7155d63eaa2f0dbf5a) , [8de278d](https://github.com/Yamato-Security/hayabusa/commit/8de278d8c8ccc396d4f9f7d7d28630e562052f99) で完了しました
> 
> > 今後の処理時間解析のためにもdebug機能の一環でセットしたタイマーで処理したいところの時間をprintするようにしたいと思いますがいかがでしょうか。
> > 大まかに処理時間が取れればよいかと思っています。
> > 
> > * ルールの読み込み時間
> > * 検知開始から検知完了までの時間
> > * 検知終了から出力完了までの時間

より細かく時間計測ができて良いですね！

2022-12-11 10:37 UTC, hitenkoku commented
@YamatoSecurity  https://github.com/Yamato-Security/hayabusa/pull/832/commits/d70d7d2e08e9113b4b55a8468ddbf85097c83107 でクローンの位置を変えたら以下の通り多少速度が改善しました。ご確認音ほどよろしくお願いいたします。

6.1GBのevtxファイル類を読み込んだ際の結果

<details>
<summary> 8de278d8c8ccc396d4f9f7d7d28630e562052f99 (修正前)</summary>

``` bash
Saved file: c9e2b7d-4.csv (575.3 MB)
Elapsed time: 00:08:11.815
Rule Parse Processing Time: 00:00:03.037
Analysis Processing Time: 00:07:54.241
Output Processing Time: 00:00:14.535

Memory usage stats:
heap stats:    peak      total      freed    current       unit      count
  reserved:    6.3 GiB    6.3 GiB   56.0 MiB    6.2 GiB                        not all freed!
 committed:    4.9 GiB    7.0 GiB    2.1 GiB    4.8 GiB                        not all freed!
     reset:      0          0          0          0                            ok
   touched:  128.5 KiB    2.5 MiB   54.4 GiB  -54.4 GiB                        ok
  segments:     18         20         16          4                            not all freed!
-abandoned:      0          0          0          0                            ok
   -cached:      0          0          0          0                            ok
     pages:      0          0      733.5 Ki  -733.5 Ki                         ok
-abandoned:      0          0          0          0                            ok
 -extended:      0
 -noretire:      0
     mmaps:      0
   commits:    2.3 Ki
   threads:     32         32          0         32                            not all freed!
  searches:     0.0 avg
numa nodes:       1
   elapsed:     491.834 s
   process: user: 3185.640 s, system: 75.796 s, faults: 1310856, rss: 4.7 GiB, commit: 4.9 GiB
```

</details>


<details>
<summary> d70d7d2e (修正後)</summary>

```
....
Saved file: d70d7d2e.csv (575.3 MB)
Elapsed time: 00:07:39.485
Rule Parse Processing Time: 00:00:02.393
Analysis Processing Time: 00:07:26.000
Output Processing Time: 00:00:11.090

Memory usage stats:
heap stats:    peak      total      freed    current       unit      count
  reserved:    6.3 GiB    6.3 GiB   56.0 MiB    6.2 GiB                        not all freed!
 committed:    4.9 GiB    6.5 GiB    1.6 GiB    4.8 GiB                        not all freed!
     reset:      0          0          0          0                            ok
   touched:  128.5 KiB    2.5 MiB   54.8 GiB  -54.8 GiB                        ok
  segments:     18         20         15          5                            not all freed!
-abandoned:      0          0          0          0                            ok
   -cached:      0          0          0          0                            ok
     pages:      0          0      748.5 Ki  -748.5 Ki                         ok
-abandoned:      0          0          0          0                            ok
 -extended:      0
 -noretire:      0
     mmaps:      0
   commits:    2.1 Ki
   threads:     32         32          0         32                            not all freed!
  searches:     0.0 avg
numa nodes:       1
   elapsed:     459.503 s
   process: user: 3217.640 s, system: 79.015 s, faults: 1308947, rss: 4.7 GiB, commit: 4.9 GiB
```
</details>

2022-12-12 01:48 UTC, YamatoSecurity commented
@hitenkoku いつも対応ありがとうございます！
何回か再確認しましたが、まだこちらではあまり速度が変わっていません。
まだ1.8.1の方が約20%速いです。
なんででしょう。。

2022-12-12 04:53 UTC, YamatoSecurity commented
@hitenkoku すみません、速度の件とまた別ですが、以下をお願いできますか？
1. 今までのように引数なしの場合は、ヘルプメニューの上にロゴの出力
2. 引数なしのヘルプメニューの`Options`内の`--no-color`と`-q, --quiet`以外のオプションの削除
(理由: 他のオプションはスキャン時に使うオプションで、`-h`のヘルプオプションは特に追加の情報が出力されないので不要で、バージョン情報がデフォルトで出力されているので、それも不要です）
3. list-profilesのコマンドの追加。(すみません、`--list-profile`のオプションを作る前にサブコマンドの概要を書いたので、このコマンドが漏れていたと思います）
4. コマンドの引数が無い場合はヘルプメニューを出力する（例: `hayabusa.exe csv-timeline`)
5. csv-timelineとオプションから`Other-Actions`の`--set-default-profile`と`--list-profiles`は不要のため、削除
6. Update-rulesのオプションから`-t, --thread-number`の削除？これってマルチスレッド対象外ですよね？
7. pivot-keywords-listの`-o`の説明`Save pivot words to seperate files (ex: pivot-keywords)`を`Save pivot words to separate files (ex: pivot-keywords.txt)`に変更 (`seperate`->`separate`、`pivot-keywords`->`pivot-keywords.txt`)
8. `level-tuning`と`set-default-profile`の次のオプションの削除: `-t, --thread-number`, `-Q, --quiet-errors`, `--debug` (対象外ですよね？）
9. `level-tuning`で`[<FILE>]`(例: `./rules/config/level_tuning.txt`)を指定した時に、`error: Found argument './rules/config/level_tuning.txt' which wasn't expected, or isn't valid in this context`というエラーになります。`-f, --file`のオプションを作った方が楽でしたら、`[<FILE>]`の代わりに`-f`オプションの追加でも良いと思います。
10. `help                 Print this message or the help of the given subcommand(s)`を`help [COMMAND]                Print this message or the help of the given subcommand(s)`に変更できますか？

2022-12-12 08:38 UTC, YamatoSecurity commented
毎回csv-timeline等を書くのが少し手間なので、以下のshorthandを追加するのはどうですか？
```
c, csv-timeline         Save the timeline in CSV format
j, json-timeline        Save the timeline in JSON/JSONL format
l, logon-summary        Print a summary of successful and failed logons
m, metrics              Print event ID metrics
p, pivot-keywords-list  Create a list of pivot keywords
u, update-rules         Update to the latest rules in the hayabusa-rules github repository
l, list-profiles          Show the available profiles
t, level-tuning         Tune alert levels (default: ./rules/config/level_tuning.txt)
d, set-default-profile  Set default output profile
list-contributors    Print the list of contributors
```

2022-12-12 09:58 UTC, hitenkoku commented
https://github.com/Yamato-Security/hayabusa/pull/832/commits/8801a9724220f95998e49959bf204243fc39f0e4 で対応完了。基本Commandは大文字になるように修正しました。また、optionで衝突しているものがあるので以下の通り修正しました。

-P --profile -> -p --profile
-U --utc -> -u --utc
-T --visualize-timeline -> -t --visualize-timeline
-J --jsonl -> -j --jsonl
-t --thread-number -> -h --thread-number


> 毎回csv-timeline等を書くのが少し手間なので、以下のshorthandを追加するのはどうですか？
> 
> ```
> C, csv-timeline         Save the timeline in CSV format
> J, json-timeline        Save the timeline in JSON/JSONL format
> S, logon-summary        Print a summary of successful and failed logons
> M, metrics              Print event ID metrics
> P, pivot-keywords-list  Create a list of pivot keywords
> U, update-rules         Update to the latest rules in the hayabusa-rules github repository
> L. list-profiles          Show the available profiles
> T, level-tuning         Tune alert levels (default: ./rules/config/level_tuning.txt)
> D, set-default-profile  Set default output profile
> list-contributors    Print the list of contributors
> ```

2022-12-12 10:43 UTC, hitenkoku commented
> 
> 1. 今までのように引数なしの場合は、ヘルプメニューの上にロゴの出力
https://github.com/Yamato-Security/hayabusa/pull/832/commits/7af3bd494b72d718077a38e683300a484ca604ad で対応


> 2. 引数なしのヘルプメニューの`Options`内の`--no-color`と`-q, --quiet`以外のオプションの削除
>    (理由: 他のオプションはスキャン時に使うオプションで、`-h`のヘルプオプションは特に追加の情報が出力されないので不要で、バージョン情報がデフォルトで出力されているので、それも不要です）
> 3. list-profilesのコマンドの追加。(すみません、`--list-profile`のオプションを作る前にサブコマンドの概要を書いたので、このコマンドが漏れていたと思います）
> 4. コマンドの引数が無い場合はヘルプメニューを出力する（例: `hayabusa.exe csv-timeline`)
> 5. csv-timelineとオプションから`Other-Actions`の`--set-default-profile`と`--list-profiles`は不要のため、削除
> 6. Update-rulesのオプションから`-t, --thread-number`の削除？これってマルチスレッド対象外ですよね？
> 7. pivot-keywords-listの`-o`の説明`Save pivot words to seperate files (ex: pivot-keywords)`を`Save pivot words to separate files (ex: pivot-keywords.txt)`に変更 (`seperate`->`separate`、`pivot-keywords`->`pivot-keywords.txt`)
> 8. `level-tuning`と`set-default-profile`の次のオプションの削除: `-t, --thread-number`, `-Q, --quiet-errors`, `--debug` (対象外ですよね？）
> 9. `level-tuning`で`[<FILE>]`(例: `./rules/config/level_tuning.txt`)を指定した時に、`error: Found argument './rules/config/level_tuning.txt' which wasn't expected, or isn't valid in this context`というエラーになります。`-f, --file`のオプションを作った方が楽でしたら、`[<FILE>]`の代わりに`-f`オプションの追加でも良いと思います。
> 10. `help                 Print this message or the help of the given subcommand(s)`を`help [COMMAND]                Print this message or the help of the given subcommand(s)`に変更できますか？

2022-12-12 13:01 UTC, YamatoSecurity commented
> あ、すみません、サブコマンドのshorthandはオプション(例: `-C`)ではなくて、`c`か`C`にできますか？(`c`は`csv-timeline`のリンクのような感じ）`-C`だとオプションのように見えてしまうので、ユーザが混乱しそうです。また、`-C -h`のようにヘルプ画面が出なかったりします。難しい場合はshorthandなしでもOKです。

昔、あるRustプログラムがサブコマンドの省略にも対応していると思ったら、調べてみたら、shortはオプションのみのようですよね？であれば、サブコマンドはフルで仕方ないですね。折角オプションを実装して下さったのに申し訳ありません。

2022-12-12 22:18 UTC, YamatoSecurity commented
度々すみません。思い出しました。cargoのヘルプメニュー(`build, b`等々)でした:

<img width="741" alt="cargo" src="https://user-images.githubusercontent.com/71482215/207166728-4d5e67f0-d61b-4718-83cd-144310246472.png">

CargoもClap 4を使っているようなので、参考にできるかも？

2022-12-13 00:23 UTC, hitenkoku commented
> > [8801a97](https://github.com/Yamato-Security/hayabusa/commit/8801a9724220f95998e49959bf204243fc39f0e4) で対応完了。基本Commandは大文字になるように修正しました。また、optionで衝突しているものがあるので以下の通り修正しました。
> 
> あ、すみません、サブコマンドのshorthandはオプション(例: `-C`)ではなくて、`c`か`C`にできますか？(`c`は`csv-timeline`のリンクのような感じ）`-C`だとオプションのように見えてしまうので、ユーザが混乱しそうです。また、`-C -h`のようにヘルプ画面が出なかったりします。難しい場合はshorthandなしでもOKです。
> 

-の削除はできません。その場合はCsv-timelineではなくCという構造体を持たなければいけなくなります。shorthandは削除するということで承りました。戻します

> 因みに、`hayabusa.exe -q`はロゴなしでヘルプ画面が出るはずですが、panicで終了しています。

2022-12-13 00:39 UTC, hitenkoku commented
cargoで利用しているのはhelp_templateというところに直接ハードコードする形になります。一応試してみますが、cargoよりも多層で利用しているためうまくいくかは保証しかねます

> 度々すみません。思い出しました。cargoのヘルプメニュー(`build, b`等々)でした:
> 
> <img alt="cargo" width="741" src="https://user-images.githubusercontent.com/71482215/207166728-4d5e67f0-d61b-4718-83cd-144310246472.png">
> 
> CargoもClap 4を使っているようなので、参考にできるかも？

2022-12-13 08:28 UTC, hitenkoku commented
こちらも言い方が悪くなってしまい申し訳ございません。

cargoのほうを確認したところcago build をcargo bとするところの処理はそれなりに複雑ではありますができなくはないです。ただ、利用している方法が、外部のサブコマンド(clapで指定していないもの)を許可する設定をした上で、他のソースコードで得られたデータをもとに振り分けしていく方法となります

ref: https://github.com/rust-lang/cargo/blob/f5cdfa4d8bde8b25cb1f020632a921f4190a7c58/src/bin/cargo/main.rs#L40-L83

help_templateではトップのヘルプ内容と、サブコマンドのヘルプ内容は変更することができることが確認できました。これを対応するとトップのヘルプ内容でのコマンド及びオプションはハードコートで記載する必要が出てきますがいかがしましょうか

2022-12-13 08:50 UTC, YamatoSecurity commented
cargoの確認ありがとうございます！
どこまで大変かこちらでは分からないので、ご意見を聞きたいところですが、それなり複雑でできなくはないという感じのであれば、やめた方が良さそうですよね？ ヘルプメニューをカスタムでハードコードしないと、修正できないのは以下のhelp説明だけですか？

`help Print this message or the help of the given subcommand(s)`

それだけであれば、毎回ハードコードの修正が手間かかって、記載ミス等の可能性もあるので、ハードコードしない方が管理しやすいですよね？

2022-12-13 08:57 UTC, hitenkoku commented
ヘルプメニューをカスタムで変更しないと対応できなさそうなのは以下の2つですね。

- cargoのようにCsv-timeline c のような使い方をする場合にhelpの文面も変更が必要
  - これはclapのallow_external_subcommand機能を利用しますが、clap側の方に以下のように書かれています。今までclapで管理していたもの以外はエラーとして取り扱ってくれていたものを一部除外する流れとなるため今までclapでやっていた処理をcargoのようにhayabusaで書く必要が出てきます
  
  > NOTE: Use this setting with caution, as a truly unexpected argument (i.e. one that is NOT an external subcommand) will not cause an error and instead be treated as a potential subcommand. One should check for such cases manually and inform the user appropriately.

-  helpの文面

2022-12-13 11:09 UTC, YamatoSecurity commented
なるほど、では今回はcargoのように`csv-timeline, c`をなしにして、`csv-timeline`等でハードコードせずにしましょう。

2022-12-13 16:06 UTC, hitenkoku commented
指摘事項の個所の修正を直すまで誤ってマージしないようにするためdraftに変更しました

2022-12-14 13:06 UTC, hitenkoku commented
@YamatoSecurity 以下の件について、現在の形ですと ./hayabusa.exe level-tuning --level-tuning ./rules/config/level_tuning.txt でエラーなく実行できます。念のためどのようなコマンドを入力したのかお教えいただけますでしょうか。

./hayabusa.exe level-tuning だけでも./rules/config/level_tuning.txtを確認しに生きます。

> 9. level-tuningで[<FILE>](例: ./rules/config/level_tuning.txt)を指定した時に、error: Found argument './rules/config/level_tuning.txt' which wasn't expected, or isn't valid in this contextというエラーになります。-f, --fileのオプションを作った方が楽でしたら、[<FILE>]の代わりに-fオプションの追加でも良いと思います。

2022-12-14 13:43 UTC, hitenkoku commented
@YamatoSecurity 追加の質問になりますが、以下の指摘について、--debugは現在すべてのコマンドで入力されたらメモリ利用量を表示してくれるようになっていますが削除しますか？そもそもdebugなのでこのオプション自体を非表示にしてしまってもよいと思っていますがいかがでしょうか。

> level-tuningとset-default-profileの次のオプションの削除: -t, --thread-number, -Q, --quiet-errors, --debug (対象外ですよね？）

2022-12-14 13:49 UTC, hitenkoku commented
https://github.com/Yamato-Security/hayabusa/pull/832#issuecomment-1346195161 のrevertは https://github.com/Yamato-Security/hayabusa/pull/832/commits/775197ede9bac26643a57dcd0e33ac41258cbfe8 で対応済み

2022-12-14 15:39 UTC, hitenkoku commented
@YamatoSecurity  指摘事項はすべて修正しました。以下2点についてご確認をお願い致します。

- https://github.com/Yamato-Security/hayabusa/pull/832#issuecomment-1351376512
- https://github.com/Yamato-Security/hayabusa/pull/832#issuecomment-1351322268

2022-12-15 08:11 UTC, YamatoSecurity commented
@hitenkoku 
対応、ありがとうございます！凄く良い感じです。あと少しだけ細かいところをお願いしたいです。度々すみません。

まず、こちらで以下の修正を行いました:
1. csv-timelineのオプション修正:
`-O, --thread-number` -> `-t, --thread-number`
`Directory of mul``tiple .evtx files` -> `Directory of multiple .evtx files`
`-P, --profile` -> `-p, --profile` (--pivot-keywordsがコマンドになったため）
2. `level-tuning`の`--level-tuning`オプションが`Other Actions:`になっていたので、`Options`になるようにしました。

コミットをご確認下さい。

以下の確認をお願いできますか？
1. `--debug`オプションは確かに開発メンバーしか普段使わないから、メニューから消しましょう。
2. コマンドのヘルプメニューにExamples:を追加できますか？あった方が分かりやすいかも。
3. 細かいところなので、修正しなくても良いかもしれませんが、引数なしでコマンドを入力すると(例: hayabusa.exe csv-timeline) ヘルプメニューに上に`Start time: xxxx`が表示されます。
4. `./target/release/hayabusa update-rules -r test-rules` でtest-rulesディレクトリが存在しない場合はpanicします。"Directory does not exist"というエラーが出るので、問題は分かると思います。修正が手間だったら、このままでも大丈夫だと思います。
5. `./target/release/hayabusa set-default-profile`を実行したら、「Successfully updated the default profile.」が表示されます。`-p, --profile`を指定する必要があるので、引数なしの場合はcsv-timeline等のようにヘルプメニューを出したいです。そして、`-p`が必要だと分かるように`Usage: hayabusa.exe set-default-profile --profile <PROFILE>`にしたいですが、可能ですか？
6. hayabusa.exe help level-tuningのヘルプメニューでUsageを`Usage: hayabusa.exe level-tuning\n  hayabusa.exe level-tuning --level-tuning <FILE>`にできますか？　`level-tuning`を２回書かないといけないので、`hayabusa.exe level-tuning -f <FILE>`の方が分かりやすそうですが、`-f`は他のコマンドで使っているので、難しいでしょうか？
7. OPTIONSなしの`level-tuning`コマンドはデフォルトの設定ファイルを使うので、`--level-tuning`オプションはファイルを指定する場合だけすよね？そうすると、`[<FILE>]`ではなくて、`<FILE>`が正しいですよね？
8. `./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -p hogehoge `のように存在しないプロファイルを指定した場合、その後にロゴとStart timeが表示されます。

2022-12-17 08:59 UTC, hitenkoku commented
> 
> まず、こちらで以下の修正を行いました:
> 
> 1. csv-timelineのオプション修正:
>    `-O, --thread-number` -> `-t, --thread-number`
>    `` Directory of mul``tiple .evtx files `` -> `Directory of multiple .evtx files`
>    `-P, --profile` -> `-p, --profile` (--pivot-keywordsがコマンドになったため）
> 2. `level-tuning`の`--level-tuning`オプションが`Other Actions:`になっていたので、`Options`になるようにしました。
> 
> コミットをご確認下さい。

ご対応ありがとうございます。上記の内容を確認しました。問題ないと思います

> 
> 以下の確認をお願いできますか？
> 
> 1. `--debug`オプションは確かに開発メンバーしか普段使わないから、メニューから消しましょう。
4e687dad88d63a9907b33996d161f142f1b2ad28 で対応済み

> 2. コマンドのヘルプメニューにExamples:を追加できますか？あった方が分かりやすいかも。
<対応中>

> 3. 細かいところなので、修正しなくても良いかもしれませんが、引数なしでコマンドを入力すると(例: hayabusa.exe csv-timeline) ヘルプメニューに上に`Start time: xxxx`が表示されます。
<対応中>

> 4. `./target/release/hayabusa update-rules -r test-rules` でtest-rulesディレクトリが存在しない場合はpanicします。"Directory does not exist"というエラーが出るので、問題は分かると思います。修正が手間だったら、このままでも大丈夫だと思います。
<対応中>

> 5. `./target/release/hayabusa set-default-profile`を実行したら、「Successfully updated the default profile.」が表示されます。`-p, --profile`を指定する必要があるので、引数なしの場合はcsv-timeline等のようにヘルプメニューを出したいです。そして、`-p`が必要だと分かるように`Usage: hayabusa.exe set-default-profile --profile <PROFILE>`にしたいですが、可能ですか？
<対応中>

> 6. hayabusa.exe help level-tuningのヘルプメニューでUsageを`Usage: hayabusa.exe level-tuning\n  hayabusa.exe level-tuning --level-tuning <FILE>`にできますか？　`level-tuning`を２回書かないといけないので、`hayabusa.exe level-tuning -f <FILE>`の方が分かりやすそうですが、`-f`は他のコマンドで使っているので、難しいでしょうか？
<対応中>

> 7. OPTIONSなしの`level-tuning`コマンドはデフォルトの設定ファイルを使うので、`--level-tuning`オプションはファイルを指定する場合だけすよね？そうすると、`[<FILE>]`ではなくて、`<FILE>`が正しいですよね？
<対応中>

> 8. `./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -p hogehoge `のように存在しないプロファイルを指定した場合、その後にロゴとStart timeが表示されます。

<対応中>

2022-12-17 11:25 UTC, hitenkoku commented
@YamatoSecurity 以下の指摘ですが、どこの部分に出したいでしょうか。

今だと、トップのヘルプ(./hayabusa.exe helpと打ったときの内容)と各コマンドのヘルプ./hayabusa.exe help csv-timelineと打ったときの内容)の2つのパターンがあります。

あとは何を出したいのか指定してください。どういうコマンドを表示したいのかを提示してもらえると確認がスムーズになります。

> コマンドのヘルプメニューにExamples:を追加できますか？あった方が分かりやすいかも。

2022-12-17 21:27 UTC, YamatoSecurity commented
> @YamatoSecurity 以下の指摘ですが、3点確認させてください。

確かにUsageを読めば分かるはずなので、Examplesを無しにしましょうか。`<INPUT>`が必要であることだけを伝えたいので、Usageの以下の変更をお願いできますか？
`Usage: csv-timeline [OPTIONS]` -> `Usage: csv-timeline <INPUT> [OPTIONS]`
`Usage: json-timeline [OPTIONS]` -> `Usage: json-timeline <INPUT> [OPTIONS]`
`Usage: logon-summary [OPTIONS]` -> `Usage: logon-summary <INPUT> [OPTIONS]`
`Usage: metrics [OPTIONS]` -> `Usage: metrics <INPUT> [OPTIONS]`
`Usage: pivot-keywords-list [OPTIONS]` -> `Usage: pivot-keywords-list <INPUT> [OPTIONS]`

2022-12-17 21:55 UTC, YamatoSecurity commented
すみません、デフォルトのヘルプメニューのUsageではバイナリ名が使われているので、`help_template`と`override_usage`でハードコードすると、Hayabusaのファイル名がバラバラになってしまいます。デフォルトのヘルプメニューのようにhayabusaのコマンド(例: Windowsの場合は`hayabusa.exe`等、*nix/macの場合は`hayabusa`等)をバイナリのファイル名にできますか？
調べたら、以下の例がありました。ご参考まで。
https://stackoverflow.com/questions/71712400/how-to-refer-to-the-program-name-in-help-strings

2022-12-18 05:37 UTC, hitenkoku commented
@YamatoSecurity 提示していただいた例を確認してみました。

help_template側で{usage}を使うと https://github.com/Yamato-Security/hayabusa/pull/832#issuecomment-1356475597 で指定されている形の記載はできません(override_usageではバイナリネームを参照することはできず、指定した文字列でそのまま上書きする形になる)

help_template側で{bin}を使うと、clapの https://docs.rs/clap/latest/src/clap/output/help_template.rs.html#239 に記載がある通り、サブコマンドとファイル名が-で繋がれることになります。
(ex. test.exe csv-timelineであれば usageには test.exe-csv-timelineと表示されてしまう)

2022-12-18 06:11 UTC, hitenkoku commented
@YamatoSecurity  念のためclapのDiscussionで他の方法がないかどうかを聞いてみています。並行してhelp_templateでサブコマンドの間に-が入らないようにするpull-requestを出して置こうと思います。

https://github.com/clap-rs/clap/discussions/4561

2022-12-18 07:58 UTC, YamatoSecurity commented
> @YamatoSecurity 念のためclapのDiscussionで他の方法がないかどうかを聞いてみています。並行してhelp_templateでサブコマンドの間に-が入らないようにするpull-requestを出して置こうと思います。

なるほど、ありがとうございます！

2022-12-18 08:36 UTC, hitenkoku commented
すぐにマージされるかはわからないですが、このpull-requestはv2へのリリースには含めますか？

2022-12-18 09:28 UTC, YamatoSecurity commented
そうですね。これが一番重要なので、Major Updateって言えるようにマージしたいですね。(使い方が1.xと完全に変わっているので）
急に他のPRも沢山上がったので、どちらを先にマージするか悩みますね。先にこちらをマージしましょうか？

ごめんなさい、最近のコミットで`override_usage = "hayabusa [COMMAND] [OPTIONS]\n  hayabusa help [COMMAND]"`が無くなって、`hayabusa [OPTIONS] [COMMAND]`という風にコマンドが最後になっているので、override_usageのやり方に戻したいのですが、大丈夫ですか？Usageでhayabusaのファイル名が合わない可能性がある件はそんなに重要ではないので、取り敢えず、一番多いuse caseのWindowsに合わせて`hayabusa.exe`って書いたら良いと思います。次のMinorアップデートで修正したら良いと思います。

あとはヘルプメニューの時にStart timeを非表示にするだけですよね？それも大きな問題ではないので、次のMinorアップデートでも構いません。
あとはReadmeをこちらで更新していますが、それが終わったら、マージしますか？

2022-12-18 10:06 UTC, YamatoSecurity commented
あ、`level-tuning`の`-f <FILE>       Tune alert levels (default: ./rules/config/level_tuning.txt)`のlong versionの`--file`も追加しますか？ (`-f, --file <FILE>       Tune alert levels (default: ./rules/config/level_tuning.txt)`)

2022-12-18 10:40 UTC, hitenkoku commented
@YamatoSecurity マージをするとしたら他のものを優先してマージしておきたいです。機能追加によるパフォーマンスの影響とかを分けやすくしたいです。（動かなくなった理由が今回のサブコマンドの影響か、それとも機能実装自体に問題があったのかは分かっておいたほうが良いと思います。

2022-12-18 10:48 UTC, YamatoSecurity commented
了解です！では、そうしましょう。
サブコマンド前の状態の1.9とサブコマンド入りの2.0の２つのリリースを作ったら良いかもしれません。
因みに12/24か12/25にリリースしようと思っていますが、間に合わなさそうでしたら、年明けでも全然問題ありません。

2022-12-18 12:34 UTC, hitenkoku commented
承りました。それではApproveされた他のブランチをマージしていきます

2022-12-18 12:58 UTC, hitenkoku commented
承りました。まず現在のコマンドで動くものたちを1.9.0にする案が良いと思います。

2022-12-18 13:28 UTC, hitenkoku commented
誤ってマージすることを防ぐためにDraftにしておきました

2022-12-21 15:06 UTC, hitenkoku commented
@YamatoSecurity 1.9の機能もマージしてエラーについても直しておきました。テスト関連は通っていることを確認しましたが、ご確認のほどよろしくお願いいたします。
並行して今のmainブランチの最新のところにいったんv1.9.0のタグを打っておこうと思います(それをしていれば仮にこちらを先にマージしてもreleaseの参照はv1.9.0のタグに紐づけてv1.9.0をリリースすれば楽かと思っています)

2022-12-21 23:58 UTC, YamatoSecurity commented
対応、ありがとうございます！

以下の細かい修正だけお願いできますか？これが終わったら、v1.9をタグして、マージして良いと思います。

1. オプションなしのデフォルトヘルプ画面で前のように戻せますか？
```
Usage:
  hayabusa [OPTIONS] [COMMAND]
```
↓
```
Usage:
  hayabusa.exe <COMMAND> [OPTIONS]
  hayabusa.exe help <COMMAND>
```

2. csv-timeline, json-timeline, logon-summary, metrics, pivot-keywords-listの
```
Usage:
  csv-timeline [OPTIONS]
```
を
```
Usage:
  csv-timeline <INPUT> [OPTIONS]
```
に変更をお願いできますか？

3. csv-timeline, json-timeline, logon-summary, metrics, pivot-keywords-list等の全コマンドから
`-h, --help`と`-V, --version`の削除。
特に`csv-timeline -h`等のように`-h`を付けてもエラーが出力されるだけです。
デフォルトのヘルプ画面で既にバージョン情報が出力されるので、`-V`は無くても良いですよね？
非表示にできないんでしたっけ？

4. level-tuningのオプションで`-f` -> `-f, --file`

因みに、この間話していた「一部スピードアップのためにcollectとかで一旦Vecを作ってしまっているところをなるべくIteratorとかで対応できるようにしたところ、20秒くらいは縮まりました。こちらはひとまずv2.0とかのリリースが終わったら適宜出していこうと思います
」はマージ済みですか？

2022-12-22 06:20 UTC, hitenkoku commented
> 対応、ありがとうございます！
> 
> 以下の細かい修正だけお願いできますか？これが終わったら、v1.9をタグして、マージして良いと思います。
> 
> 1. オプションなしのデフォルトヘルプ画面で前のように戻せますか？
> 
> ```
> Usage:
>   hayabusa [OPTIONS] [COMMAND]
> ```
> 
> ↓
> 
> ```
> Usage:
>   hayabusa.exe <COMMAND> [OPTIONS]
>   hayabusa.exe help <COMMAND>
> ```
> 


> 2. csv-timeline, json-timeline, logon-summary, metrics, pivot-keywords-listの
> 
> ```
> Usage:
>   csv-timeline [OPTIONS]
> ```
> 
> を
> 
> ```
> Usage:
>   csv-timeline <INPUT> [OPTIONS]
> ```
> 
> に変更をお願いできますか？
> 

override_usageの方法で対応をします。

> 3. csv-timeline, json-timeline, logon-summary, metrics, pivot-keywords-list等の全コマンドから
>    `-h, --help`と`-V, --version`の削除。
>    特に`csv-timeline -h`等のように`-h`を付けてもエラーが出力されるだけです。
>    デフォルトのヘルプ画面で既にバージョン情報が出力されるので、`-V`は無くても良いですよね？
>    非表示にできないんでしたっけ？

こちらは非表示にできない理由としてhelp_template内で{version}と記載があったときにversionフラグがないと数値を読み込んでくれないという問題があります。また、update-rulesオプションでバージョンの比較をするときにversion番号を取得して比較しているのですが、そのときにこのversionの仕組みを使っていたと思います。念のためupdate-rules側の方で問題がなければ、help_templateから{version}を削除して--versionオプションを削除することは可能です。

helpについてはこちら側で制御ができないものになります。表示をしないとなるとhelpというコマンド自体が打てない可能性があります。こちらも確認します。

> 4. level-tuningのオプションで`-f` -> `-f, --file`
> 
<対応中>

> 因みに、この間話していた「一部スピードアップのためにcollectとかで一旦Vecを作ってしまっているところをなるべくIteratorとかで対応できるようにしたところ、20秒くらいは縮まりました。こちらはひとまずv2.0とかのリリースが終わったら適宜出していこうと思います 」はマージ済みですか？

こちらはマージはしていません。このpull-requestがだいぶ肥大化してしまっているのもあり、まとめて投入するのは避けたいと考えていますがいかがでしょうか。

2022-12-22 07:43 UTC, YamatoSecurity commented
> こちらはマージはしていません。このpull-requestがだいぶ肥大化してしまっているのもあり、まとめて投入するのは避けたいと考えていますがいかがでしょうか。

了解しました。はい、それでも大丈夫です！

2022-12-22 22:56 UTC, YamatoSecurity commented
@hitenkoku Readme等を更新しました。

確認したら、`csv-timeline`等は`-h`と`-V`はありますが、`./target/release/hayabusa help update-rules`は`-V`のみで、`help list-contributors`は`-h`も`-V`も表示されていません。

何が違うかな？`--debug`オプションのような非表示のやり方では駄目ですかね？

2022-12-23 00:24 UTC, hitenkoku commented
> @hitenkoku Readme等を更新しました。
> 
> 確認したら、`csv-timeline`等は`-h`と`-V`はありますが、`./target/release/hayabusa help update-rules`は`-V`のみで、`help list-contributors`は`-h`も`-V`も表示されていません。
> 
> 何が違うかな？`--debug`オプションのような非表示のやり方では駄目ですかね？

対応が遅くなり申し訳ございません。-Vについては対応ができました。ただし、help_templateに記載されている{version}は表示されなくなりましたのでそこはhelp_templateにバージョン番号をハードコードする形でで対応しようと思います。-hについては頂いている指摘を修正後に確認します。

2022-12-23 00:43 UTC, hitenkoku commented
@YamatoSecurity  ひとまず修正いたしました。念のためそちらでもご確認をよろしくお願いいたします。
タグはadd-JQdocumentationをマージしてからタグを打つ方がよろしいでしょうか。

もしv1.9.0のタグを特定のcommitに付与したいのであればURLをいただければこちらのほうでv1.9.0タグを用意しておきます(v2.0.0は今までどおりgithubのReleaseで作成すれば問題ないと思います)

2022-12-23 01:16 UTC, YamatoSecurity commented
@hitenkoku すみません、明日バタバタしそうなので、少し早いのですが、1.9.0をリリースしました。

`Hayabusa`にbacktickが入っていたので、削除しました。また、デフォルト画面でバージョンが表示されなくなったので、ハードコードしました。`-V`を消すのに`{version}`が使えなくなったんですね？
２点だけです:
1. update-rulesを実行したら、以下のエラーが出ます：
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:433:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
2. `update-rules`のLatest versionチェックする時に問題なさそうですか？

2022-12-23 02:15 UTC, hitenkoku commented
> `Hayabusa`にbacktickが入っていたので、削除しました。また、デフォルト画面でバージョンが表示されなくなったので、ハードコードしました。`-V`を消すのに`{version}`が使えなくなったんですね？ 

はい、その通りです。


> 
> 1. update-rulesを実行したら、以下のエラーが出ます：
> 
> ```
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:433:51
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> 2. `update-rules`のLatest versionチェックする時に問題なさそうですか？

該当のエラーはLatest versionチェックの時にclapの関数を利用していたため出たエラーでした。cargo.tomlから得られるバージョン番号を参照するように  https://github.com/Yamato-Security/hayabusa/pull/832/commits/0122f8c558a41876c6fb0c2012af86b4058245ac で修正しました

2022-12-23 03:05 UTC, YamatoSecurity approved these changes
中々長いやり取りすみません＆対応ありがとうございました！
大分良い感じだと思います。
これでマージしましょうか？

その後、スピードアップのPRをお願いできますか？

2022-12-23 03:12 UTC, hitenkoku commented
はい、大丈夫です。スピードアップをさせたprもこのブランチの最新版の変更をマージした上で、pull requestしておきます

2022-12-23 03:13 UTC, merged

2022-12-23 23:34 UTC, hitenkoku commented
@YamatoSecurity  @fukusuket 

スピードアップのための不要なcollect処理を除外した版を https://github.com/Yamato-Security/hayabusa/pull/847 で出しましたのでご確認のほどよろしくお願いいたします。