Feature/731 output logon types
Yamato-Security/hayabusa pull request #835
Opened 2022-12-17 16:25 UTC by garigariganzy

## What Changed

- Changed 1 ログオン成功、失敗の集計機能でコンピュータ名、ログオンタイプも含めた集計を行うように変更しました。
- Changed 2 ログオン成功、失敗毎で集計結果を表示するように変更しました。

## Evidence

![logonsummary_success](https://user-images.githubusercontent.com/25587634/208251567-92c00e94-4728-4e75-974d-89c3d404e761.png)

![logonsummary_failed](https://user-images.githubusercontent.com/25587634/208251578-800da995-70fd-4e62-a8bd-750eb4486b13.png)

Please describe the functionality gained by merging this pull-request and the evidence that the bug has been fixed.

2022-12-17 16:50 UTC, hitenkoku commented
@garigariganzy  PRありがとうございます。clippyでエラーが出ていますが、私の方で別ブランチで対応したので、問題なければ私の方でclippy errorの解消をしておきましょうか？

2022-12-17 23:00 UTC, garigariganzy commented
> @garigariganzy PRありがとうございます。clippyでエラーが出ていますが、私の方で別ブランチで対応したので、ソースコードの確認がてら問題なければ私の方でclippy errorの解消させていただいても良いでしょうか？

@hitenkoku ご確認ありがとうございます。自分で確認できたclippy errorについては、修正を行いましたが、すべて対応できていないです。お手数ですが、よろしくお願いします。

2022-12-18 06:46 UTC, hitenkoku requested changes

2022-12-18 06:46 UTC, hitenkoku commented on src/timeline/metrics.rs
> +                            username.unwrap().to_string(),
Valueの先頭および末尾に空白が入っている可能性があるため可能であればutils::value_to_string関数を利用するのはいかがでしょうか

2022-12-18 06:46 UTC, hitenkoku commented on src/timeline/timelines.rs
>                  username.pop();
ここの部分でpopとremoveをしている理由は何でしょうか？

2022-12-18 06:46 UTC, hitenkoku commented on src/timeline/timelines.rs
> +            let mut msges: Vec<String> = Vec::new();
1行のみの出力であればそのままprintln!を使って出力してください。

2022-12-18 07:52 UTC, YamatoSecurity commented
英語を少しだけ修正しました。
細かいところだけですが、ログオン番号がダブルクォートで囲まれている場合があるので、読み込む時にstripするようにできますか？
<img width="643" alt="Screen Shot 2022-12-18 at 4 47 56 PM" src="https://user-images.githubusercontent.com/71482215/208287281-561a6e2a-d7fb-427d-b1bf-b445f2714d7c.png">

2022-12-18 08:39 UTC, hitenkoku commented
@garigariganzy リリースが近づいているのでもし実装が時間がかかりそう、難しそうであればご連絡いただければ、私の方で引き継いで作っておきますがいかがでしょうか。

2022-12-18 11:04 UTC, garigariganzy commented
> @garigariganzy リリースが近づいているのでもし実装が時間がかかりそう、難しそうであればご連絡いただければ、私の方で引き継いで作っておきますがいかがでしょうか。

@hitenkoku 時間がかかりそうなので申し訳ないのですが、引き継いでいただけますでしょうか。遅くなり申し訳ございません。

2022-12-18 11:24 UTC, garigariganzy commented on src/timeline/timelines.rs
>                  username.pop();
@hitenkoku 前後のダブルコートの削除とした処理であったのでコンピュータ名（hostname）でも同じように利用しました。

2022-12-18 11:36 UTC, hitenkoku commented on src/timeline/timelines.rs
>                  username.pop();
ご回答ありがとうございます。私の方で引継ぎをさせていただきます。

2022-12-18 12:05 UTC, hitenkoku commented on src/timeline/timelines.rs
> +            let mut msges: Vec<String> = Vec::new();
https://github.com/Yamato-Security/hayabusa/pull/835/commits/b72917af151ab3bbb729a5624559b34e7e8bda24 で対応済み

2022-12-18 12:05 UTC, hitenkoku commented on src/timeline/timelines.rs
>                  username.pop();
https://github.com/Yamato-Security/hayabusa/pull/835/commits/19644a1314b885e271fb5315d865ed75691f61b7 で対応完了

2022-12-18 12:36 UTC, hitenkoku commented
これ少し確認してみましたが、ul やnullとなっているのは値がないということなのでそこはdefaultの空白とするように変更しておきます

2022-12-18 12:43 UTC, YamatoSecurity commented
> これ少し確認してみましたが、ul やnullとなっているのは値がないということなのでそこはdefaultの空白とするように変更しておきます

すみません、空白だと、バグと勘違いされるかもしれないので、`n/a`に変更をお願いできますか？

(LogonTypeがヌルになることがあるんですね）

2022-12-18 12:50 UTC, hitenkoku commented
@YamatoSecurity  対応が完了しました。念のため動作確認をお願いいたします。

2022-12-18 12:51 UTC, hitenkoku commented on src/timeline/timelines.rs
>                  username.pop();
対応誤りがあったため、 revertした後に対応完了

2022-12-18 12:53 UTC, hitenkoku commented on src/timeline/metrics.rs
> +                            username.unwrap().to_string(),
対応完了。utils::value_to_stringを修正したところ既存処理への影響があり、テストが通らなくなった。類似の処理をしているget_serde_number_to_stringで修正をかけて実行できることを確認した。
https://github.com/Yamato-Security/hayabusa/pull/835/commits/eadae65b4b456973e85fb936f32389b57ec22d30 で対応完了

2022-12-18 12:55 UTC, hitenkoku approved these changes
確認が完了しました。実装はokです。LGTM

2022-12-18 13:00 UTC, hitenkoku commented
このような感じで該当のデータがない場合はn/aで出力されることを確認しました。


``` powershell
> ./731.exe -f ..\hayabusa-sample-evtx\DeepBlueCLI\many-events-application.evtx -L -q
Generating Logon Summary

Start time: 2022/12/18 21:59

Analyzing event files: 1
Total file size: 2.2 MB

1 / 1 [=============================================================================================================================] 100.00 % Evtx File Path: ..\hayabusa-sample-evtx\DeepBlueCLI\many-events-application.evtx


Total Event Records: 2216

First Timestamp: "2013-10-23T16:16:29.000000Z"
Last Timestamp: "2016-09-20T13:15:31.000000Z"

 Logon Summary:

 Successful Logons:
 No logon Successful events were detected.


 Failed Logons:
╭──────┬───────────────┬────────────┬────────╮
│ User ┆ Hostname      ┆ Logon Type ┆ Failed │
╞══════╪═══════════════╪════════════╪════════╡
│ n/a  ┆ IE8Win7       ┆ n/a        ┆ 18     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ n/a  ┆ IE10Win7      ┆ n/a        ┆ 15     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ n/a  ┆ IE9WIN7       ┆ n/a        ┆ 2      │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ n/a  ┆ IE8WIN7       ┆ n/a        ┆ 1      │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ n/a  ┆ IE9Win7       ┆ n/a        ┆ 1      │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ n/a  ┆ 37L4247D28-05 ┆ n/a        ┆ 1      │
╰──────┴───────────────┴────────────┴────────╯

Elapsed time: 00:00:02.291
```

2022-12-19 00:34 UTC, YamatoSecurity commented
hayabusa-sample-evtxに対してスキャンしたら問題ありませんが、壊れているevtxが入っているディレクトリをスキャンしたら以下のエラーでpanicしています。

<img width="839" alt="Screen Shot 2022-12-19 at 9 33 06 AM" src="https://user-images.githubusercontent.com/71482215/208327811-712dfb95-5b25-4b1f-a310-ca638ad6938f.png">

2022-12-19 01:19 UTC, hitenkoku commented
承りました。いったん確認します

2022-12-19 01:25 UTC, hitenkoku commented
@YamatoSecurity 対応完了しました。お手数ですが、壊れたevtxに対して実行してもエラーなく動作しているかご確認のほどよろしくお願いします。

2022-12-19 01:37 UTC, YamatoSecurity commented
エラーが無くなりました。ありがとうございました！
ソースを見たら、`Channel`が`Security`であることをチェックしていなさそうですが、イベントIDだけで判定していますか？
それだと、誤検知が出ると思います。(ユーザ名やLogonTypeフィールドはあるはずなので、恐らくSecurityでないイベント4624/4625で誤検知していると思います。）

その確認をお願いできますか？

2022-12-19 02:28 UTC, hitenkoku commented
はい、現状はチャンネルでのフィルタリングはしていなさそうです。ChannelがSecurityであることを条件として追加しておきます

2022-12-19 04:05 UTC, hitenkoku commented
@YamatoSecurity  Secuirty Channelのものを対象にするように修正完了しました。ご確認のほどよろしくお願いいたします。

2022-12-19 05:33 UTC, hitenkoku approved these changes
追加のコミット分の確認完了

2022-12-19 05:44 UTC, YamatoSecurity commented
@hitenkoku 
対応、ありがとうございました！
`n/a`が無くなって、安心しました。

最後に、またお願いで誠に申し訳ありませんが、以下の３つをお願いできますか？

1. ログオン番号を覚えるのが大変で横幅がまだ余裕があるので、以下のようにLogon Type番号をLogon Type番号と説明に置換をお願いできますか？
`0` -> `0 - System`
`2` -> `1 - Interactive`
`3` -> `3 - Network`
`4` -> `4 - Batch`
`5` -> `5 - Service`
`7` -> `7 - Unlock`
`8` -> `8 - NetworkCleartext`
`9` -> `9 - NewInteractive`
`10` -> `10 - RemoteInteractive`
`11` -> `11 - CachedInteractive`
`12` -> `12 - CachedRemoteInteractive`
`13` -> `13 - CachedUnlock`

2. ログオン元が分からないと誤検知の判断が難しいので、User、Hostname、LogonType以外に`Source Computer` (%WorkstationName%)と`Source IP` (%IpAddress%)の列もお願いできますか？

3. 順番をSuccessful/Failed | User | Hostname | Logon Type | Source Computer | Source IP という順番にできますか？

m(__)m

2022-12-19 07:03 UTC, hitenkoku commented
@YamatoSecurity ここだけLogonTypeの番号と表示の内容が違いますが大丈夫ですか？一応枠組みの作成を進めておきます

> 2 -> 1 - Interactive

2022-12-19 07:38 UTC, YamatoSecurity commented
> @YamatoSecurity ここだけLogonTypeの番号と表示の内容が違いますが大丈夫ですか？一応枠組みの作成を進めておきます

あ、ごめんなさい、タイポでした。`2 - Interactive`です。

2022-12-19 12:07 UTC, hitenkoku commented
@YamatoSecurity  https://github.com/Yamato-Security/hayabusa/pull/835/commits/e277bfd7deb3335dd2e9c55fd3aa19d63cbfd963 で対応完了しました。ご確認のほどよろしくお願いいたします。

2022-12-19 14:27 UTC, YamatoSecurity approved these changes
完璧です！ありがとうございました！

2022-12-19 15:26 UTC, hitenkoku commented
ご確認ありがとうございます。それではマージさせていただきます。

2022-12-19 15:26 UTC, merged